from __future__ import annotations

FLAG_SIM = "S"
FLAG_NAO = "N"

STATUS_PDV_ATIVO = "ativo"
STATUS_PDV_INATIVO = "inativo"

STATUS_CAIXA_ABERTO = "aberto"
STATUS_CAIXA_FECHADO = "fechado"

CLIENTE_PADRAO_CONSUMIDOR_FINAL = "CONSUMIDOR_FINAL"
CLIENTE_PADRAO_SELECIONAR = "SELECIONAR_NO_MOMENTO"

REGRA_DESCONTO_PERMITIR = "PERMITIR_DESCONTO"
REGRA_DESCONTO_EXIGIR_AUTORIZACAO = "EXIGIR_AUTORIZACAO"

PRIORIDADE_PROMOCAO_ANTES_DESCONTO = "PROMOCAO_ANTES_DESCONTO"
PRIORIDADE_DESCONTO_ANTES_PROMOCAO = "DESCONTO_ANTES_PROMOCAO"

PERFIL_LOG_OPERACIONAL = "OPERACIONAL"
PERFIL_LOG_DETALHADO = "DETALHADO"
PERFIL_LOG_SILENCIOSO = "SILENCIOSO"

REGIME_TRIBUTARIO_SIMPLES_NACIONAL = "SIMPLES_NACIONAL"

CLIENTE_SISTEMA_CONSUMIDOR_FINAL = FLAG_SIM

STATUS_VENDA_CONCLUIDA = "CONCLUIDA"
STATUS_VENDA_CONCLUIDA_COM_PENDENCIA = "CONCLUIDA_COM_PENDENCIA"
STATUS_VENDA_PARCIALMENTE_REEMBOLSADA = "PARCIALMENTE_REEMBOLSADA"
STATUS_VENDA_REEMBOLSADA = "REEMBOLSADA"
STATUS_VENDA_OPERACIONAL = (
    STATUS_VENDA_CONCLUIDA,
    STATUS_VENDA_CONCLUIDA_COM_PENDENCIA,
    STATUS_VENDA_PARCIALMENTE_REEMBOLSADA,
    STATUS_VENDA_REEMBOLSADA,
)

STATUS_CONTA_PENDENTE = "PENDENTE"
STATUS_CONTA_PARCIALMENTE_RECEBIDA = "PARCIALMENTE_RECEBIDA"
STATUS_CONTA_QUITADA = "QUITADA"
STATUS_CONTA_VENCIDA = "VENCIDA"
STATUS_CONTA_ABERTAS = (
    STATUS_CONTA_PENDENTE,
    STATUS_CONTA_PARCIALMENTE_RECEBIDA,
)

STATUS_REEMBOLSO_CONCLUIDO = "CONCLUIDO"
STATUS_REEMBOLSO_CANCELADO = "CANCELADO"
TIPO_REEMBOLSO_PARCIAL = "PARCIAL"
TIPO_REEMBOLSO_TOTAL = "TOTAL"

STATUS_PROMOCAO_RASCUNHO = "RASCUNHO"
STATUS_PROMOCAO_AGENDADA = "AGENDADA"
STATUS_PROMOCAO_ATIVA = "ATIVA"
STATUS_PROMOCAO_ENCERRADA = "ENCERRADA"
STATUS_PROMOCAO_CANCELADA = "CANCELADA"
STATUS_PROMOCAO_EDITAVEL = (
    STATUS_PROMOCAO_RASCUNHO,
    STATUS_PROMOCAO_AGENDADA,
    STATUS_PROMOCAO_ATIVA,
)


def flag_ativa(valor: object, *, default: str = FLAG_NAO) -> bool:
    return str(valor or default).strip().upper() == FLAG_SIM


def bool_para_flag(valor: bool) -> str:
    return FLAG_SIM if bool(valor) else FLAG_NAO


def alternar_flag(valor: object, *, default: str = FLAG_NAO) -> str:
    return FLAG_NAO if flag_ativa(valor, default=default) else FLAG_SIM
