from PyQt5 import QtCore, QtWidgets

class Ui_FinalizarPendenciaDialog(object):
    def setupUi(self, FinalizarPendenciaDialog):
        FinalizarPendenciaDialog.setObjectName("FinalizarPendenciaDialog")
        FinalizarPendenciaDialog.resize(680, 460)
        FinalizarPendenciaDialog.setMinimumSize(QtCore.QSize(640, 430))
        FinalizarPendenciaDialog.setStyleSheet(
            "QDialog{background-color:#edf4fb;}"
            "QFrame#frameCard{background-color:#ffffff;border:1px solid #c7d9ea;border-radius:12px;}"
            "QLabel{color:#143d67;font-size:12px;}"
            "QLabel#lblTitulo{font-size:24px;font-weight:bold;color:#123f6f;}"
            "QLabel#lblSubtitulo{font-size:12px;color:#5a7a9a;}"
            "QLabel.propLabel{font-size:11px;font-weight:bold;color:#4f6f90;letter-spacing:0.5px;}"
            "QLabel.propValor{font-size:18px;font-weight:bold;color:#123f6f;}"
            "QDateEdit,QPlainTextEdit{background-color:#f9fcff;border:1px solid #b9d0e5;border-radius:8px;color:#143d67;padding:8px;}"
            "QDateEdit{min-height:40px;font-size:13px;}"
            "QPlainTextEdit{font-size:13px;}"
            "QPushButton{min-height:42px;border-radius:8px;font-size:13px;font-weight:bold;padding:0 18px;}"
            "QPushButton#btnCancelar{background-color:#eef4fa;border:1px solid #c2d6e8;color:#345c82;}"
            "QPushButton#btnCancelar:hover{background-color:#e3edf6;}"
            "QPushButton#btnConfirmar{background-color:#2f7ed1;border:1px solid #2568af;color:#ffffff;}"
            "QPushButton#btnConfirmar:hover{background-color:#3a8ae0;}"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(FinalizarPendenciaDialog)
        self.verticalLayout.setContentsMargins(22, 22, 22, 22)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCard = QtWidgets.QFrame(FinalizarPendenciaDialog)
        self.frameCard.setObjectName("frameCard")
        self.cardLayout = QtWidgets.QVBoxLayout(self.frameCard)
        self.cardLayout.setContentsMargins(28, 26, 28, 24)
        self.cardLayout.setSpacing(20)
        self.cardLayout.setObjectName("cardLayout")
        self.lblTitulo = QtWidgets.QLabel(self.frameCard)
        self.lblTitulo.setObjectName("lblTitulo")
        self.cardLayout.addWidget(self.lblTitulo)
        self.lblSubtitulo = QtWidgets.QLabel(self.frameCard)
        self.lblSubtitulo.setWordWrap(True)
        self.lblSubtitulo.setObjectName("lblSubtitulo")
        self.cardLayout.addWidget(self.lblSubtitulo)
        self.gridResumo = QtWidgets.QGridLayout()
        self.gridResumo.setHorizontalSpacing(28)
        self.gridResumo.setVerticalSpacing(10)
        self.gridResumo.setObjectName("gridResumo")
        self.lblClienteLabel = QtWidgets.QLabel(self.frameCard)
        self.lblClienteLabel.setObjectName("lblClienteLabel")
        self.lblClienteLabel.setProperty("class", "propLabel")
        self.gridResumo.addWidget(self.lblClienteLabel, 0, 0, 1, 1)
        self.lblClienteValor = QtWidgets.QLabel(self.frameCard)
        self.lblClienteValor.setObjectName("lblClienteValor")
        self.lblClienteValor.setProperty("class", "propValor")
        self.gridResumo.addWidget(self.lblClienteValor, 1, 0, 1, 1)
        self.lblTotalLabel = QtWidgets.QLabel(self.frameCard)
        self.lblTotalLabel.setObjectName("lblTotalLabel")
        self.lblTotalLabel.setProperty("class", "propLabel")
        self.gridResumo.addWidget(self.lblTotalLabel, 0, 1, 1, 1)
        self.lblTotalValor = QtWidgets.QLabel(self.frameCard)
        self.lblTotalValor.setObjectName("lblTotalValor")
        self.lblTotalValor.setProperty("class", "propValor")
        self.gridResumo.addWidget(self.lblTotalValor, 1, 1, 1, 1)
        self.lblPagoLabel = QtWidgets.QLabel(self.frameCard)
        self.lblPagoLabel.setObjectName("lblPagoLabel")
        self.lblPagoLabel.setProperty("class", "propLabel")
        self.gridResumo.addWidget(self.lblPagoLabel, 0, 2, 1, 1)
        self.lblPagoValor = QtWidgets.QLabel(self.frameCard)
        self.lblPagoValor.setObjectName("lblPagoValor")
        self.lblPagoValor.setProperty("class", "propValor")
        self.gridResumo.addWidget(self.lblPagoValor, 1, 2, 1, 1)
        self.lblAbertoLabel = QtWidgets.QLabel(self.frameCard)
        self.lblAbertoLabel.setObjectName("lblAbertoLabel")
        self.lblAbertoLabel.setProperty("class", "propLabel")
        self.gridResumo.addWidget(self.lblAbertoLabel, 0, 3, 1, 1)
        self.lblAbertoValor = QtWidgets.QLabel(self.frameCard)
        self.lblAbertoValor.setObjectName("lblAbertoValor")
        self.lblAbertoValor.setProperty("class", "propValor")
        self.gridResumo.addWidget(self.lblAbertoValor, 1, 3, 1, 1)
        self.cardLayout.addLayout(self.gridResumo)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setHorizontalSpacing(16)
        self.formLayout.setVerticalSpacing(14)
        self.formLayout.setObjectName("formLayout")
        self.lblVencimento = QtWidgets.QLabel(self.frameCard)
        self.lblVencimento.setObjectName("lblVencimento")
        self.dateVencimento = QtWidgets.QDateEdit(self.frameCard)
        self.dateVencimento.setCalendarPopup(True)
        self.dateVencimento.setObjectName("dateVencimento")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblVencimento)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateVencimento)
        self.lblObservacao = QtWidgets.QLabel(self.frameCard)
        self.lblObservacao.setObjectName("lblObservacao")
        self.textObservacao = QtWidgets.QPlainTextEdit(self.frameCard)
        self.textObservacao.setMinimumHeight(150)
        self.textObservacao.setObjectName("textObservacao")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblObservacao)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textObservacao)
        self.cardLayout.addLayout(self.formLayout)
        self.botoesLayout = QtWidgets.QHBoxLayout()
        self.botoesLayout.setSpacing(10)
        self.botoesLayout.setObjectName("botoesLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesLayout.addItem(spacerItem)
        self.btnCancelar = QtWidgets.QPushButton(self.frameCard)
        self.btnCancelar.setObjectName("btnCancelar")
        self.botoesLayout.addWidget(self.btnCancelar)
        self.btnConfirmar = QtWidgets.QPushButton(self.frameCard)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.botoesLayout.addWidget(self.btnConfirmar)
        self.cardLayout.addLayout(self.botoesLayout)
        self.verticalLayout.addWidget(self.frameCard)

        self.retranslateUi(FinalizarPendenciaDialog)
        QtCore.QMetaObject.connectSlotsByName(FinalizarPendenciaDialog)

    def retranslateUi(self, FinalizarPendenciaDialog):
        _translate = QtCore.QCoreApplication.translate
        FinalizarPendenciaDialog.setWindowTitle(_translate("FinalizarPendenciaDialog", "CSPdv - Finalizar com Pendência"))
        self.lblTitulo.setText(_translate("FinalizarPendenciaDialog", "Finalizar com Pendência"))
        self.lblSubtitulo.setText(_translate("FinalizarPendenciaDialog", "Conclua a venda com pagamento parcial e gere automaticamente a pendência financeira do cliente."))
        self.lblClienteLabel.setText(_translate("FinalizarPendenciaDialog", "CLIENTE"))
        self.lblClienteValor.setText(_translate("FinalizarPendenciaDialog", "Consumidor Final"))
        self.lblTotalLabel.setText(_translate("FinalizarPendenciaDialog", "TOTAL"))
        self.lblTotalValor.setText(_translate("FinalizarPendenciaDialog", "R$ 0,00"))
        self.lblPagoLabel.setText(_translate("FinalizarPendenciaDialog", "PAGO AGORA"))
        self.lblPagoValor.setText(_translate("FinalizarPendenciaDialog", "R$ 0,00"))
        self.lblAbertoLabel.setText(_translate("FinalizarPendenciaDialog", "EM ABERTO"))
        self.lblAbertoValor.setText(_translate("FinalizarPendenciaDialog", "R$ 0,00"))
        self.lblVencimento.setText(_translate("FinalizarPendenciaDialog", "Vencimento *"))
        self.lblObservacao.setText(_translate("FinalizarPendenciaDialog", "Observação"))
        self.btnCancelar.setText(_translate("FinalizarPendenciaDialog", "Cancelar"))
        self.btnConfirmar.setText(_translate("FinalizarPendenciaDialog", "Finalizar com Pendência"))
