# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\cspdv\ui\venda\frente_loja.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrenteLoja(object):
    def setupUi(self, FrenteLoja):
        FrenteLoja.setObjectName("FrenteLoja")
        FrenteLoja.resize(1376, 744)
        FrenteLoja.setStyleSheet("\n"
"    QMainWindow { background-color: #0f2030; font-family: Arial; }\n"
"    QLabel { background-color: transparent; }\n"
"   ")
        self.centralWidget = QtWidgets.QWidget(FrenteLoja)
        self.centralWidget.setObjectName("centralWidget")
        self.rootHLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.rootHLayout.setContentsMargins(0, 0, 0, 0)
        self.rootHLayout.setSpacing(0)
        self.rootHLayout.setObjectName("rootHLayout")
        self.frameSidebar = QtWidgets.QFrame(self.centralWidget)
        self.frameSidebar.setMinimumWidth(224)
        self.frameSidebar.setMaximumWidth(224)
        self.frameSidebar.setStyleSheet("\n"
"        QFrame#frameSidebar {\n"
"         background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"          stop:0 #0a1828, stop:1 #0f2038);\n"
"         border-right: 2px solid #1a3a5a;\n"
"        }\n"
"        QPushButton[navBtn=\"true\"] {\n"
"         background-color: transparent;\n"
"         color: #4a7a9a;\n"
"         font-size: 12px;\n"
"         font-weight: bold;\n"
"         border: none;\n"
"         border-left: 3px solid transparent;\n"
"         border-radius: 0px;\n"
"         padding: 11px 16px;\n"
"         text-align: left;\n"
"         min-height: 46px;\n"
"        }\n"
"        QPushButton[navBtn=\"true\"]:hover {\n"
"         background-color: rgba(255,255,255,6);\n"
"         color: #8ab4d0;\n"
"         border-left: 3px solid rgba(53,133,200,60);\n"
"        }\n"
"        QPushButton[navBtn=\"true\"]:checked {\n"
"         background-color: rgba(53,133,200,18);\n"
"         color: white;\n"
"         border-left: 3px solid #3585c8;\n"
"        }\n"
"        QPushButton[navBtn=\"true\"]:disabled {\n"
"         color: #1a3a5a;\n"
"         border-left: 3px solid transparent;\n"
"         background-color: transparent;\n"
"        }\n"
"       ")
        self.frameSidebar.setObjectName("frameSidebar")
        self.sidebarVLayout = QtWidgets.QVBoxLayout(self.frameSidebar)
        self.sidebarVLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarVLayout.setSpacing(0)
        self.sidebarVLayout.setObjectName("sidebarVLayout")
        self.frameSidebarOperador = QtWidgets.QFrame(self.frameSidebar)
        self.frameSidebarOperador.setStyleSheet("\n"
"           QFrame#frameSidebarOperador {\n"
"            background-color: rgba(255,255,255,5);\n"
"            border-bottom: 1px solid #1a3a5a;\n"
"           }\n"
"          ")
        self.frameSidebarOperador.setObjectName("frameSidebarOperador")
        self.operadorHL = QtWidgets.QHBoxLayout(self.frameSidebarOperador)
        self.operadorHL.setContentsMargins(12, 8, 12, 8)
        self.operadorHL.setSpacing(8)
        self.operadorHL.setObjectName("operadorHL")
        self.lblOpIcone = QtWidgets.QLabel(self.frameSidebarOperador)
        self.lblOpIcone.setStyleSheet("font-size:22px;")
        self.lblOpIcone.setObjectName("lblOpIcone")
        self.operadorHL.addWidget(self.lblOpIcone)
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblOpNome = QtWidgets.QLabel(self.frameSidebarOperador)
        self.lblOpNome.setStyleSheet("color:#f5fbff;font-size:20px;font-weight:bold;")
        self.lblOpNome.setObjectName("lblOpNome")
        self.vboxlayout.addWidget(self.lblOpNome)
        self.lblCaixaStatus = QtWidgets.QLabel(self.frameSidebarOperador)
        self.lblCaixaStatus.setStyleSheet("color:#ff8a7a;font-size:12px;font-weight:bold;")
        self.lblCaixaStatus.setObjectName("lblCaixaStatus")
        self.vboxlayout.addWidget(self.lblCaixaStatus)
        self.operadorHL.addLayout(self.vboxlayout)
        self.sidebarVLayout.addWidget(self.frameSidebarOperador)
        self.lblSecaoPrincipal = QtWidgets.QLabel(self.frameSidebar)
        self.lblSecaoPrincipal.setStyleSheet("color:#3f8ed6;font-size:15px;font-weight:bold;letter-spacing:1px;padding:6px 16px 2px 16px;")
        self.lblSecaoPrincipal.setObjectName("lblSecaoPrincipal")
        self.sidebarVLayout.addWidget(self.lblSecaoPrincipal)
        self.btnNavAbertura = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavAbertura.setCheckable(True)
        self.btnNavAbertura.setChecked(True)
        self.btnNavAbertura.setObjectName("btnNavAbertura")
        self.sidebarVLayout.addWidget(self.btnNavAbertura)
        self.btnNavVendas = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavVendas.setEnabled(False)
        self.btnNavVendas.setCheckable(True)
        self.btnNavVendas.setObjectName("btnNavVendas")
        self.sidebarVLayout.addWidget(self.btnNavVendas)
        self.btnNavPreVenda = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavPreVenda.setEnabled(False)
        self.btnNavPreVenda.setCheckable(True)
        self.btnNavPreVenda.setObjectName("btnNavPreVenda")
        self.sidebarVLayout.addWidget(self.btnNavPreVenda)
        self.btnNavConsulta = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavConsulta.setEnabled(False)
        self.btnNavConsulta.setCheckable(True)
        self.btnNavConsulta.setObjectName("btnNavConsulta")
        self.sidebarVLayout.addWidget(self.btnNavConsulta)
        self.lblSecaoCaixa = QtWidgets.QLabel(self.frameSidebar)
        self.lblSecaoCaixa.setStyleSheet("color:#3f8ed6;font-size:13px;font-weight:bold;letter-spacing:1px;padding:8px 16px 2px 16px;")
        self.lblSecaoCaixa.setObjectName("lblSecaoCaixa")
        self.sidebarVLayout.addWidget(self.lblSecaoCaixa)
        self.btnNavMovimentacao = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavMovimentacao.setEnabled(False)
        self.btnNavMovimentacao.setCheckable(True)
        self.btnNavMovimentacao.setObjectName("btnNavMovimentacao")
        self.sidebarVLayout.addWidget(self.btnNavMovimentacao)
        self.btnNavFechamento = QtWidgets.QPushButton(self.frameSidebar)
        self.btnNavFechamento.setEnabled(False)
        self.btnNavFechamento.setCheckable(True)
        self.btnNavFechamento.setObjectName("btnNavFechamento")
        self.sidebarVLayout.addWidget(self.btnNavFechamento)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.sidebarVLayout.addItem(spacerItem)
        self.frameSidebarFooter = QtWidgets.QFrame(self.frameSidebar)
        self.frameSidebarFooter.setStyleSheet("\n"
"           QFrame#frameSidebarFooter {\n"
"            background-color: rgba(0,0,0,20);\n"
"            border-top: 1px solid #1a3a5a;\n"
"           }\n"
"          ")
        self.frameSidebarFooter.setObjectName("frameSidebarFooter")
        self.footerVLayout = QtWidgets.QVBoxLayout(self.frameSidebarFooter)
        self.footerVLayout.setContentsMargins(14, 10, 14, 10)
        self.footerVLayout.setSpacing(2)
        self.footerVLayout.setObjectName("footerVLayout")
        self.lblSidebarDataHora = QtWidgets.QLabel(self.frameSidebarFooter)
        self.lblSidebarDataHora.setStyleSheet("color:#5f93c2;font-size:13px;font-weight:bold;")
        self.lblSidebarDataHora.setObjectName("lblSidebarDataHora")
        self.footerVLayout.addWidget(self.lblSidebarDataHora)
        self.lblSidebarHora = QtWidgets.QLabel(self.frameSidebarFooter)
        self.lblSidebarHora.setStyleSheet("color:#3f8ed6;font-size:22px;font-weight:bold;")
        self.lblSidebarHora.setObjectName("lblSidebarHora")
        self.footerVLayout.addWidget(self.lblSidebarHora)
        self.btnSairLoja = QtWidgets.QPushButton(self.frameSidebarFooter)
        self.btnSairLoja.setStyleSheet("\n"
"              QPushButton{background-color:rgba(180,30,30,120);color:#ff8080;font-size:11px;font-weight:bold;border:1px solid rgba(180,30,30,80);border-radius:4px;padding:4px 8px;}\n"
"              QPushButton:hover{background-color:rgba(200,40,40,160);}\n"
"              QPushButton:pressed{background-color:rgba(140,20,20,160);}\n"
"             ")
        self.btnSairLoja.setObjectName("btnSairLoja")
        self.footerVLayout.addWidget(self.btnSairLoja)
        self.sidebarVLayout.addWidget(self.frameSidebarFooter)
        self.rootHLayout.addWidget(self.frameSidebar)
        self.stackedContent = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedContent.setStyleSheet("QStackedWidget { background-color: #0f2030; }")
        self.stackedContent.setObjectName("stackedContent")
        self.pageDefault = QtWidgets.QWidget()
        self.pageDefault.setStyleSheet("QWidget { background-color: #0f2030; }")
        self.pageDefault.setObjectName("pageDefault")
        self.defaultVLayout = QtWidgets.QVBoxLayout(self.pageDefault)
        self.defaultVLayout.setObjectName("defaultVLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.defaultVLayout.addItem(spacerItem1)
        self.lblDefaultMsg = QtWidgets.QLabel(self.pageDefault)
        self.lblDefaultMsg.setStyleSheet("color:#7fb2df;font-size:20px;font-weight:600;line-height:1.4;")
        self.lblDefaultMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDefaultMsg.setObjectName("lblDefaultMsg")
        self.defaultVLayout.addWidget(self.lblDefaultMsg)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.defaultVLayout.addItem(spacerItem2)
        self.stackedContent.addWidget(self.pageDefault)
        self.rootHLayout.addWidget(self.stackedContent)
        self.rootHLayout.setStretch(0, 1)
        self.rootHLayout.setStretch(1, 7)
        FrenteLoja.setCentralWidget(self.centralWidget)

        self.retranslateUi(FrenteLoja)
        self.stackedContent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FrenteLoja)

    def retranslateUi(self, FrenteLoja):
        _translate = QtCore.QCoreApplication.translate
        FrenteLoja.setWindowTitle(_translate("FrenteLoja", "CSPdv - Frente de Loja"))
        self.lblOpIcone.setText(_translate("FrenteLoja", "👤"))
        self.lblOpNome.setText(_translate("FrenteLoja", "ADMIN"))
        self.lblCaixaStatus.setText(_translate("FrenteLoja", "● Caixa Fechado"))
        self.lblSecaoPrincipal.setText(_translate("FrenteLoja", "OPERAÇÕES"))
        self.btnNavAbertura.setText(_translate("FrenteLoja", "🔑  Abertura de Caixa"))
        self.btnNavVendas.setText(_translate("FrenteLoja", "🛒  Vendas"))
        self.btnNavPreVenda.setText(_translate("FrenteLoja", "📋  Pré-Venda"))
        self.btnNavConsulta.setText(_translate("FrenteLoja", "🔍  Consulta de Preços"))
        self.lblSecaoCaixa.setText(_translate("FrenteLoja", "CAIXA"))
        self.btnNavMovimentacao.setText(_translate("FrenteLoja", "💳  Movimentação"))
        self.btnNavFechamento.setText(_translate("FrenteLoja", "🔒  Fechar Caixa"))
        self.lblSidebarDataHora.setText(_translate("FrenteLoja", "--/--/----"))
        self.lblSidebarHora.setText(_translate("FrenteLoja", "--:--:--"))
        self.btnSairLoja.setText(_translate("FrenteLoja", "➔  Sair da Loja"))
        self.lblDefaultMsg.setText(_translate("FrenteLoja", "Carregando..."))
