# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\cspdv\ui\venda\modal_confirmacao_venda.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModalConfirmacaoVenda(object):
    def setupUi(self, ModalConfirmacaoVenda):
        ModalConfirmacaoVenda.setObjectName("ModalConfirmacaoVenda")
        ModalConfirmacaoVenda.resize(560, 580)
        ModalConfirmacaoVenda.setModal(True)
        ModalConfirmacaoVenda.setStyleSheet("QDialog { background-color: #e8f2fa; font-family: Arial; }")
        self.mainVLayout = QtWidgets.QVBoxLayout(ModalConfirmacaoVenda)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameTitleBar = QtWidgets.QFrame(ModalConfirmacaoVenda)
        self.frameTitleBar.setMinimumHeight(42)
        self.frameTitleBar.setMaximumHeight(42)
        self.frameTitleBar.setStyleSheet("\n"
"       QFrame#frameTitleBar {\n"
"        background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"         stop:0 #3d90d8, stop:1 #1a5fa0);\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"       }\n"
"      ")
        self.frameTitleBar.setObjectName("frameTitleBar")
        self.titleHL = QtWidgets.QHBoxLayout(self.frameTitleBar)
        self.titleHL.setContentsMargins(14, 0, 10, 0)
        self.titleHL.setSpacing(8)
        self.titleHL.setObjectName("titleHL")
        self.lblTitleIcon = QtWidgets.QLabel(self.frameTitleBar)
        self.lblTitleIcon.setMaximumWidth(22)
        self.lblTitleIcon.setStyleSheet("font-size:16px;")
        self.lblTitleIcon.setObjectName("lblTitleIcon")
        self.titleHL.addWidget(self.lblTitleIcon)
        self.lblTitulo = QtWidgets.QLabel(self.frameTitleBar)
        self.lblTitulo.setStyleSheet("color:white;font-size:13px;font-weight:bold;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.titleHL.addWidget(self.lblTitulo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleHL.addItem(spacerItem)
        self.btnFechar = QtWidgets.QPushButton(self.frameTitleBar)
        self.btnFechar.setMinimumSize(QtCore.QSize(22, 22))
        self.btnFechar.setMaximumSize(QtCore.QSize(22, 22))
        self.btnFechar.setStyleSheet("\n"
"          QPushButton{background-color:#cc2222;border:none;border-radius:11px;color:white;font-size:11px;font-weight:bold;}\n"
"          QPushButton:hover{background-color:#e03030;}\n"
"          QPushButton:pressed{background-color:#aa1010;}\n"
"         ")
        self.btnFechar.setObjectName("btnFechar")
        self.titleHL.addWidget(self.btnFechar)
        self.mainVLayout.addWidget(self.frameTitleBar)
        self.frameConteudo = QtWidgets.QFrame(ModalConfirmacaoVenda)
        self.frameConteudo.setStyleSheet("\n"
"       QFrame#frameConteudo {\n"
"        background-color: #e8f2fa;\n"
"        border: 2px solid #2a70b8;\n"
"        border-top: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"       }\n"
"      ")
        self.frameConteudo.setObjectName("frameConteudo")
        self.conteudoVLayout = QtWidgets.QVBoxLayout(self.frameConteudo)
        self.conteudoVLayout.setContentsMargins(16, 14, 16, 14)
        self.conteudoVLayout.setSpacing(10)
        self.conteudoVLayout.setObjectName("conteudoVLayout")
        self.frameInfoVenda = QtWidgets.QFrame(self.frameConteudo)
        self.frameInfoVenda.setStyleSheet("\n"
"          QFrame#frameInfoVenda {\n"
"           background-color: #f0f6fc;\n"
"           border: 1px solid #a8c4d8;\n"
"           border-left: 4px solid #3585c8;\n"
"           border-radius: 4px;\n"
"          }\n"
"         ")
        self.frameInfoVenda.setObjectName("frameInfoVenda")
        self.infoVendaHL = QtWidgets.QHBoxLayout(self.frameInfoVenda)
        self.infoVendaHL.setContentsMargins(14, 8, 14, 8)
        self.infoVendaHL.setSpacing(20)
        self.infoVendaHL.setObjectName("infoVendaHL")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblNumVendaLabel = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblNumVendaLabel.setStyleSheet("font-size:10px;color:#5580a0;")
        self.lblNumVendaLabel.setObjectName("lblNumVendaLabel")
        self.vboxlayout.addWidget(self.lblNumVendaLabel)
        self.lblNumVendaValor = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblNumVendaValor.setStyleSheet("font-size:18px;font-weight:bold;color:#1a5fa0;")
        self.lblNumVendaValor.setObjectName("lblNumVendaValor")
        self.vboxlayout.addWidget(self.lblNumVendaValor)
        self.infoVendaHL.addLayout(self.vboxlayout)
        self.frameSep1 = QtWidgets.QFrame(self.frameInfoVenda)
        self.frameSep1.setMinimumWidth(1)
        self.frameSep1.setMaximumWidth(1)
        self.frameSep1.setStyleSheet("background-color:#c0d8ec;")
        self.frameSep1.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSep1.setObjectName("frameSep1")
        self.infoVendaHL.addWidget(self.frameSep1)
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setSpacing(2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.lblClienteLabel = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblClienteLabel.setStyleSheet("font-size:10px;color:#5580a0;")
        self.lblClienteLabel.setObjectName("lblClienteLabel")
        self.vboxlayout1.addWidget(self.lblClienteLabel)
        self.lblClienteValor = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblClienteValor.setStyleSheet("font-size:13px;font-weight:bold;color:#1a3a5c;")
        self.lblClienteValor.setObjectName("lblClienteValor")
        self.vboxlayout1.addWidget(self.lblClienteValor)
        self.infoVendaHL.addLayout(self.vboxlayout1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infoVendaHL.addItem(spacerItem1)
        self.vboxlayout2 = QtWidgets.QVBoxLayout()
        self.vboxlayout2.setSpacing(2)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.lblOperadorLabel = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblOperadorLabel.setStyleSheet("font-size:10px;color:#5580a0;")
        self.lblOperadorLabel.setObjectName("lblOperadorLabel")
        self.vboxlayout2.addWidget(self.lblOperadorLabel)
        self.lblOperadorValor = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblOperadorValor.setStyleSheet("font-size:13px;font-weight:bold;color:#1a3a5c;")
        self.lblOperadorValor.setObjectName("lblOperadorValor")
        self.vboxlayout2.addWidget(self.lblOperadorValor)
        self.infoVendaHL.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtWidgets.QVBoxLayout()
        self.vboxlayout3.setSpacing(2)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.lblDataHoraLabel = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblDataHoraLabel.setStyleSheet("font-size:10px;color:#5580a0;")
        self.lblDataHoraLabel.setObjectName("lblDataHoraLabel")
        self.vboxlayout3.addWidget(self.lblDataHoraLabel)
        self.lblDataHoraValor = QtWidgets.QLabel(self.frameInfoVenda)
        self.lblDataHoraValor.setStyleSheet("font-size:12px;color:#1a3a5c;")
        self.lblDataHoraValor.setObjectName("lblDataHoraValor")
        self.vboxlayout3.addWidget(self.lblDataHoraValor)
        self.infoVendaHL.addLayout(self.vboxlayout3)
        self.conteudoVLayout.addWidget(self.frameInfoVenda)
        self.lblItensHeader = QtWidgets.QLabel(self.frameConteudo)
        self.lblItensHeader.setMinimumHeight(28)
        self.lblItensHeader.setMaximumHeight(28)
        self.lblItensHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblItensHeader.setStyleSheet("\n"
"          QLabel {\n"
"           background-color: #1a5fa0;\n"
"           color: white;\n"
"           font-size: 12px;\n"
"           font-weight: bold;\n"
"           padding: 4px 8px;\n"
"           border-top-left-radius: 4px;\n"
"           border-top-right-radius: 4px;\n"
"          }\n"
"         ")
        self.lblItensHeader.setObjectName("lblItensHeader")
        self.conteudoVLayout.addWidget(self.lblItensHeader)
        self.tableResumoItens = QtWidgets.QTableWidget(self.frameConteudo)
        self.tableResumoItens.setMinimumHeight(200)
        self.tableResumoItens.setStyleSheet("\n"
"          QTableWidget{background-color:#ffffff;alternate-background-color:#f4f9fc;border:1px solid #a8c4d8;border-top:none;border-bottom-left-radius:4px;border-bottom-right-radius:4px;font-size:12px;gridline-color:#dce8f0;outline:0;}\n"
"          QTableWidget::item{padding:4px 8px;color:#111111;}\n"
"          QTableWidget::item:selected{background-color:#3585c8;color:#ffffff;}\n"
"          QHeaderView::section:horizontal{background-color:#f0f6fc;color:#1a3a5c;font-size:11px;font-weight:bold;padding:4px 8px;border:none;border-right:1px solid #dce8f0;border-bottom:2px solid #3585c8;}\n"
"          QHeaderView::section:horizontal:last{border-right:none;}\n"
"          QHeaderView::section:horizontal:checked{background-color:#f0f6fc;color:#1a3a5c;}\n"
"          QHeaderView::section:vertical{background-color:#f0f6fc;color:#f0f6fc;border:none;border-bottom:1px solid #dce8f0;border-right:1px solid #dce8f0;width:14px;}\n"
"          QHeaderView::section:vertical:checked{background-color:#3585c8;color:#3585c8;}\n"
"          QTableCornerButton::section{background-color:#f0f6fc;border:none;border-bottom:2px solid #3585c8;border-right:1px solid #dce8f0;}\n"
"          QScrollBar:vertical{background:#f0f4f8;width:8px;margin:0;}\n"
"          QScrollBar::handle:vertical{background:#a8c4d8;border-radius:3px;min-height:20px;}\n"
"          QScrollBar::handle:vertical:hover{background:#3585c8;}\n"
"          QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{height:0px;}\n"
"         ")
        self.tableResumoItens.setColumnCount(5)
        self.tableResumoItens.setRowCount(0)
        self.tableResumoItens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableResumoItens.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableResumoItens.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResumoItens.setAlternatingRowColors(True)
        self.tableResumoItens.setShowGrid(True)
        self.tableResumoItens.setObjectName("tableResumoItens")
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoItens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoItens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoItens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoItens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoItens.setHorizontalHeaderItem(4, item)
        self.tableResumoItens.horizontalHeader().setVisible(True)
        self.tableResumoItens.horizontalHeader().setDefaultSectionSize(100)
        self.tableResumoItens.horizontalHeader().setHighlightSections(False)
        self.tableResumoItens.horizontalHeader().setStretchLastSection(True)
        self.tableResumoItens.verticalHeader().setVisible(True)
        self.tableResumoItens.verticalHeader().setDefaultSectionSize(24)
        self.tableResumoItens.verticalHeader().setHighlightSections(False)
        self.conteudoVLayout.addWidget(self.tableResumoItens)
        self.frameTotais = QtWidgets.QFrame(self.frameConteudo)
        self.frameTotais.setStyleSheet("\n"
"          QFrame#frameTotais {\n"
"           background-color: #ffffff;\n"
"           border: 1px solid #a8c4d8;\n"
"           border-radius: 6px;\n"
"          }\n"
"         ")
        self.frameTotais.setObjectName("frameTotais")
        self.totaisHL = QtWidgets.QHBoxLayout(self.frameTotais)
        self.totaisHL.setContentsMargins(0, 0, 0, 0)
        self.totaisHL.setSpacing(0)
        self.totaisHL.setObjectName("totaisHL")
        self.frameTotaisEsq = QtWidgets.QFrame(self.frameTotais)
        self.frameTotaisEsq.setStyleSheet("QFrame{background-color:transparent;}")
        self.frameTotaisEsq.setObjectName("frameTotaisEsq")
        self.totaisEsqVL = QtWidgets.QVBoxLayout(self.frameTotaisEsq)
        self.totaisEsqVL.setContentsMargins(16, 10, 16, 10)
        self.totaisEsqVL.setSpacing(0)
        self.totaisEsqVL.setObjectName("totaisEsqVL")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(12)
        self.hboxlayout.setObjectName("hboxlayout")
        self.lblQtdItensLabel = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblQtdItensLabel.setStyleSheet("font-size:12px;color:#5580a0;min-width:110px;")
        self.lblQtdItensLabel.setObjectName("lblQtdItensLabel")
        self.hboxlayout.addWidget(self.lblQtdItensLabel)
        self.lblQtdItensValor = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblQtdItensValor.setStyleSheet("font-size:13px;font-weight:bold;color:#1a3a5c;")
        self.lblQtdItensValor.setObjectName("lblQtdItensValor")
        self.hboxlayout.addWidget(self.lblQtdItensValor)
        self.totaisEsqVL.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setSpacing(12)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.lblSubtotalLabel = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblSubtotalLabel.setStyleSheet("font-size:12px;color:#5580a0;min-width:110px;")
        self.lblSubtotalLabel.setObjectName("lblSubtotalLabel")
        self.hboxlayout1.addWidget(self.lblSubtotalLabel)
        self.lblSubtotalValor = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblSubtotalValor.setStyleSheet("font-size:13px;font-weight:bold;color:#1a3a5c;")
        self.lblSubtotalValor.setObjectName("lblSubtotalValor")
        self.hboxlayout1.addWidget(self.lblSubtotalValor)
        self.totaisEsqVL.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setSpacing(12)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.lblDescontoLabel = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblDescontoLabel.setStyleSheet("font-size:12px;color:#5580a0;min-width:110px;")
        self.lblDescontoLabel.setObjectName("lblDescontoLabel")
        self.hboxlayout2.addWidget(self.lblDescontoLabel)
        self.lblDescontoValor = QtWidgets.QLabel(self.frameTotaisEsq)
        self.lblDescontoValor.setStyleSheet("font-size:13px;font-weight:bold;color:#c07010;")
        self.lblDescontoValor.setObjectName("lblDescontoValor")
        self.hboxlayout2.addWidget(self.lblDescontoValor)
        self.totaisEsqVL.addLayout(self.hboxlayout2)
        self.totaisHL.addWidget(self.frameTotaisEsq)
        self.frameSepTotais = QtWidgets.QFrame(self.frameTotais)
        self.frameSepTotais.setMinimumWidth(1)
        self.frameSepTotais.setMaximumWidth(1)
        self.frameSepTotais.setStyleSheet("background-color:#dce8f0;")
        self.frameSepTotais.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepTotais.setObjectName("frameSepTotais")
        self.totaisHL.addWidget(self.frameSepTotais)
        self.frameTotalDestaque = QtWidgets.QFrame(self.frameTotais)
        self.frameTotalDestaque.setStyleSheet("\n"
"             QFrame#frameTotalDestaque {\n"
"              background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"               stop:0 #1a5fa0, stop:1 #0e3878);\n"
"              border-radius: 5px;\n"
"              margin: 4px;\n"
"             }\n"
"            ")
        self.frameTotalDestaque.setObjectName("frameTotalDestaque")
        self.totalDestaqueVL = QtWidgets.QVBoxLayout(self.frameTotalDestaque)
        self.totalDestaqueVL.setContentsMargins(20, 10, 20, 10)
        self.totalDestaqueVL.setSpacing(2)
        self.totalDestaqueVL.setObjectName("totalDestaqueVL")
        self.lblTotalLabel = QtWidgets.QLabel(self.frameTotalDestaque)
        self.lblTotalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalLabel.setStyleSheet("font-size:10px;font-weight:bold;color:#a0c8e8;letter-spacing:1px;")
        self.lblTotalLabel.setObjectName("lblTotalLabel")
        self.totalDestaqueVL.addWidget(self.lblTotalLabel)
        self.lblTotalValor = QtWidgets.QLabel(self.frameTotalDestaque)
        self.lblTotalValor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotalValor.setStyleSheet("font-size:28px;font-weight:bold;color:white;")
        self.lblTotalValor.setObjectName("lblTotalValor")
        self.totalDestaqueVL.addWidget(self.lblTotalValor)
        self.totaisHL.addWidget(self.frameTotalDestaque)
        self.conteudoVLayout.addWidget(self.frameTotais)
        self.lblAvisoVazio = QtWidgets.QLabel(self.frameConteudo)
        self.lblAvisoVazio.setVisible(False)
        self.lblAvisoVazio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAvisoVazio.setStyleSheet("\n"
"          QLabel {\n"
"           background-color: #fff8e8;\n"
"           border: 1px solid #e0b020;\n"
"           border-radius: 4px;\n"
"           font-size: 12px;\n"
"           font-weight: bold;\n"
"           color: #806000;\n"
"           padding: 6px 12px;\n"
"          }\n"
"         ")
        self.lblAvisoVazio.setObjectName("lblAvisoVazio")
        self.conteudoVLayout.addWidget(self.lblAvisoVazio)
        self.botoesHL = QtWidgets.QHBoxLayout()
        self.botoesHL.setSpacing(10)
        self.botoesHL.setObjectName("botoesHL")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesHL.addItem(spacerItem2)
        self.btnVoltarCorrigir = QtWidgets.QPushButton(self.frameConteudo)
        self.btnVoltarCorrigir.setMinimumSize(QtCore.QSize(150, 42))
        self.btnVoltarCorrigir.setStyleSheet("\n"
"            QPushButton{background-color:#f0f0f0;color:#333333;font-size:12px;font-weight:bold;border:1px solid #bbbbbb;border-radius:5px;padding:5px 14px;}\n"
"            QPushButton:hover{background-color:#e0e0e0;}\n"
"            QPushButton:pressed{background-color:#cccccc;}\n"
"           ")
        self.btnVoltarCorrigir.setObjectName("btnVoltarCorrigir")
        self.botoesHL.addWidget(self.btnVoltarCorrigir)
        self.btnConfirmarPagamento = QtWidgets.QPushButton(self.frameConteudo)
        self.btnConfirmarPagamento.setDefault(True)
        self.btnConfirmarPagamento.setMinimumSize(QtCore.QSize(200, 42))
        self.btnConfirmarPagamento.setStyleSheet("\n"
"            QPushButton{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #3a9a3a,stop:1 #1a7a1a);color:white;font-size:13px;font-weight:bold;border:none;border-radius:5px;padding:5px 16px;}\n"
"            QPushButton:hover{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #48aa48,stop:1 #288828);}\n"
"            QPushButton:pressed{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #1a7a1a,stop:1 #0e5a0e);}\n"
"            QPushButton:disabled{background:#9dbfda;color:#c0d8ec;}\n"
"           ")
        self.btnConfirmarPagamento.setObjectName("btnConfirmarPagamento")
        self.botoesHL.addWidget(self.btnConfirmarPagamento)
        self.conteudoVLayout.addLayout(self.botoesHL)
        self.mainVLayout.addWidget(self.frameConteudo)

        self.retranslateUi(ModalConfirmacaoVenda)
        self.btnFechar.clicked.connect(ModalConfirmacaoVenda.reject) # type: ignore
        self.btnVoltarCorrigir.clicked.connect(ModalConfirmacaoVenda.reject) # type: ignore
        self.btnConfirmarPagamento.clicked.connect(ModalConfirmacaoVenda.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModalConfirmacaoVenda)

    def retranslateUi(self, ModalConfirmacaoVenda):
        _translate = QtCore.QCoreApplication.translate
        ModalConfirmacaoVenda.setWindowTitle(_translate("ModalConfirmacaoVenda", "CSPdv - Confirmar Venda"))
        self.lblTitleIcon.setText(_translate("ModalConfirmacaoVenda", "💰"))
        self.lblTitulo.setText(_translate("ModalConfirmacaoVenda", "Confirmar Venda  —  F4"))
        self.btnFechar.setText(_translate("ModalConfirmacaoVenda", "✕"))
        self.btnFechar.setShortcut(_translate("ModalConfirmacaoVenda", "Escape"))
        self.lblNumVendaLabel.setText(_translate("ModalConfirmacaoVenda", "Venda nº"))
        self.lblNumVendaValor.setText(_translate("ModalConfirmacaoVenda", "---"))
        self.lblClienteLabel.setText(_translate("ModalConfirmacaoVenda", "Cliente"))
        self.lblClienteValor.setText(_translate("ModalConfirmacaoVenda", "Consumidor Final"))
        self.lblOperadorLabel.setText(_translate("ModalConfirmacaoVenda", "Operador"))
        self.lblOperadorValor.setText(_translate("ModalConfirmacaoVenda", "ADMIN"))
        self.lblDataHoraLabel.setText(_translate("ModalConfirmacaoVenda", "Data / Hora"))
        self.lblDataHoraValor.setText(_translate("ModalConfirmacaoVenda", "--/--/---- --:--"))
        self.lblItensHeader.setText(_translate("ModalConfirmacaoVenda", "Itens da Venda"))
        self.tableResumoItens.setSortingEnabled(False)
        item = self.tableResumoItens.horizontalHeaderItem(0)
        item.setText(_translate("ModalConfirmacaoVenda", "Código"))
        item = self.tableResumoItens.horizontalHeaderItem(1)
        item.setText(_translate("ModalConfirmacaoVenda", "Descrição"))
        item = self.tableResumoItens.horizontalHeaderItem(2)
        item.setText(_translate("ModalConfirmacaoVenda", "Qtd."))
        item = self.tableResumoItens.horizontalHeaderItem(3)
        item.setText(_translate("ModalConfirmacaoVenda", "Vl. Unit."))
        item = self.tableResumoItens.horizontalHeaderItem(4)
        item.setText(_translate("ModalConfirmacaoVenda", "Subtotal"))
        self.lblQtdItensLabel.setText(_translate("ModalConfirmacaoVenda", "Qtd. de itens:"))
        self.lblQtdItensValor.setText(_translate("ModalConfirmacaoVenda", "0"))
        self.lblSubtotalLabel.setText(_translate("ModalConfirmacaoVenda", "Subtotal:"))
        self.lblSubtotalValor.setText(_translate("ModalConfirmacaoVenda", "R$ 0,00"))
        self.lblDescontoLabel.setText(_translate("ModalConfirmacaoVenda", "Desconto:"))
        self.lblDescontoValor.setText(_translate("ModalConfirmacaoVenda", "R$ 0,00"))
        self.lblTotalLabel.setText(_translate("ModalConfirmacaoVenda", "TOTAL A PAGAR"))
        self.lblTotalValor.setText(_translate("ModalConfirmacaoVenda", "R$ 0,00"))
        self.lblAvisoVazio.setText(_translate("ModalConfirmacaoVenda", "⚠  Nenhum item adicionado. Adicione produtos antes de confirmar."))
        self.btnVoltarCorrigir.setText(_translate("ModalConfirmacaoVenda", "◀  Voltar e Corrigir"))
        self.btnVoltarCorrigir.setShortcut(_translate("ModalConfirmacaoVenda", "Escape"))
        self.btnConfirmarPagamento.setText(_translate("ModalConfirmacaoVenda", "💰  Confirmar e Pagar  (Enter)"))
        self.btnConfirmarPagamento.setShortcut(_translate("ModalConfirmacaoVenda", "Return"))
