# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\cspdv\ui\venda\tela_cupom_nao_fiscal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CupomNaoFiscal(object):
    def setupUi(self, CupomNaoFiscal):
        CupomNaoFiscal.setObjectName("CupomNaoFiscal")
        CupomNaoFiscal.resize(340, 500)
        CupomNaoFiscal.setModal(True)
        CupomNaoFiscal.setStyleSheet("QDialog { background-color: #e8f2fa; font-family: Arial; }")
        self.mainVLayout = QtWidgets.QVBoxLayout(CupomNaoFiscal)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameTitleBar = QtWidgets.QFrame(CupomNaoFiscal)
        self.frameTitleBar.setMinimumHeight(32)
        self.frameTitleBar.setMaximumHeight(32)
        self.frameTitleBar.setStyleSheet("\n"
"       QFrame#frameTitleBar {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"         stop:0 #3d90d8, stop:1 #1a5fa0);\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"       }\n"
"      ")
        self.frameTitleBar.setObjectName("frameTitleBar")
        self.titleHLayout = QtWidgets.QHBoxLayout(self.frameTitleBar)
        self.titleHLayout.setContentsMargins(8, 0, 6, 0)
        self.titleHLayout.setSpacing(6)
        self.titleHLayout.setObjectName("titleHLayout")
        self.lblTitleIcon = QtWidgets.QLabel(self.frameTitleBar)
        self.lblTitleIcon.setMaximumWidth(22)
        self.lblTitleIcon.setStyleSheet("color: #a0d0f0; font-size: 13px;")
        self.lblTitleIcon.setObjectName("lblTitleIcon")
        self.titleHLayout.addWidget(self.lblTitleIcon)
        self.lblTitulo = QtWidgets.QLabel(self.frameTitleBar)
        self.lblTitulo.setStyleSheet("color: white; font-size: 13px; font-weight: bold;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.titleHLayout.addWidget(self.lblTitulo)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleHLayout.addItem(spacerItem)
        self.btnMinimizar = QtWidgets.QPushButton(self.frameTitleBar)
        self.btnMinimizar.setMinimumSize(QtCore.QSize(22, 22))
        self.btnMinimizar.setMaximumSize(QtCore.QSize(22, 22))
        self.btnMinimizar.setStyleSheet("\n"
"          QPushButton {\n"
"           background-color: #2a70b8;\n"
"           border: none;\n"
"           border-radius: 3px;\n"
"           color: white;\n"
"           font-size: 11px;\n"
"           font-weight: bold;\n"
"          }\n"
"          QPushButton:hover  { background-color: #3a85cc; }\n"
"          QPushButton:pressed{ background-color: #1a5fa0; }\n"
"         ")
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.titleHLayout.addWidget(self.btnMinimizar)
        self.btnMaximizar = QtWidgets.QPushButton(self.frameTitleBar)
        self.btnMaximizar.setMinimumSize(QtCore.QSize(22, 22))
        self.btnMaximizar.setMaximumSize(QtCore.QSize(22, 22))
        self.btnMaximizar.setStyleSheet("\n"
"          QPushButton {\n"
"           background-color: #2a70b8;\n"
"           border: none;\n"
"           border-radius: 3px;\n"
"           color: white;\n"
"           font-size: 11px;\n"
"          }\n"
"          QPushButton:hover  { background-color: #3a85cc; }\n"
"          QPushButton:pressed{ background-color: #1a5fa0; }\n"
"         ")
        self.btnMaximizar.setObjectName("btnMaximizar")
        self.titleHLayout.addWidget(self.btnMaximizar)
        self.btnFechar = QtWidgets.QPushButton(self.frameTitleBar)
        self.btnFechar.setMinimumSize(QtCore.QSize(22, 22))
        self.btnFechar.setMaximumSize(QtCore.QSize(22, 22))
        self.btnFechar.setStyleSheet("\n"
"          QPushButton {\n"
"           background-color: #cc2222;\n"
"           border: none;\n"
"           border-radius: 3px;\n"
"           color: white;\n"
"           font-size: 11px;\n"
"           font-weight: bold;\n"
"          }\n"
"          QPushButton:hover  { background-color: #e03030; }\n"
"          QPushButton:pressed{ background-color: #aa1010; }\n"
"         ")
        self.btnFechar.setObjectName("btnFechar")
        self.titleHLayout.addWidget(self.btnFechar)
        self.mainVLayout.addWidget(self.frameTitleBar)
        self.frameConteudo = QtWidgets.QFrame(CupomNaoFiscal)
        self.frameConteudo.setStyleSheet("\n"
"       QFrame#frameConteudo {\n"
"        background-color: #f8f8f8;\n"
"        border: 2px solid #2a70b8;\n"
"        border-top: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"       }\n"
"      ")
        self.frameConteudo.setObjectName("frameConteudo")
        self.conteudoVLayout = QtWidgets.QVBoxLayout(self.frameConteudo)
        self.conteudoVLayout.setContentsMargins(8, 8, 8, 10)
        self.conteudoVLayout.setSpacing(8)
        self.conteudoVLayout.setObjectName("conteudoVLayout")
        self.textCupom = QtWidgets.QPlainTextEdit(self.frameConteudo)
        self.textCupom.setStyleSheet("\n"
"          QPlainTextEdit {\n"
"           background-color: #ffffff;\n"
"           border: 1px solid #c0c0c0;\n"
"           border-radius: 2px;\n"
"           font-family: \"Courier New\", Courier, monospace;\n"
"           font-size: 11px;\n"
"           color: #111111;\n"
"           padding: 6px;\n"
"           selection-background-color: #3585c8;\n"
"           selection-color: #ffffff;\n"
"          }\n"
"          QScrollBar:vertical {\n"
"           background: #f0f4f8;\n"
"           width: 10px;\n"
"           margin: 0;\n"
"          }\n"
"          QScrollBar::handle:vertical {\n"
"           background: #a8c4d8;\n"
"           border-radius: 4px;\n"
"           min-height: 20px;\n"
"          }\n"
"          QScrollBar::handle:vertical:hover { background: #3585c8; }\n"
"          QScrollBar::add-line:vertical,\n"
"          QScrollBar::sub-line:vertical { height: 0px; }\n"
"         ")
        self.textCupom.setReadOnly(True)
        self.textCupom.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textCupom.setObjectName("textCupom")
        self.conteudoVLayout.addWidget(self.textCupom)
        self.botoesHLayout = QtWidgets.QHBoxLayout()
        self.botoesHLayout.setSpacing(10)
        self.botoesHLayout.setObjectName("botoesHLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesHLayout.addItem(spacerItem1)
        self.btnImprimir = QtWidgets.QPushButton(self.frameConteudo)
        self.btnImprimir.setMinimumSize(QtCore.QSize(120, 36))
        self.btnImprimir.setStyleSheet("\n"
"            QPushButton {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #f0f4f8, stop:1 #d8e8f4);\n"
"             border: 1px solid #9ab8d0;\n"
"             border-radius: 4px;\n"
"             font-size: 12px;\n"
"             font-weight: bold;\n"
"             color: #1a3a5c;\n"
"             padding: 4px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #e0ecf8, stop:1 #c0d8f0);\n"
"             border-color: #6a9ab8;\n"
"            }\n"
"            QPushButton:pressed {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #c0d8f0, stop:1 #a0c4e4);\n"
"            }\n"
"           ")
        self.btnImprimir.setObjectName("btnImprimir")
        self.botoesHLayout.addWidget(self.btnImprimir)
        self.btnFinalizarSemImpressao = QtWidgets.QPushButton(self.frameConteudo)
        self.btnFinalizarSemImpressao.setMinimumSize(QtCore.QSize(210, 36))
        self.btnFinalizarSemImpressao.setStyleSheet("\n"
"            QPushButton {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #eef8ee, stop:1 #d6efd6);\n"
"             border: 1px solid #79ad79;\n"
"             border-radius: 4px;\n"
"             font-size: 12px;\n"
"             font-weight: bold;\n"
"             color: #245224;\n"
"             padding: 4px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #e0f4e0, stop:1 #c0e6c0);\n"
"             border-color: #4c914c;\n"
"            }\n"
"            QPushButton:pressed {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #c8e6c8, stop:1 #a8d6a8);\n"
"            }\n"
"           ")
        self.btnFinalizarSemImpressao.setObjectName("btnFinalizarSemImpressao")
        self.botoesHLayout.addWidget(self.btnFinalizarSemImpressao)
        self.btnSair = QtWidgets.QPushButton(self.frameConteudo)
        self.btnSair.setMinimumSize(QtCore.QSize(100, 36))
        self.btnSair.setStyleSheet("\n"
"            QPushButton {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #fce8e8, stop:1 #f0cccc);\n"
"             border: 1px solid #cc7070;\n"
"             border-radius: 4px;\n"
"             font-size: 12px;\n"
"             font-weight: bold;\n"
"             color: #6a1a1a;\n"
"             padding: 4px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #f8d8d8, stop:1 #e8b8b8);\n"
"             border-color: #aa4444;\n"
"            }\n"
"            QPushButton:pressed {\n"
"             background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"              stop:0 #e8b8b8, stop:1 #d09898);\n"
"            }\n"
"           ")
        self.btnSair.setObjectName("btnSair")
        self.botoesHLayout.addWidget(self.btnSair)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesHLayout.addItem(spacerItem2)
        self.conteudoVLayout.addLayout(self.botoesHLayout)
        self.mainVLayout.addWidget(self.frameConteudo)

        self.retranslateUi(CupomNaoFiscal)
        self.btnSair.clicked.connect(CupomNaoFiscal.reject) # type: ignore
        self.btnFechar.clicked.connect(CupomNaoFiscal.reject) # type: ignore
        self.btnImprimir.clicked.connect(CupomNaoFiscal.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CupomNaoFiscal)

    def retranslateUi(self, CupomNaoFiscal):
        _translate = QtCore.QCoreApplication.translate
        CupomNaoFiscal.setWindowTitle(_translate("CupomNaoFiscal", "Cupom Não Fiscal"))
        self.lblTitleIcon.setText(_translate("CupomNaoFiscal", "🖨"))
        self.lblTitulo.setText(_translate("CupomNaoFiscal", "Cupom Não Fiscal"))
        self.btnMinimizar.setText(_translate("CupomNaoFiscal", "─"))
        self.btnMaximizar.setText(_translate("CupomNaoFiscal", "□"))
        self.btnFechar.setText(_translate("CupomNaoFiscal", "✕"))
        self.btnFechar.setShortcut(_translate("CupomNaoFiscal", "Escape"))
        self.textCupom.setPlainText(_translate("CupomNaoFiscal", "*****DOCUMENTO NÃO FISCAL *****\n"
"         VIDA NATURAL\n"
"    CONFERENCIA DE PRODUTOS\n"
"N. da venda: 0\n"
"Atendente: ADMIN\n"
"Data/Hora: --/--/---- --:--\n"
"--------------------------------\n"
"ITEM DESCRICAO\n"
"COD.   QUANT.  V. UNIT.  V. TOTAL\n"
"--------------------------------\n"
"\n"
"--------------------------------\n"
"VALOR TOTAL                  0,00\n"
"\n"
"TOTAL PAGO                   0,00\n"
"TROCO                        0,00\n"
"--------------------------------\n"
"      FORMAS DE PAGAMENTO\n"
"--------------------------------\n"
"\n"
"--------------------------------\n"
"    CONFERENCIA DE PRODUTOS"))
        self.btnImprimir.setText(_translate("CupomNaoFiscal", "   Imprimir"))
        self.btnImprimir.setShortcut(_translate("CupomNaoFiscal", "Return"))
        self.btnFinalizarSemImpressao.setText(_translate("CupomNaoFiscal", "Finalizar sem impressão"))
        self.btnSair.setText(_translate("CupomNaoFiscal", "   Sair"))
        self.btnSair.setShortcut(_translate("CupomNaoFiscal", "Escape"))
