# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel_relatorios.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PainelRelatorios(object):
    def setupUi(self, PainelRelatorios):
        PainelRelatorios.setObjectName("PainelRelatorios")
        PainelRelatorios.resize(1366, 768)
        self.centralWidget = QtWidgets.QWidget(PainelRelatorios)
        self.centralWidget.setObjectName("centralWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(self.centralWidget)
        self.frameHeader.setStyleSheet("\n"
"QFrame#frameHeader { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }\n"
"QLabel#lblLogo { color: white; font-size: 28px; font-weight: bold; }\n"
"QLabel#lblModulo {\n"
" color: #ffe39a; font-size: 12px; font-weight: bold;\n"
" background-color: rgba(255,255,255,30);\n"
" border: 1px solid rgba(255,255,255,60);\n"
" border-radius: 4px; padding: 3px 10px;\n"
"}\n"
"QLabel#lblOperadorInfo, QLabel#lblPeriodoAtual { color: #d9ebfb; font-size: 11px; }\n"
"QPushButton#btnVoltarSelecao {\n"
" background-color: #cc2222; color: white; border: none; border-radius: 4px;\n"
" padding: 6px 12px; font-size: 11px; font-weight: bold;\n"
"}\n"
"QPushButton#btnVoltarSelecao:hover { background-color: #e03030; }\n"
"       ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerLayout.setContentsMargins(14, 8, 14, 8)
        self.headerLayout.setObjectName("headerLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setObjectName("lblLogo")
        self.headerLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerLayout.addWidget(self.frameSepHeader)
        self.lblModulo = QtWidgets.QLabel(self.frameHeader)
        self.lblModulo.setObjectName("lblModulo")
        self.headerLayout.addWidget(self.lblModulo)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.lblOperadorInfo = QtWidgets.QLabel(self.frameHeader)
        self.lblOperadorInfo.setObjectName("lblOperadorInfo")
        self.headerLayout.addWidget(self.lblOperadorInfo)
        self.lblPeriodoAtual = QtWidgets.QLabel(self.frameHeader)
        self.lblPeriodoAtual.setObjectName("lblPeriodoAtual")
        self.headerLayout.addWidget(self.lblPeriodoAtual)
        self.btnVoltarSelecao = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltarSelecao.setObjectName("btnVoltarSelecao")
        self.headerLayout.addWidget(self.btnVoltarSelecao)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameToolbar = QtWidgets.QFrame(self.centralWidget)
        self.frameToolbar.setMinimumSize(QtCore.QSize(0, 56))
        self.frameToolbar.setStyleSheet("\n"
"QFrame#frameToolbar { background-color: #f0f6fc; border-bottom: 1px solid #c8d8e8; }\n"
"QComboBox, QDateEdit {\n"
" background-color: white; border: 1px solid #b8cde0; border-radius: 4px;\n"
" padding: 6px 8px; font-size: 12px;\n"
"}\n"
"QPushButton {\n"
" background-color: #3585c8; color: white; border: none; border-radius: 4px;\n"
" padding: 6px 12px; font-size: 12px; font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #2b74b4; }\n"
"QPushButton#btnExportarCsv { background-color: #5cb85c; }\n"
"QPushButton#btnExportarCsv:hover { background-color: #4aa14a; }\n"
"       ")
        self.frameToolbar.setObjectName("frameToolbar")
        self.toolbarLayout = QtWidgets.QHBoxLayout(self.frameToolbar)
        self.toolbarLayout.setContentsMargins(16, 10, 16, 10)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.cmbTipoRelatorio = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbTipoRelatorio.setObjectName("cmbTipoRelatorio")
        self.cmbTipoRelatorio.addItem("")
        self.cmbTipoRelatorio.addItem("")
        self.cmbTipoRelatorio.addItem("")
        self.cmbTipoRelatorio.addItem("")
        self.toolbarLayout.addWidget(self.cmbTipoRelatorio)
        self.dateInicial = QtWidgets.QDateEdit(self.frameToolbar)
        self.dateInicial.setCalendarPopup(True)
        self.dateInicial.setObjectName("dateInicial")
        self.toolbarLayout.addWidget(self.dateInicial)
        self.dateFinal = QtWidgets.QDateEdit(self.frameToolbar)
        self.dateFinal.setCalendarPopup(True)
        self.dateFinal.setObjectName("dateFinal")
        self.toolbarLayout.addWidget(self.dateFinal)
        self.cmbAgrupamento = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbAgrupamento.setObjectName("cmbAgrupamento")
        self.cmbAgrupamento.addItem("")
        self.cmbAgrupamento.addItem("")
        self.cmbAgrupamento.addItem("")
        self.toolbarLayout.addWidget(self.cmbAgrupamento)
        self.btnGerarRelatorio = QtWidgets.QPushButton(self.frameToolbar)
        self.btnGerarRelatorio.setObjectName("btnGerarRelatorio")
        self.toolbarLayout.addWidget(self.btnGerarRelatorio)
        self.btnExportarCsv = QtWidgets.QPushButton(self.frameToolbar)
        self.btnExportarCsv.setObjectName("btnExportarCsv")
        self.toolbarLayout.addWidget(self.btnExportarCsv)
        self.mainVLayout.addWidget(self.frameToolbar)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setContentsMargins(16, 14, 16, 14)
        self.contentLayout.setSpacing(12)
        self.contentLayout.setObjectName("contentLayout")
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(12)
        self.cardsLayout.setObjectName("cardsLayout")
        self.cardTotalVendas = QtWidgets.QFrame(self.centralWidget)
        self.cardTotalVendas.setStyleSheet("QFrame#cardTotalVendas { background-color: #3585c8; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #d8ebfb; font-size: 12px; }")
        self.cardTotalVendas.setObjectName("cardTotalVendas")
        self.cardTotalVendasLayout = QtWidgets.QVBoxLayout(self.cardTotalVendas)
        self.cardTotalVendasLayout.setContentsMargins(16, 14, 16, 14)
        self.cardTotalVendasLayout.setObjectName("cardTotalVendasLayout")
        self.lblTotalVendasValor = QtWidgets.QLabel(self.cardTotalVendas)
        self.lblTotalVendasValor.setObjectName("lblTotalVendasValor")
        self.cardTotalVendasLayout.addWidget(self.lblTotalVendasValor)
        self.lblTotalVendasTitulo = QtWidgets.QLabel(self.cardTotalVendas)
        self.lblTotalVendasTitulo.setObjectName("lblTotalVendasTitulo")
        self.cardTotalVendasLayout.addWidget(self.lblTotalVendasTitulo)
        self.cardsLayout.addWidget(self.cardTotalVendas)
        self.cardFaturamentoPeriodo = QtWidgets.QFrame(self.centralWidget)
        self.cardFaturamentoPeriodo.setStyleSheet("QFrame#cardFaturamentoPeriodo { background-color: #5cb85c; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #daf0da; font-size: 12px; }")
        self.cardFaturamentoPeriodo.setObjectName("cardFaturamentoPeriodo")
        self.cardFaturamentoPeriodoLayout = QtWidgets.QVBoxLayout(self.cardFaturamentoPeriodo)
        self.cardFaturamentoPeriodoLayout.setContentsMargins(16, 14, 16, 14)
        self.cardFaturamentoPeriodoLayout.setObjectName("cardFaturamentoPeriodoLayout")
        self.lblFaturamentoPeriodoValor = QtWidgets.QLabel(self.cardFaturamentoPeriodo)
        self.lblFaturamentoPeriodoValor.setObjectName("lblFaturamentoPeriodoValor")
        self.cardFaturamentoPeriodoLayout.addWidget(self.lblFaturamentoPeriodoValor)
        self.lblFaturamentoPeriodoTitulo = QtWidgets.QLabel(self.cardFaturamentoPeriodo)
        self.lblFaturamentoPeriodoTitulo.setObjectName("lblFaturamentoPeriodoTitulo")
        self.cardFaturamentoPeriodoLayout.addWidget(self.lblFaturamentoPeriodoTitulo)
        self.cardsLayout.addWidget(self.cardFaturamentoPeriodo)
        self.cardTicketMedio = QtWidgets.QFrame(self.centralWidget)
        self.cardTicketMedio.setStyleSheet("QFrame#cardTicketMedio { background-color: #9b59b6; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #ebd7f5; font-size: 12px; }")
        self.cardTicketMedio.setObjectName("cardTicketMedio")
        self.cardTicketMedioLayout = QtWidgets.QVBoxLayout(self.cardTicketMedio)
        self.cardTicketMedioLayout.setContentsMargins(16, 14, 16, 14)
        self.cardTicketMedioLayout.setObjectName("cardTicketMedioLayout")
        self.lblTicketMedioValor = QtWidgets.QLabel(self.cardTicketMedio)
        self.lblTicketMedioValor.setObjectName("lblTicketMedioValor")
        self.cardTicketMedioLayout.addWidget(self.lblTicketMedioValor)
        self.lblTicketMedioTitulo = QtWidgets.QLabel(self.cardTicketMedio)
        self.lblTicketMedioTitulo.setObjectName("lblTicketMedioTitulo")
        self.cardTicketMedioLayout.addWidget(self.lblTicketMedioTitulo)
        self.cardsLayout.addWidget(self.cardTicketMedio)
        self.cardClientesAtendidos = QtWidgets.QFrame(self.centralWidget)
        self.cardClientesAtendidos.setStyleSheet("QFrame#cardClientesAtendidos { background-color: #f0a030; border-radius: 8px; } QLabel { color: #13202c; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #523b10; font-size: 12px; }")
        self.cardClientesAtendidos.setObjectName("cardClientesAtendidos")
        self.cardClientesAtendidosLayout = QtWidgets.QVBoxLayout(self.cardClientesAtendidos)
        self.cardClientesAtendidosLayout.setContentsMargins(16, 14, 16, 14)
        self.cardClientesAtendidosLayout.setObjectName("cardClientesAtendidosLayout")
        self.lblClientesAtendidosValor = QtWidgets.QLabel(self.cardClientesAtendidos)
        self.lblClientesAtendidosValor.setObjectName("lblClientesAtendidosValor")
        self.cardClientesAtendidosLayout.addWidget(self.lblClientesAtendidosValor)
        self.lblClientesAtendidosTitulo = QtWidgets.QLabel(self.cardClientesAtendidos)
        self.lblClientesAtendidosTitulo.setObjectName("lblClientesAtendidosTitulo")
        self.cardClientesAtendidosLayout.addWidget(self.lblClientesAtendidosTitulo)
        self.cardsLayout.addWidget(self.cardClientesAtendidos)
        self.contentLayout.addLayout(self.cardsLayout)
        self.reportsLayout = QtWidgets.QHBoxLayout()
        self.reportsLayout.setSpacing(12)
        self.reportsLayout.setObjectName("reportsLayout")
        self.frameIndicadores = QtWidgets.QFrame(self.centralWidget)
        self.frameIndicadores.setStyleSheet("\n"
"QFrame#frameIndicadores, QFrame#frameRankings {\n"
" background-color: white;\n"
" border: 1px solid #b8cde0;\n"
" border-radius: 6px;\n"
"}\n"
"QLabel[sectionTitle=\"true\"] {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 13px;\n"
" font-weight: bold;\n"
" padding: 8px 12px;\n"
" border-bottom: 1px solid #d8e3ee;\n"
"}\n"
"QTableWidget {\n"
" border: none;\n"
" background-color: white;\n"
" gridline-color: #dce8f0;\n"
" font-size: 12px;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-right: 1px solid #dce8f0;\n"
" border-bottom: 2px solid #3585c8;\n"
" padding: 5px 6px;\n"
"}\n"
"           ")
        self.frameIndicadores.setObjectName("frameIndicadores")
        self.frameIndicadoresLayout = QtWidgets.QVBoxLayout(self.frameIndicadores)
        self.frameIndicadoresLayout.setContentsMargins(0, 0, 0, 0)
        self.frameIndicadoresLayout.setSpacing(0)
        self.frameIndicadoresLayout.setObjectName("frameIndicadoresLayout")
        self.lblIndicadoresSection = QtWidgets.QLabel(self.frameIndicadores)
        self.lblIndicadoresSection.setObjectName("lblIndicadoresSection")
        self.frameIndicadoresLayout.addWidget(self.lblIndicadoresSection)
        self.tableResumoPeriodo = QtWidgets.QTableWidget(self.frameIndicadores)
        self.tableResumoPeriodo.setRowCount(0)
        self.tableResumoPeriodo.setColumnCount(5)
        self.tableResumoPeriodo.setObjectName("tableResumoPeriodo")
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoPeriodo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoPeriodo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoPeriodo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoPeriodo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResumoPeriodo.setHorizontalHeaderItem(4, item)
        self.tableResumoPeriodo.horizontalHeader().setStretchLastSection(True)
        self.frameIndicadoresLayout.addWidget(self.tableResumoPeriodo)
        self.reportsLayout.addWidget(self.frameIndicadores)
        self.frameRankings = QtWidgets.QFrame(self.centralWidget)
        self.frameRankings.setMinimumSize(QtCore.QSize(440, 0))
        self.frameRankings.setObjectName("frameRankings")
        self.frameRankingsLayout = QtWidgets.QVBoxLayout(self.frameRankings)
        self.frameRankingsLayout.setContentsMargins(0, 0, 0, 0)
        self.frameRankingsLayout.setSpacing(0)
        self.frameRankingsLayout.setObjectName("frameRankingsLayout")
        self.lblProdutosRankingSection = QtWidgets.QLabel(self.frameRankings)
        self.lblProdutosRankingSection.setObjectName("lblProdutosRankingSection")
        self.frameRankingsLayout.addWidget(self.lblProdutosRankingSection)
        self.tableProdutosMaisVendidos = QtWidgets.QTableWidget(self.frameRankings)
        self.tableProdutosMaisVendidos.setRowCount(0)
        self.tableProdutosMaisVendidos.setColumnCount(4)
        self.tableProdutosMaisVendidos.setObjectName("tableProdutosMaisVendidos")
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosMaisVendidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosMaisVendidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosMaisVendidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosMaisVendidos.setHorizontalHeaderItem(3, item)
        self.tableProdutosMaisVendidos.horizontalHeader().setStretchLastSection(True)
        self.frameRankingsLayout.addWidget(self.tableProdutosMaisVendidos)
        self.lblClientesRankingSection = QtWidgets.QLabel(self.frameRankings)
        self.lblClientesRankingSection.setObjectName("lblClientesRankingSection")
        self.frameRankingsLayout.addWidget(self.lblClientesRankingSection)
        self.tableClientesDestaque = QtWidgets.QTableWidget(self.frameRankings)
        self.tableClientesDestaque.setRowCount(0)
        self.tableClientesDestaque.setColumnCount(3)
        self.tableClientesDestaque.setObjectName("tableClientesDestaque")
        item = QtWidgets.QTableWidgetItem()
        self.tableClientesDestaque.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientesDestaque.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClientesDestaque.setHorizontalHeaderItem(2, item)
        self.tableClientesDestaque.horizontalHeader().setStretchLastSection(True)
        self.frameRankingsLayout.addWidget(self.tableClientesDestaque)
        self.reportsLayout.addWidget(self.frameRankings)
        self.contentLayout.addLayout(self.reportsLayout)
        self.mainVLayout.addLayout(self.contentLayout)
        self.frameStatusBar = QtWidgets.QFrame(self.centralWidget)
        self.frameStatusBar.setStyleSheet("\n"
"QFrame#frameStatusBar { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }\n"
"QLabel { color: white; font-size: 11px; }\n"
"QLabel#lblStatusSistema { color: #80ff80; font-weight: bold; }\n"
"       ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusLayout.setContentsMargins(12, -1, 12, -1)
        self.statusLayout.setObjectName("statusLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusLayout.addWidget(self.lblStatusSistema)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem1)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusLayout.addWidget(self.lblStatusBar)
        self.mainVLayout.addWidget(self.frameStatusBar)
        PainelRelatorios.setCentralWidget(self.centralWidget)

        self.retranslateUi(PainelRelatorios)
        QtCore.QMetaObject.connectSlotsByName(PainelRelatorios)

    def retranslateUi(self, PainelRelatorios):
        _translate = QtCore.QCoreApplication.translate
        PainelRelatorios.setWindowTitle(_translate("PainelRelatorios", "CSPdv - Relatorios"))
        self.lblLogo.setText(_translate("PainelRelatorios", "CSPdv"))
        self.lblModulo.setText(_translate("PainelRelatorios", "RELATORIOS E INDICADORES"))
        self.lblOperadorInfo.setText(_translate("PainelRelatorios", "Operador: ---"))
        self.lblPeriodoAtual.setText(_translate("PainelRelatorios", "Periodo: Hoje"))
        self.btnVoltarSelecao.setText(_translate("PainelRelatorios", "Voltar"))
        self.cmbTipoRelatorio.setItemText(0, _translate("PainelRelatorios", "Visao Geral de Vendas"))
        self.cmbTipoRelatorio.setItemText(1, _translate("PainelRelatorios", "Produtos Mais Vendidos"))
        self.cmbTipoRelatorio.setItemText(2, _translate("PainelRelatorios", "Clientes e Ticket Medio"))
        self.cmbTipoRelatorio.setItemText(3, _translate("PainelRelatorios", "Caixa por Periodo"))
        self.cmbAgrupamento.setItemText(0, _translate("PainelRelatorios", "Agrupar por dia"))
        self.cmbAgrupamento.setItemText(1, _translate("PainelRelatorios", "Agrupar por semana"))
        self.cmbAgrupamento.setItemText(2, _translate("PainelRelatorios", "Agrupar por mes"))
        self.btnGerarRelatorio.setText(_translate("PainelRelatorios", "Gerar Relatorio"))
        self.btnExportarCsv.setText(_translate("PainelRelatorios", "Exportar CSV"))
        self.lblTotalVendasValor.setProperty("role", _translate("PainelRelatorios", "value"))
        self.lblTotalVendasValor.setText(_translate("PainelRelatorios", "0"))
        self.lblTotalVendasTitulo.setProperty("role", _translate("PainelRelatorios", "title"))
        self.lblTotalVendasTitulo.setText(_translate("PainelRelatorios", "Quantidade de Vendas"))
        self.lblFaturamentoPeriodoValor.setProperty("role", _translate("PainelRelatorios", "value"))
        self.lblFaturamentoPeriodoValor.setText(_translate("PainelRelatorios", "R$ 0,00"))
        self.lblFaturamentoPeriodoTitulo.setProperty("role", _translate("PainelRelatorios", "title"))
        self.lblFaturamentoPeriodoTitulo.setText(_translate("PainelRelatorios", "Faturamento do Periodo"))
        self.lblTicketMedioValor.setProperty("role", _translate("PainelRelatorios", "value"))
        self.lblTicketMedioValor.setText(_translate("PainelRelatorios", "R$ 0,00"))
        self.lblTicketMedioTitulo.setProperty("role", _translate("PainelRelatorios", "title"))
        self.lblTicketMedioTitulo.setText(_translate("PainelRelatorios", "Ticket Medio"))
        self.lblClientesAtendidosValor.setProperty("role", _translate("PainelRelatorios", "value"))
        self.lblClientesAtendidosValor.setText(_translate("PainelRelatorios", "0"))
        self.lblClientesAtendidosTitulo.setProperty("role", _translate("PainelRelatorios", "title"))
        self.lblClientesAtendidosTitulo.setText(_translate("PainelRelatorios", "Clientes no Periodo"))
        self.lblIndicadoresSection.setProperty("sectionTitle", _translate("PainelRelatorios", "true"))
        self.lblIndicadoresSection.setText(_translate("PainelRelatorios", "Resumo por Periodo"))
        item = self.tableResumoPeriodo.horizontalHeaderItem(0)
        item.setText(_translate("PainelRelatorios", "Periodo"))
        item = self.tableResumoPeriodo.horizontalHeaderItem(1)
        item.setText(_translate("PainelRelatorios", "Vendas"))
        item = self.tableResumoPeriodo.horizontalHeaderItem(2)
        item.setText(_translate("PainelRelatorios", "Faturamento"))
        item = self.tableResumoPeriodo.horizontalHeaderItem(3)
        item.setText(_translate("PainelRelatorios", "Ticket Medio"))
        item = self.tableResumoPeriodo.horizontalHeaderItem(4)
        item.setText(_translate("PainelRelatorios", "Clientes"))
        self.lblProdutosRankingSection.setProperty("sectionTitle", _translate("PainelRelatorios", "true"))
        self.lblProdutosRankingSection.setText(_translate("PainelRelatorios", "Produtos Mais Vendidos"))
        item = self.tableProdutosMaisVendidos.horizontalHeaderItem(0)
        item.setText(_translate("PainelRelatorios", "Produto"))
        item = self.tableProdutosMaisVendidos.horizontalHeaderItem(1)
        item.setText(_translate("PainelRelatorios", "Qtd."))
        item = self.tableProdutosMaisVendidos.horizontalHeaderItem(2)
        item.setText(_translate("PainelRelatorios", "Receita"))
        item = self.tableProdutosMaisVendidos.horizontalHeaderItem(3)
        item.setText(_translate("PainelRelatorios", "Margem"))
        self.lblClientesRankingSection.setProperty("sectionTitle", _translate("PainelRelatorios", "true"))
        self.lblClientesRankingSection.setText(_translate("PainelRelatorios", "Clientes em Destaque"))
        item = self.tableClientesDestaque.horizontalHeaderItem(0)
        item.setText(_translate("PainelRelatorios", "Cliente"))
        item = self.tableClientesDestaque.horizontalHeaderItem(1)
        item.setText(_translate("PainelRelatorios", "Compras"))
        item = self.tableClientesDestaque.horizontalHeaderItem(2)
        item.setText(_translate("PainelRelatorios", "Total Gasto"))
        self.lblStatusSistema.setText(_translate("PainelRelatorios", "Sistema online"))
        self.lblStatusBar.setText(_translate("PainelRelatorios", "CSPdv - Central de Relatorios"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PainelRelatorios = QtWidgets.QMainWindow()
    ui = Ui_PainelRelatorios()
    ui.setupUi(PainelRelatorios)
    PainelRelatorios.show()
    sys.exit(app.exec_())
