# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel_financeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PainelFinanceiro(object):
    def setupUi(self, PainelFinanceiro):
        PainelFinanceiro.setObjectName("PainelFinanceiro")
        PainelFinanceiro.resize(1280, 768)
        self.centralWidget = QtWidgets.QWidget(PainelFinanceiro)
        self.centralWidget.setObjectName("centralWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(self.centralWidget)
        self.frameHeader.setStyleSheet("\n"
"QFrame#frameHeader {\n"
" background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #153552, stop:0.55 #1d4c74, stop:1 #2f75b0);\n"
" border-bottom: 1px solid rgba(255,255,255,28);\n"
"}\n"
"QLabel#lblLogo {\n"
" color: white;\n"
" font-size: 30px;\n"
" font-weight: 800;\n"
"}\n"
"QLabel#lblModulo {\n"
" color: #ffe59d;\n"
" font-size: 12px;\n"
" font-weight: 700;\n"
" padding: 8px 14px;\n"
" border-radius: 8px;\n"
" background-color: rgba(255,255,255,0.10);\n"
" border: 1px solid rgba(255,255,255,0.18);\n"
"}\n"
"QLabel#lblOperadorInfo, QLabel#lblDataHora {\n"
" color: #dbeaf7;\n"
" font-size: 12px;\n"
" font-weight: 600;\n"
"}\n"
"QPushButton#btnVoltarSelecao {\n"
" background-color: #d92b2b;\n"
" color: white;\n"
" border: none;\n"
" border-radius: 10px;\n"
" padding: 10px 24px;\n"
" font-size: 12px;\n"
" font-weight: 700;\n"
"}\n"
"QPushButton#btnVoltarSelecao:hover {\n"
" background-color: #c11f1f;\n"
"}\n"
"       ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(18, 12, 18, 12)
        self.headerHLayout.setSpacing(14)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,0.25);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblModulo = QtWidgets.QLabel(self.frameHeader)
        self.lblModulo.setObjectName("lblModulo")
        self.headerHLayout.addWidget(self.lblModulo)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.lblOperadorInfo = QtWidgets.QLabel(self.frameHeader)
        self.lblOperadorInfo.setObjectName("lblOperadorInfo")
        self.headerHLayout.addWidget(self.lblOperadorInfo)
        self.lblDataHora = QtWidgets.QLabel(self.frameHeader)
        self.lblDataHora.setObjectName("lblDataHora")
        self.headerHLayout.addWidget(self.lblDataHora)
        self.btnVoltarSelecao = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltarSelecao.setMinimumSize(QtCore.QSize(140, 42))
        self.btnVoltarSelecao.setObjectName("btnVoltarSelecao")
        self.headerHLayout.addWidget(self.btnVoltarSelecao)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameToolbar = QtWidgets.QFrame(self.centralWidget)
        self.frameToolbar.setMinimumSize(QtCore.QSize(0, 108))
        self.frameToolbar.setStyleSheet("\n"
"QFrame#frameToolbar { background-color: #eef5fb; border-bottom: 1px solid #c8d8e8; }\n"
"QFrame#frameToolbarFilters, QFrame#frameToolbarActions {\n"
" background-color: rgba(255,255,255,0.88);\n"
" border: 1px solid #d7e4ef;\n"
" border-radius: 8px;\n"
"}\n"
"QComboBox, QDateEdit, QLineEdit {\n"
" background-color: white; border: 1px solid #b8cde0; border-radius: 4px;\n"
" padding: 6px 8px; font-size: 12px; min-height: 34px;\n"
"}\n"
"QLineEdit {\n"
" color: #24415e;\n"
" selection-background-color: #3585c8;\n"
"}\n"
"QLabel[filterLabel=\"true\"] {\n"
" color: #46627d;\n"
" font-size: 11px;\n"
" font-weight: 700;\n"
" padding: 0 2px;\n"
"}\n"
"QPushButton {\n"
" background-color: #3585c8; color: white; border: none; border-radius: 4px;\n"
" padding: 6px 10px; font-size: 11px; font-weight: bold; min-height: 34px;\n"
"}\n"
"QPushButton:hover { background-color: #2b74b4; }\n"
"QPushButton#btnConsultarVenda { background-color: #5b6f86; }\n"
"QPushButton#btnConsultarVenda:hover { background-color: #4a5d73; }\n"
"QPushButton#btnReceberPendencia { background-color: #f0a039; }\n"
"QPushButton#btnReceberPendencia:hover { background-color: #de8b22; }\n"
"QPushButton#btnRegistrarReembolso { background-color: #d9534f; }\n"
"QPushButton#btnRegistrarReembolso:hover { background-color: #c64542; }\n"
"QPushButton#btnRegistrarMovimento { background-color: #5cb85c; }\n"
"QPushButton#btnRegistrarMovimento:hover { background-color: #4aa14a; }\n"
"       ")
        self.frameToolbar.setObjectName("frameToolbar")
        self.toolbarLayout = QtWidgets.QVBoxLayout(self.frameToolbar)
        self.toolbarLayout.setContentsMargins(12, 8, 12, 8)
        self.toolbarLayout.setSpacing(8)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.frameToolbarFilters = QtWidgets.QFrame(self.frameToolbar)
        self.frameToolbarFilters.setMinimumHeight(52)
        self.frameToolbarFilters.setObjectName("frameToolbarFilters")
        self.toolbarFiltrosLayout = QtWidgets.QHBoxLayout(self.frameToolbarFilters)
        self.toolbarFiltrosLayout.setContentsMargins(10, 8, 10, 8)
        self.toolbarFiltrosLayout.setSpacing(8)
        self.toolbarFiltrosLayout.setObjectName("toolbarFiltrosLayout")
        self.cmbPdvFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbPdvFiltro.setMinimumWidth(136)
        self.cmbPdvFiltro.setMaximumWidth(156)
        self.cmbPdvFiltro.setObjectName("cmbPdvFiltro")
        self.cmbPdvFiltro.addItem("")
        self.toolbarFiltrosLayout.addWidget(self.cmbPdvFiltro)
        self.cmbFormaPagamentoFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbFormaPagamentoFiltro.setMinimumWidth(168)
        self.cmbFormaPagamentoFiltro.setMaximumWidth(188)
        self.cmbFormaPagamentoFiltro.setObjectName("cmbFormaPagamentoFiltro")
        self.cmbFormaPagamentoFiltro.addItem("")
        self.toolbarFiltrosLayout.addWidget(self.cmbFormaPagamentoFiltro)
        self.lineEditBuscaConta = QtWidgets.QLineEdit(self.frameToolbar)
        self.lineEditBuscaConta.setMinimumWidth(150)
        self.lineEditBuscaConta.setMaximumWidth(260)
        self.lineEditBuscaConta.setObjectName("lineEditBuscaConta")
        self.toolbarFiltrosLayout.addWidget(self.lineEditBuscaConta)
        self.cmbStatusContaFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbStatusContaFiltro.setMinimumWidth(150)
        self.cmbStatusContaFiltro.setMaximumWidth(170)
        self.cmbStatusContaFiltro.setObjectName("cmbStatusContaFiltro")
        self.cmbStatusContaFiltro.addItem("")
        self.toolbarFiltrosLayout.addWidget(self.cmbStatusContaFiltro)
        self.framePeriodoFiltro = QtWidgets.QFrame(self.frameToolbarFilters)
        self.framePeriodoFiltro.setMinimumWidth(300)
        self.framePeriodoFiltro.setMaximumWidth(320)
        self.framePeriodoFiltro.setObjectName("framePeriodoFiltro")
        self.periodoLayout = QtWidgets.QHBoxLayout(self.framePeriodoFiltro)
        self.periodoLayout.setContentsMargins(0, 0, 0, 0)
        self.periodoLayout.setSpacing(6)
        self.periodoLayout.setObjectName("periodoLayout")
        self.lblPeriodoDe = QtWidgets.QLabel(self.framePeriodoFiltro)
        self.lblPeriodoDe.setObjectName("lblPeriodoDe")
        self.periodoLayout.addWidget(self.lblPeriodoDe)
        self.dateInicial = QtWidgets.QDateEdit(self.framePeriodoFiltro)
        self.dateInicial.setMinimumWidth(96)
        self.dateInicial.setMaximumWidth(106)
        self.dateInicial.setCalendarPopup(True)
        self.dateInicial.setObjectName("dateInicial")
        self.periodoLayout.addWidget(self.dateInicial)
        self.lblPeriodoAte = QtWidgets.QLabel(self.framePeriodoFiltro)
        self.lblPeriodoAte.setObjectName("lblPeriodoAte")
        self.periodoLayout.addWidget(self.lblPeriodoAte)
        self.dateFinal = QtWidgets.QDateEdit(self.framePeriodoFiltro)
        self.dateFinal.setMinimumWidth(96)
        self.dateFinal.setMaximumWidth(106)
        self.dateFinal.setCalendarPopup(True)
        self.dateFinal.setObjectName("dateFinal")
        self.periodoLayout.addWidget(self.dateFinal)
        self.toolbarFiltrosLayout.addWidget(self.framePeriodoFiltro)
        spacerItem2 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarFiltrosLayout.addItem(spacerItem2)
        self.toolbarLayout.addWidget(self.frameToolbarFilters)
        self.frameToolbarActions = QtWidgets.QFrame(self.frameToolbar)
        self.frameToolbarActions.setMinimumHeight(52)
        self.frameToolbarActions.setObjectName("frameToolbarActions")
        self.toolbarAcoesLayout = QtWidgets.QHBoxLayout(self.frameToolbarActions)
        self.toolbarAcoesLayout.setContentsMargins(10, 8, 10, 8)
        self.toolbarAcoesLayout.setSpacing(8)
        self.toolbarAcoesLayout.setObjectName("toolbarAcoesLayout")
        self.btnAtualizar = QtWidgets.QPushButton(self.frameToolbar)
        self.btnAtualizar.setMinimumWidth(84)
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.toolbarAcoesLayout.addWidget(self.btnAtualizar)
        self.btnConsultarVenda = QtWidgets.QPushButton(self.frameToolbar)
        self.btnConsultarVenda.setMinimumWidth(114)
        self.btnConsultarVenda.setObjectName("btnConsultarVenda")
        self.toolbarAcoesLayout.addWidget(self.btnConsultarVenda)
        self.btnReceberPendencia = QtWidgets.QPushButton(self.frameToolbar)
        self.btnReceberPendencia.setMinimumWidth(132)
        self.btnReceberPendencia.setObjectName("btnReceberPendencia")
        self.toolbarAcoesLayout.addWidget(self.btnReceberPendencia)
        self.btnRegistrarReembolso = QtWidgets.QPushButton(self.frameToolbar)
        self.btnRegistrarReembolso.setMinimumWidth(120)
        self.btnRegistrarReembolso.setObjectName("btnRegistrarReembolso")
        self.toolbarAcoesLayout.addWidget(self.btnRegistrarReembolso)
        self.btnAbrirCaixa = QtWidgets.QPushButton(self.frameToolbar)
        self.btnAbrirCaixa.setMinimumWidth(96)
        self.btnAbrirCaixa.setObjectName("btnAbrirCaixa")
        self.toolbarAcoesLayout.addWidget(self.btnAbrirCaixa)
        self.btnFecharCaixa = QtWidgets.QPushButton(self.frameToolbar)
        self.btnFecharCaixa.setMinimumWidth(96)
        self.btnFecharCaixa.setObjectName("btnFecharCaixa")
        self.toolbarAcoesLayout.addWidget(self.btnFecharCaixa)
        self.btnRegistrarMovimento = QtWidgets.QPushButton(self.frameToolbar)
        self.btnRegistrarMovimento.setMinimumWidth(142)
        self.btnRegistrarMovimento.setObjectName("btnRegistrarMovimento")
        self.toolbarAcoesLayout.addWidget(self.btnRegistrarMovimento)
        spacerItem3 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarAcoesLayout.addItem(spacerItem3)
        self.toolbarLayout.addWidget(self.frameToolbarActions)
        self.mainVLayout.addWidget(self.frameToolbar)
        self.contentVLayout = QtWidgets.QVBoxLayout()
        self.contentVLayout.setContentsMargins(16, 14, 16, 14)
        self.contentVLayout.setSpacing(12)
        self.contentVLayout.setObjectName("contentVLayout")
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(12)
        self.cardsLayout.setObjectName("cardsLayout")
        self.cardSaldoCaixa = QtWidgets.QFrame(self.centralWidget)
        self.cardSaldoCaixa.setStyleSheet("QFrame#cardSaldoCaixa { background-color: #3585c8; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #d8ebfb; font-size: 12px; }")
        self.cardSaldoCaixa.setObjectName("cardSaldoCaixa")
        self.cardSaldoCaixaLayout = QtWidgets.QVBoxLayout(self.cardSaldoCaixa)
        self.cardSaldoCaixaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardSaldoCaixaLayout.setObjectName("cardSaldoCaixaLayout")
        self.lblSaldoCaixaValor = QtWidgets.QLabel(self.cardSaldoCaixa)
        self.lblSaldoCaixaValor.setObjectName("lblSaldoCaixaValor")
        self.cardSaldoCaixaLayout.addWidget(self.lblSaldoCaixaValor)
        self.lblSaldoCaixaTitulo = QtWidgets.QLabel(self.cardSaldoCaixa)
        self.lblSaldoCaixaTitulo.setObjectName("lblSaldoCaixaTitulo")
        self.cardSaldoCaixaLayout.addWidget(self.lblSaldoCaixaTitulo)
        self.cardsLayout.addWidget(self.cardSaldoCaixa)
        self.cardEntradasDia = QtWidgets.QFrame(self.centralWidget)
        self.cardEntradasDia.setStyleSheet("QFrame#cardEntradasDia { background-color: #5cb85c; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #daf0da; font-size: 12px; }")
        self.cardEntradasDia.setObjectName("cardEntradasDia")
        self.cardEntradasDiaLayout = QtWidgets.QVBoxLayout(self.cardEntradasDia)
        self.cardEntradasDiaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardEntradasDiaLayout.setObjectName("cardEntradasDiaLayout")
        self.lblEntradasDiaValor = QtWidgets.QLabel(self.cardEntradasDia)
        self.lblEntradasDiaValor.setObjectName("lblEntradasDiaValor")
        self.cardEntradasDiaLayout.addWidget(self.lblEntradasDiaValor)
        self.lblEntradasDiaTitulo = QtWidgets.QLabel(self.cardEntradasDia)
        self.lblEntradasDiaTitulo.setObjectName("lblEntradasDiaTitulo")
        self.cardEntradasDiaLayout.addWidget(self.lblEntradasDiaTitulo)
        self.cardsLayout.addWidget(self.cardEntradasDia)
        self.cardSaidasDia = QtWidgets.QFrame(self.centralWidget)
        self.cardSaidasDia.setStyleSheet("QFrame#cardSaidasDia { background-color: #e67e22; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #fbe0c3; font-size: 12px; }")
        self.cardSaidasDia.setObjectName("cardSaidasDia")
        self.cardSaidasDiaLayout = QtWidgets.QVBoxLayout(self.cardSaidasDia)
        self.cardSaidasDiaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardSaidasDiaLayout.setObjectName("cardSaidasDiaLayout")
        self.lblSaidasDiaValor = QtWidgets.QLabel(self.cardSaidasDia)
        self.lblSaidasDiaValor.setObjectName("lblSaidasDiaValor")
        self.cardSaidasDiaLayout.addWidget(self.lblSaidasDiaValor)
        self.lblSaidasDiaTitulo = QtWidgets.QLabel(self.cardSaidasDia)
        self.lblSaidasDiaTitulo.setObjectName("lblSaidasDiaTitulo")
        self.cardSaidasDiaLayout.addWidget(self.lblSaidasDiaTitulo)
        self.cardsLayout.addWidget(self.cardSaidasDia)
        self.cardPagamentosPendentes = QtWidgets.QFrame(self.centralWidget)
        self.cardPagamentosPendentes.setStyleSheet("QFrame#cardPagamentosPendentes { background-color: #6c7ea0; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #d7def0; font-size: 12px; }")
        self.cardPagamentosPendentes.setObjectName("cardPagamentosPendentes")
        self.cardPagamentosPendentesLayout = QtWidgets.QVBoxLayout(self.cardPagamentosPendentes)
        self.cardPagamentosPendentesLayout.setContentsMargins(16, 14, 16, 14)
        self.cardPagamentosPendentesLayout.setObjectName("cardPagamentosPendentesLayout")
        self.lblPagamentosPendentesValor = QtWidgets.QLabel(self.cardPagamentosPendentes)
        self.lblPagamentosPendentesValor.setObjectName("lblPagamentosPendentesValor")
        self.cardPagamentosPendentesLayout.addWidget(self.lblPagamentosPendentesValor)
        self.lblPagamentosPendentesTitulo = QtWidgets.QLabel(self.cardPagamentosPendentes)
        self.lblPagamentosPendentesTitulo.setObjectName("lblPagamentosPendentesTitulo")
        self.cardPagamentosPendentesLayout.addWidget(self.lblPagamentosPendentesTitulo)
        self.cardsLayout.addWidget(self.cardPagamentosPendentes)
        self.contentVLayout.addLayout(self.cardsLayout)
        self.tablesLayout = QtWidgets.QHBoxLayout()
        self.tablesLayout.setSpacing(12)
        self.tablesLayout.setObjectName("tablesLayout")
        self.frameCaixaMovimentacoes = QtWidgets.QFrame(self.centralWidget)
        self.frameCaixaMovimentacoes.setStyleSheet("\n"
"QFrame#frameCaixaMovimentacoes, QFrame#frameRecebimentos {\n"
" background-color: white;\n"
" border: 1px solid #b8cde0;\n"
" border-radius: 6px;\n"
"}\n"
"QLabel[sectionTitle=\"true\"] {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 13px;\n"
" font-weight: bold;\n"
" padding: 8px 12px;\n"
" border-bottom: 1px solid #d8e3ee;\n"
"}\n"
"QLabel#lblRecebimentosSection {\n"
" background-color: #eef4fa;\n"
" color: #415a77;\n"
" border-bottom: 1px solid #d8e3ee;\n"
" border-top-left-radius: 6px;\n"
" border-top-right-radius: 6px;\n"
"}\n"
"QLabel#lblContasReceberSection {\n"
" background-color: #fff4e5;\n"
" color: #9a3412;\n"
" font-size: 13px;\n"
" font-weight: 800;\n"
" padding: 9px 12px;\n"
" border-top: 1px solid #f3d3a1;\n"
" border-bottom: 1px solid #f3d3a1;\n"
"}\n"
"QLabel#lblReembolsosSection {\n"
" background-color: #fef0f0;\n"
" color: #991b1b;\n"
" border-top: 1px solid #f3c4c4;\n"
" border-bottom: 1px solid #f3c4c4;\n"
"}\n"
"QTableWidget {\n"
" border: none;\n"
" background-color: white;\n"
" gridline-color: #dce8f0;\n"
" font-size: 12px;\n"
" selection-background-color: #dbeafe;\n"
" selection-color: #102a43;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-right: 1px solid #dce8f0;\n"
" border-bottom: 2px solid #3585c8;\n"
" padding: 5px 6px;\n"
"}\n"
"           ")
        self.frameCaixaMovimentacoes.setObjectName("frameCaixaMovimentacoes")
        self.frameCaixaMovimentacoesLayout = QtWidgets.QVBoxLayout(self.frameCaixaMovimentacoes)
        self.frameCaixaMovimentacoesLayout.setContentsMargins(0, 0, 0, 0)
        self.frameCaixaMovimentacoesLayout.setSpacing(0)
        self.frameCaixaMovimentacoesLayout.setObjectName("frameCaixaMovimentacoesLayout")
        self.lblCaixaMovimentacoesSection = QtWidgets.QLabel(self.frameCaixaMovimentacoes)
        self.lblCaixaMovimentacoesSection.setObjectName("lblCaixaMovimentacoesSection")
        self.frameCaixaMovimentacoesLayout.addWidget(self.lblCaixaMovimentacoesSection)
        self.tableCaixaMovimentacoes = QtWidgets.QTableWidget(self.frameCaixaMovimentacoes)
        self.tableCaixaMovimentacoes.setRowCount(0)
        self.tableCaixaMovimentacoes.setColumnCount(6)
        self.tableCaixaMovimentacoes.setObjectName("tableCaixaMovimentacoes")
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(5, item)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.tableCaixaMovimentacoes.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        self.tableCaixaMovimentacoes.horizontalHeader().setStretchLastSection(True)
        self.frameCaixaMovimentacoesLayout.addWidget(self.tableCaixaMovimentacoes)
        self.tablesLayout.addWidget(self.frameCaixaMovimentacoes)
        self.frameRecebimentos = QtWidgets.QFrame(self.centralWidget)
        self.frameRecebimentos.setMinimumSize(QtCore.QSize(500, 0))
        self.frameRecebimentos.setObjectName("frameRecebimentos")
        self.frameRecebimentosLayout = QtWidgets.QVBoxLayout(self.frameRecebimentos)
        self.frameRecebimentosLayout.setContentsMargins(8, 8, 8, 8)
        self.frameRecebimentosLayout.setSpacing(8)
        self.frameRecebimentosLayout.setObjectName("frameRecebimentosLayout")
        self.lblRecebimentosSection = QtWidgets.QLabel(self.frameRecebimentos)
        self.lblRecebimentosSection.setObjectName("lblRecebimentosSection")
        self.frameRecebimentosLayout.addWidget(self.lblRecebimentosSection)
        self.tablePagamentos = QtWidgets.QTableWidget(self.frameRecebimentos)
        self.tablePagamentos.setRowCount(0)
        self.tablePagamentos.setColumnCount(5)
        self.tablePagamentos.setObjectName("tablePagamentos")
        self.tablePagamentos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablePagamentos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePagamentos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablePagamentos.setMinimumHeight(150)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(4, item)
        self.tablePagamentos.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tablePagamentos.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.tablePagamentos.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tablePagamentos.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        self.tablePagamentos.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.tablePagamentos.horizontalHeader().setStretchLastSection(True)
        self.tablePagamentos.verticalHeader().setVisible(False)
        self.frameRecebimentosLayout.addWidget(self.tablePagamentos)
        self.lblContasReceberSection = QtWidgets.QLabel(self.frameRecebimentos)
        self.lblContasReceberSection.setObjectName("lblContasReceberSection")
        self.frameRecebimentosLayout.addWidget(self.lblContasReceberSection)
        self.tableContasReceber = QtWidgets.QTableWidget(self.frameRecebimentos)
        self.tableContasReceber.setRowCount(0)
        self.tableContasReceber.setColumnCount(5)
        self.tableContasReceber.setObjectName("tableContasReceber")
        self.tableContasReceber.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableContasReceber.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableContasReceber.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableContasReceber.setMinimumHeight(300)
        item = QtWidgets.QTableWidgetItem()
        self.tableContasReceber.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContasReceber.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContasReceber.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContasReceber.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableContasReceber.setHorizontalHeaderItem(4, item)
        self.tableContasReceber.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tableContasReceber.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.tableContasReceber.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tableContasReceber.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        self.tableContasReceber.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.tableContasReceber.horizontalHeader().setStretchLastSection(True)
        self.tableContasReceber.verticalHeader().setVisible(False)
        self.frameRecebimentosLayout.addWidget(self.tableContasReceber)
        self.lblReembolsosSection = QtWidgets.QLabel(self.frameRecebimentos)
        self.lblReembolsosSection.setObjectName("lblReembolsosSection")
        self.frameRecebimentosLayout.addWidget(self.lblReembolsosSection)
        self.tableReembolsos = QtWidgets.QTableWidget(self.frameRecebimentos)
        self.tableReembolsos.setRowCount(0)
        self.tableReembolsos.setColumnCount(5)
        self.tableReembolsos.setObjectName("tableReembolsos")
        self.tableReembolsos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableReembolsos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableReembolsos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableReembolsos.setMinimumHeight(140)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(4, item)
        self.tableReembolsos.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tableReembolsos.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.tableReembolsos.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.tableReembolsos.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        self.tableReembolsos.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.tableReembolsos.horizontalHeader().setStretchLastSection(True)
        self.tableReembolsos.verticalHeader().setVisible(False)
        self.frameRecebimentosLayout.addWidget(self.tableReembolsos)
        self.tablesLayout.addWidget(self.frameRecebimentos)
        self.tablesLayout.setStretch(0, 6)
        self.tablesLayout.setStretch(1, 5)
        self.contentVLayout.addLayout(self.tablesLayout)
        self.mainVLayout.addLayout(self.contentVLayout)
        self.frameStatusBar = QtWidgets.QFrame(self.centralWidget)
        self.frameStatusBar.setStyleSheet("\n"
"QFrame#frameStatusBar { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }\n"
"QLabel { color: white; font-size: 11px; }\n"
"QLabel#lblStatusSistema { color: #80ff80; font-weight: bold; }\n"
"       ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusLayout.setContentsMargins(12, -1, 12, -1)
        self.statusLayout.setObjectName("statusLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusLayout.addWidget(self.lblStatusSistema)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem1)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusLayout.addWidget(self.lblStatusBar)
        self.mainVLayout.addWidget(self.frameStatusBar)
        PainelFinanceiro.setCentralWidget(self.centralWidget)

        self.retranslateUi(PainelFinanceiro)
        QtCore.QMetaObject.connectSlotsByName(PainelFinanceiro)

    def retranslateUi(self, PainelFinanceiro):
        _translate = QtCore.QCoreApplication.translate
        PainelFinanceiro.setWindowTitle(_translate("PainelFinanceiro", "CSPdv - Financeiro e Reembolsos"))
        self.lblLogo.setText(_translate("PainelFinanceiro", "CSPdv"))
        self.lblModulo.setText(_translate("PainelFinanceiro", "FINANCEIRO, CAIXA E REEMBOLSOS"))
        self.lblOperadorInfo.setText(_translate("PainelFinanceiro", "Operador: ---"))
        self.lblDataHora.setText(_translate("PainelFinanceiro", "--/--/---- --:--:--"))
        self.btnVoltarSelecao.setText(_translate("PainelFinanceiro", "Voltar"))
        self.cmbPdvFiltro.setItemText(0, _translate("PainelFinanceiro", "Todos os PDVs"))
        self.cmbFormaPagamentoFiltro.setItemText(0, _translate("PainelFinanceiro", "Todas as formas de pagamento"))
        self.lineEditBuscaConta.setPlaceholderText(_translate("PainelFinanceiro", "Buscar por cliente, conta ou venda"))
        self.cmbStatusContaFiltro.setItemText(0, _translate("PainelFinanceiro", "Todas as contas abertas"))
        self.lblPeriodoDe.setProperty("filterLabel", _translate("PainelFinanceiro", "true"))
        self.lblPeriodoDe.setText(_translate("PainelFinanceiro", "De"))
        self.lblPeriodoAte.setProperty("filterLabel", _translate("PainelFinanceiro", "true"))
        self.lblPeriodoAte.setText(_translate("PainelFinanceiro", "Até"))
        self.btnAtualizar.setText(_translate("PainelFinanceiro", "Atualizar"))
        self.btnConsultarVenda.setText(_translate("PainelFinanceiro", "Consultar Venda"))
        self.btnReceberPendencia.setText(_translate("PainelFinanceiro", "Receber Pendência"))
        self.btnRegistrarReembolso.setText(_translate("PainelFinanceiro", "Novo Reembolso"))
        self.btnAbrirCaixa.setText(_translate("PainelFinanceiro", "Abrir Caixa"))
        self.btnFecharCaixa.setText(_translate("PainelFinanceiro", "Fechar Caixa"))
        self.btnRegistrarMovimento.setText(_translate("PainelFinanceiro", "Registrar Movimentação"))
        self.lblSaldoCaixaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblSaldoCaixaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblSaldoCaixaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblSaldoCaixaTitulo.setText(_translate("PainelFinanceiro", "Dinheiro em Caixas Abertos"))
        self.lblEntradasDiaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblEntradasDiaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblEntradasDiaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblEntradasDiaTitulo.setText(_translate("PainelFinanceiro", "Entradas no Periodo"))
        self.lblSaidasDiaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblSaidasDiaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblSaidasDiaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblSaidasDiaTitulo.setText(_translate("PainelFinanceiro", "Saidas no Periodo"))
        self.lblPagamentosPendentesValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblPagamentosPendentesValor.setText(_translate("PainelFinanceiro", "0"))
        self.lblPagamentosPendentesTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblPagamentosPendentesTitulo.setText(_translate("PainelFinanceiro", "Contas em Aberto"))
        self.lblCaixaMovimentacoesSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblCaixaMovimentacoesSection.setText(_translate("PainelFinanceiro", "Movimentações de Caixa"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Data/Hora"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "PDV"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Operador"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Motivo"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Forma Pgto."))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(5)
        item.setText(_translate("PainelFinanceiro", "Valor"))
        self.lblRecebimentosSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblRecebimentosSection.setText(_translate("PainelFinanceiro", "Vendas Registradas"))
        item = self.tablePagamentos.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Venda"))
        item = self.tablePagamentos.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "Cliente"))
        item = self.tablePagamentos.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Forma"))
        item = self.tablePagamentos.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Status"))
        item = self.tablePagamentos.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Total"))
        self.lblContasReceberSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblContasReceberSection.setText(_translate("PainelFinanceiro", "Contas a Receber"))
        item = self.tableContasReceber.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Conta"))
        item = self.tableContasReceber.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "Cliente"))
        item = self.tableContasReceber.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Vencimento"))
        item = self.tableContasReceber.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Status"))
        item = self.tableContasReceber.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Em Aberto"))
        self.lblReembolsosSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblReembolsosSection.setText(_translate("PainelFinanceiro", "Reembolsos Registrados"))
        item = self.tableReembolsos.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Venda"))
        item = self.tableReembolsos.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "Tipo"))
        item = self.tableReembolsos.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Motivo"))
        item = self.tableReembolsos.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Status"))
        item = self.tableReembolsos.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Valor"))
        self.lblStatusSistema.setText(_translate("PainelFinanceiro", "Sistema online"))
        self.lblStatusBar.setText(_translate("PainelFinanceiro", "CSPdv - Módulo Financeiro"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PainelFinanceiro = QtWidgets.QMainWindow()
    ui = Ui_PainelFinanceiro()
    ui.setupUi(PainelFinanceiro)
    PainelFinanceiro.show()
    sys.exit(app.exec_())
