# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel_financeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PainelFinanceiro(object):
    def setupUi(self, PainelFinanceiro):
        PainelFinanceiro.setObjectName("PainelFinanceiro")
        PainelFinanceiro.resize(1366, 768)
        self.centralWidget = QtWidgets.QWidget(PainelFinanceiro)
        self.centralWidget.setObjectName("centralWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(self.centralWidget)
        self.frameHeader.setStyleSheet("\n"
"QFrame#frameHeader { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }\n"
"QLabel#lblLogo { color: white; font-size: 28px; font-weight: bold; }\n"
"QLabel#lblModulo {\n"
" color: #ffe39a; font-size: 12px; font-weight: bold;\n"
" background-color: rgba(255,255,255,30);\n"
" border: 1px solid rgba(255,255,255,60);\n"
" border-radius: 4px; padding: 3px 10px;\n"
"}\n"
"QLabel#lblOperadorInfo, QLabel#lblDataHora { color: #d9ebfb; font-size: 11px; }\n"
"QPushButton#btnVoltarSelecao {\n"
" background-color: #cc2222; color: white; border: none; border-radius: 4px;\n"
" padding: 6px 12px; font-size: 11px; font-weight: bold;\n"
"}\n"
"QPushButton#btnVoltarSelecao:hover { background-color: #e03030; }\n"
"       ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(14, 8, 14, 8)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblModulo = QtWidgets.QLabel(self.frameHeader)
        self.lblModulo.setObjectName("lblModulo")
        self.headerHLayout.addWidget(self.lblModulo)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.lblOperadorInfo = QtWidgets.QLabel(self.frameHeader)
        self.lblOperadorInfo.setObjectName("lblOperadorInfo")
        self.headerHLayout.addWidget(self.lblOperadorInfo)
        self.lblDataHora = QtWidgets.QLabel(self.frameHeader)
        self.lblDataHora.setObjectName("lblDataHora")
        self.headerHLayout.addWidget(self.lblDataHora)
        self.btnVoltarSelecao = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltarSelecao.setObjectName("btnVoltarSelecao")
        self.headerHLayout.addWidget(self.btnVoltarSelecao)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameToolbar = QtWidgets.QFrame(self.centralWidget)
        self.frameToolbar.setMinimumSize(QtCore.QSize(0, 56))
        self.frameToolbar.setStyleSheet("\n"
"QFrame#frameToolbar { background-color: #f0f6fc; border-bottom: 1px solid #c8d8e8; }\n"
"QComboBox, QDateEdit {\n"
" background-color: white; border: 1px solid #b8cde0; border-radius: 4px;\n"
" padding: 6px 8px; font-size: 12px;\n"
"}\n"
"QPushButton {\n"
" background-color: #3585c8; color: white; border: none; border-radius: 4px;\n"
" padding: 6px 12px; font-size: 12px; font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #2b74b4; }\n"
"QPushButton#btnRegistrarMovimento { background-color: #5cb85c; }\n"
"QPushButton#btnRegistrarMovimento:hover { background-color: #4aa14a; }\n"
"       ")
        self.frameToolbar.setObjectName("frameToolbar")
        self.toolbarLayout = QtWidgets.QHBoxLayout(self.frameToolbar)
        self.toolbarLayout.setContentsMargins(16, 10, 16, 10)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.cmbPdvFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbPdvFiltro.setObjectName("cmbPdvFiltro")
        self.cmbPdvFiltro.addItem("")
        self.toolbarLayout.addWidget(self.cmbPdvFiltro)
        self.cmbFormaPagamentoFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbFormaPagamentoFiltro.setObjectName("cmbFormaPagamentoFiltro")
        self.cmbFormaPagamentoFiltro.addItem("")
        self.toolbarLayout.addWidget(self.cmbFormaPagamentoFiltro)
        self.dateInicial = QtWidgets.QDateEdit(self.frameToolbar)
        self.dateInicial.setCalendarPopup(True)
        self.dateInicial.setObjectName("dateInicial")
        self.toolbarLayout.addWidget(self.dateInicial)
        self.dateFinal = QtWidgets.QDateEdit(self.frameToolbar)
        self.dateFinal.setCalendarPopup(True)
        self.dateFinal.setObjectName("dateFinal")
        self.toolbarLayout.addWidget(self.dateFinal)
        self.btnAtualizar = QtWidgets.QPushButton(self.frameToolbar)
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.toolbarLayout.addWidget(self.btnAtualizar)
        self.btnAbrirCaixa = QtWidgets.QPushButton(self.frameToolbar)
        self.btnAbrirCaixa.setObjectName("btnAbrirCaixa")
        self.toolbarLayout.addWidget(self.btnAbrirCaixa)
        self.btnFecharCaixa = QtWidgets.QPushButton(self.frameToolbar)
        self.btnFecharCaixa.setObjectName("btnFecharCaixa")
        self.toolbarLayout.addWidget(self.btnFecharCaixa)
        self.btnRegistrarMovimento = QtWidgets.QPushButton(self.frameToolbar)
        self.btnRegistrarMovimento.setObjectName("btnRegistrarMovimento")
        self.toolbarLayout.addWidget(self.btnRegistrarMovimento)
        self.mainVLayout.addWidget(self.frameToolbar)
        self.contentVLayout = QtWidgets.QVBoxLayout()
        self.contentVLayout.setContentsMargins(16, 14, 16, 14)
        self.contentVLayout.setSpacing(12)
        self.contentVLayout.setObjectName("contentVLayout")
        self.cardsLayout = QtWidgets.QHBoxLayout()
        self.cardsLayout.setSpacing(12)
        self.cardsLayout.setObjectName("cardsLayout")
        self.cardSaldoCaixa = QtWidgets.QFrame(self.centralWidget)
        self.cardSaldoCaixa.setStyleSheet("QFrame#cardSaldoCaixa { background-color: #3585c8; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #d8ebfb; font-size: 12px; }")
        self.cardSaldoCaixa.setObjectName("cardSaldoCaixa")
        self.cardSaldoCaixaLayout = QtWidgets.QVBoxLayout(self.cardSaldoCaixa)
        self.cardSaldoCaixaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardSaldoCaixaLayout.setObjectName("cardSaldoCaixaLayout")
        self.lblSaldoCaixaValor = QtWidgets.QLabel(self.cardSaldoCaixa)
        self.lblSaldoCaixaValor.setObjectName("lblSaldoCaixaValor")
        self.cardSaldoCaixaLayout.addWidget(self.lblSaldoCaixaValor)
        self.lblSaldoCaixaTitulo = QtWidgets.QLabel(self.cardSaldoCaixa)
        self.lblSaldoCaixaTitulo.setObjectName("lblSaldoCaixaTitulo")
        self.cardSaldoCaixaLayout.addWidget(self.lblSaldoCaixaTitulo)
        self.cardsLayout.addWidget(self.cardSaldoCaixa)
        self.cardEntradasDia = QtWidgets.QFrame(self.centralWidget)
        self.cardEntradasDia.setStyleSheet("QFrame#cardEntradasDia { background-color: #5cb85c; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #daf0da; font-size: 12px; }")
        self.cardEntradasDia.setObjectName("cardEntradasDia")
        self.cardEntradasDiaLayout = QtWidgets.QVBoxLayout(self.cardEntradasDia)
        self.cardEntradasDiaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardEntradasDiaLayout.setObjectName("cardEntradasDiaLayout")
        self.lblEntradasDiaValor = QtWidgets.QLabel(self.cardEntradasDia)
        self.lblEntradasDiaValor.setObjectName("lblEntradasDiaValor")
        self.cardEntradasDiaLayout.addWidget(self.lblEntradasDiaValor)
        self.lblEntradasDiaTitulo = QtWidgets.QLabel(self.cardEntradasDia)
        self.lblEntradasDiaTitulo.setObjectName("lblEntradasDiaTitulo")
        self.cardEntradasDiaLayout.addWidget(self.lblEntradasDiaTitulo)
        self.cardsLayout.addWidget(self.cardEntradasDia)
        self.cardSaidasDia = QtWidgets.QFrame(self.centralWidget)
        self.cardSaidasDia.setStyleSheet("QFrame#cardSaidasDia { background-color: #e67e22; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #fbe0c3; font-size: 12px; }")
        self.cardSaidasDia.setObjectName("cardSaidasDia")
        self.cardSaidasDiaLayout = QtWidgets.QVBoxLayout(self.cardSaidasDia)
        self.cardSaidasDiaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardSaidasDiaLayout.setObjectName("cardSaidasDiaLayout")
        self.lblSaidasDiaValor = QtWidgets.QLabel(self.cardSaidasDia)
        self.lblSaidasDiaValor.setObjectName("lblSaidasDiaValor")
        self.cardSaidasDiaLayout.addWidget(self.lblSaidasDiaValor)
        self.lblSaidasDiaTitulo = QtWidgets.QLabel(self.cardSaidasDia)
        self.lblSaidasDiaTitulo.setObjectName("lblSaidasDiaTitulo")
        self.cardSaidasDiaLayout.addWidget(self.lblSaidasDiaTitulo)
        self.cardsLayout.addWidget(self.cardSaidasDia)
        self.cardPagamentosPendentes = QtWidgets.QFrame(self.centralWidget)
        self.cardPagamentosPendentes.setStyleSheet("QFrame#cardPagamentosPendentes { background-color: #6c7ea0; border-radius: 8px; } QLabel { color: white; } QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; } QLabel[role=\"title\"] { color: #d7def0; font-size: 12px; }")
        self.cardPagamentosPendentes.setObjectName("cardPagamentosPendentes")
        self.cardPagamentosPendentesLayout = QtWidgets.QVBoxLayout(self.cardPagamentosPendentes)
        self.cardPagamentosPendentesLayout.setContentsMargins(16, 14, 16, 14)
        self.cardPagamentosPendentesLayout.setObjectName("cardPagamentosPendentesLayout")
        self.lblPagamentosPendentesValor = QtWidgets.QLabel(self.cardPagamentosPendentes)
        self.lblPagamentosPendentesValor.setObjectName("lblPagamentosPendentesValor")
        self.cardPagamentosPendentesLayout.addWidget(self.lblPagamentosPendentesValor)
        self.lblPagamentosPendentesTitulo = QtWidgets.QLabel(self.cardPagamentosPendentes)
        self.lblPagamentosPendentesTitulo.setObjectName("lblPagamentosPendentesTitulo")
        self.cardPagamentosPendentesLayout.addWidget(self.lblPagamentosPendentesTitulo)
        self.cardsLayout.addWidget(self.cardPagamentosPendentes)
        self.contentVLayout.addLayout(self.cardsLayout)
        self.tablesLayout = QtWidgets.QHBoxLayout()
        self.tablesLayout.setSpacing(12)
        self.tablesLayout.setObjectName("tablesLayout")
        self.frameCaixaMovimentacoes = QtWidgets.QFrame(self.centralWidget)
        self.frameCaixaMovimentacoes.setStyleSheet("\n"
"QFrame#frameCaixaMovimentacoes, QFrame#frameRecebimentos {\n"
" background-color: white;\n"
" border: 1px solid #b8cde0;\n"
" border-radius: 6px;\n"
"}\n"
"QLabel[sectionTitle=\"true\"] {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 13px;\n"
" font-weight: bold;\n"
" padding: 8px 12px;\n"
" border-bottom: 1px solid #d8e3ee;\n"
"}\n"
"QTableWidget {\n"
" border: none;\n"
" background-color: white;\n"
" gridline-color: #dce8f0;\n"
" font-size: 12px;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-right: 1px solid #dce8f0;\n"
" border-bottom: 2px solid #3585c8;\n"
" padding: 5px 6px;\n"
"}\n"
"           ")
        self.frameCaixaMovimentacoes.setObjectName("frameCaixaMovimentacoes")
        self.frameCaixaMovimentacoesLayout = QtWidgets.QVBoxLayout(self.frameCaixaMovimentacoes)
        self.frameCaixaMovimentacoesLayout.setContentsMargins(0, 0, 0, 0)
        self.frameCaixaMovimentacoesLayout.setSpacing(0)
        self.frameCaixaMovimentacoesLayout.setObjectName("frameCaixaMovimentacoesLayout")
        self.lblCaixaMovimentacoesSection = QtWidgets.QLabel(self.frameCaixaMovimentacoes)
        self.lblCaixaMovimentacoesSection.setObjectName("lblCaixaMovimentacoesSection")
        self.frameCaixaMovimentacoesLayout.addWidget(self.lblCaixaMovimentacoesSection)
        self.tableCaixaMovimentacoes = QtWidgets.QTableWidget(self.frameCaixaMovimentacoes)
        self.tableCaixaMovimentacoes.setRowCount(0)
        self.tableCaixaMovimentacoes.setColumnCount(6)
        self.tableCaixaMovimentacoes.setObjectName("tableCaixaMovimentacoes")
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCaixaMovimentacoes.setHorizontalHeaderItem(5, item)
        self.tableCaixaMovimentacoes.horizontalHeader().setStretchLastSection(True)
        self.frameCaixaMovimentacoesLayout.addWidget(self.tableCaixaMovimentacoes)
        self.tablesLayout.addWidget(self.frameCaixaMovimentacoes)
        self.frameRecebimentos = QtWidgets.QFrame(self.centralWidget)
        self.frameRecebimentos.setMinimumSize(QtCore.QSize(430, 0))
        self.frameRecebimentos.setObjectName("frameRecebimentos")
        self.frameRecebimentosLayout = QtWidgets.QVBoxLayout(self.frameRecebimentos)
        self.frameRecebimentosLayout.setContentsMargins(0, 0, 0, 0)
        self.frameRecebimentosLayout.setSpacing(0)
        self.frameRecebimentosLayout.setObjectName("frameRecebimentosLayout")
        self.lblRecebimentosSection = QtWidgets.QLabel(self.frameRecebimentos)
        self.lblRecebimentosSection.setObjectName("lblRecebimentosSection")
        self.frameRecebimentosLayout.addWidget(self.lblRecebimentosSection)
        self.tablePagamentos = QtWidgets.QTableWidget(self.frameRecebimentos)
        self.tablePagamentos.setRowCount(0)
        self.tablePagamentos.setColumnCount(5)
        self.tablePagamentos.setObjectName("tablePagamentos")
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePagamentos.setHorizontalHeaderItem(4, item)
        self.tablePagamentos.horizontalHeader().setStretchLastSection(True)
        self.frameRecebimentosLayout.addWidget(self.tablePagamentos)
        self.lblReembolsosSection = QtWidgets.QLabel(self.frameRecebimentos)
        self.lblReembolsosSection.setObjectName("lblReembolsosSection")
        self.frameRecebimentosLayout.addWidget(self.lblReembolsosSection)
        self.tableReembolsos = QtWidgets.QTableWidget(self.frameRecebimentos)
        self.tableReembolsos.setRowCount(0)
        self.tableReembolsos.setColumnCount(4)
        self.tableReembolsos.setObjectName("tableReembolsos")
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableReembolsos.setHorizontalHeaderItem(3, item)
        self.tableReembolsos.horizontalHeader().setStretchLastSection(True)
        self.frameRecebimentosLayout.addWidget(self.tableReembolsos)
        self.tablesLayout.addWidget(self.frameRecebimentos)
        self.contentVLayout.addLayout(self.tablesLayout)
        self.mainVLayout.addLayout(self.contentVLayout)
        self.frameStatusBar = QtWidgets.QFrame(self.centralWidget)
        self.frameStatusBar.setStyleSheet("\n"
"QFrame#frameStatusBar { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }\n"
"QLabel { color: white; font-size: 11px; }\n"
"QLabel#lblStatusSistema { color: #80ff80; font-weight: bold; }\n"
"       ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusLayout.setContentsMargins(12, -1, 12, -1)
        self.statusLayout.setObjectName("statusLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusLayout.addWidget(self.lblStatusSistema)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem1)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusLayout.addWidget(self.lblStatusBar)
        self.mainVLayout.addWidget(self.frameStatusBar)
        PainelFinanceiro.setCentralWidget(self.centralWidget)

        self.retranslateUi(PainelFinanceiro)
        QtCore.QMetaObject.connectSlotsByName(PainelFinanceiro)

    def retranslateUi(self, PainelFinanceiro):
        _translate = QtCore.QCoreApplication.translate
        PainelFinanceiro.setWindowTitle(_translate("PainelFinanceiro", "CSPdv - Financeiro"))
        self.lblLogo.setText(_translate("PainelFinanceiro", "CSPdv"))
        self.lblModulo.setText(_translate("PainelFinanceiro", "FINANCEIRO E CAIXA"))
        self.lblOperadorInfo.setText(_translate("PainelFinanceiro", "Operador: ---"))
        self.lblDataHora.setText(_translate("PainelFinanceiro", "--/--/---- --:--:--"))
        self.btnVoltarSelecao.setText(_translate("PainelFinanceiro", "Voltar"))
        self.cmbPdvFiltro.setItemText(0, _translate("PainelFinanceiro", "Todos os PDVs"))
        self.cmbFormaPagamentoFiltro.setItemText(0, _translate("PainelFinanceiro", "Todas as formas de pagamento"))
        self.btnAtualizar.setText(_translate("PainelFinanceiro", "Atualizar"))
        self.btnAbrirCaixa.setText(_translate("PainelFinanceiro", "Abrir Caixa"))
        self.btnFecharCaixa.setText(_translate("PainelFinanceiro", "Fechar Caixa"))
        self.btnRegistrarMovimento.setText(_translate("PainelFinanceiro", "Registrar Sangria/Suprimento"))
        self.lblSaldoCaixaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblSaldoCaixaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblSaldoCaixaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblSaldoCaixaTitulo.setText(_translate("PainelFinanceiro", "Saldo Atual do Caixa"))
        self.lblEntradasDiaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblEntradasDiaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblEntradasDiaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblEntradasDiaTitulo.setText(_translate("PainelFinanceiro", "Entradas do Dia"))
        self.lblSaidasDiaValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblSaidasDiaValor.setText(_translate("PainelFinanceiro", "R$ 0,00"))
        self.lblSaidasDiaTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblSaidasDiaTitulo.setText(_translate("PainelFinanceiro", "Saidas do Dia"))
        self.lblPagamentosPendentesValor.setProperty("role", _translate("PainelFinanceiro", "value"))
        self.lblPagamentosPendentesValor.setText(_translate("PainelFinanceiro", "0"))
        self.lblPagamentosPendentesTitulo.setProperty("role", _translate("PainelFinanceiro", "title"))
        self.lblPagamentosPendentesTitulo.setText(_translate("PainelFinanceiro", "Parcelas Pendentes"))
        self.lblCaixaMovimentacoesSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblCaixaMovimentacoesSection.setText(_translate("PainelFinanceiro", "Movimentacoes de Caixa"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Data/Hora"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "PDV"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Operador"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Motivo"))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Forma Pgto."))
        item = self.tableCaixaMovimentacoes.horizontalHeaderItem(5)
        item.setText(_translate("PainelFinanceiro", "Valor"))
        self.lblRecebimentosSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblRecebimentosSection.setText(_translate("PainelFinanceiro", "Pagamentos e Parcelas"))
        item = self.tablePagamentos.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Venda"))
        item = self.tablePagamentos.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "Forma"))
        item = self.tablePagamentos.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Parcelas"))
        item = self.tablePagamentos.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Status"))
        item = self.tablePagamentos.horizontalHeaderItem(4)
        item.setText(_translate("PainelFinanceiro", "Total"))
        self.lblReembolsosSection.setProperty("sectionTitle", _translate("PainelFinanceiro", "true"))
        self.lblReembolsosSection.setText(_translate("PainelFinanceiro", "Reembolsos"))
        item = self.tableReembolsos.horizontalHeaderItem(0)
        item.setText(_translate("PainelFinanceiro", "Venda"))
        item = self.tableReembolsos.horizontalHeaderItem(1)
        item.setText(_translate("PainelFinanceiro", "Tipo"))
        item = self.tableReembolsos.horizontalHeaderItem(2)
        item.setText(_translate("PainelFinanceiro", "Status"))
        item = self.tableReembolsos.horizontalHeaderItem(3)
        item.setText(_translate("PainelFinanceiro", "Valor"))
        self.lblStatusSistema.setText(_translate("PainelFinanceiro", "Sistema online"))
        self.lblStatusBar.setText(_translate("PainelFinanceiro", "CSPdv - Modulo Financeiro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PainelFinanceiro = QtWidgets.QMainWindow()
    ui = Ui_PainelFinanceiro()
    ui.setupUi(PainelFinanceiro)
    PainelFinanceiro.show()
    sys.exit(app.exec_())
