from PyQt5 import QtCore, QtWidgets


class Ui_ReceberPendenciaDialog(object):
    def setupUi(self, ReceberPendenciaDialog):
        ReceberPendenciaDialog.setObjectName("ReceberPendenciaDialog")
        ReceberPendenciaDialog.resize(760, 520)
        ReceberPendenciaDialog.setMinimumSize(QtCore.QSize(720, 500))
        ReceberPendenciaDialog.setStyleSheet(
            "QDialog{background-color:#edf4fb;}"
            "QFrame#frameCard{background-color:#ffffff;border:1px solid #c8d9ea;border-radius:12px;}"
            "QLabel{color:#153d68;font-size:12px;}"
            "QLabel#lblTitulo{font-size:24px;font-weight:bold;color:#123f6f;}"
            "QLabel#lblSubtitulo{font-size:12px;color:#5c7c9c;}"
            "QLabel.infoLabel{font-size:11px;font-weight:bold;color:#557596;letter-spacing:0.6px;}"
            "QLabel.infoValue{font-size:16px;font-weight:bold;color:#123f6f;}"
            "QComboBox,QLineEdit,QDateEdit,QPlainTextEdit{background-color:#fbfdff;border:1px solid #bfd3e6;border-radius:8px;color:#153d68;padding:8px;}"
            "QComboBox,QLineEdit,QDateEdit{min-height:40px;font-size:13px;}"
            "QPlainTextEdit{font-size:13px;}"
            "QPushButton{min-height:42px;border-radius:8px;font-size:13px;font-weight:bold;padding:0 18px;}"
            "QPushButton#btnCancelar{background-color:#eef4fa;border:1px solid #c2d6e8;color:#355d83;}"
            "QPushButton#btnCancelar:hover{background-color:#e4edf6;}"
            "QPushButton#btnConfirmar{background-color:#2f7ed1;border:1px solid #2568af;color:#ffffff;}"
            "QPushButton#btnConfirmar:hover{background-color:#3a8ae0;}"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(ReceberPendenciaDialog)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCard = QtWidgets.QFrame(ReceberPendenciaDialog)
        self.frameCard.setObjectName("frameCard")
        self.cardLayout = QtWidgets.QVBoxLayout(self.frameCard)
        self.cardLayout.setContentsMargins(22, 20, 22, 18)
        self.cardLayout.setSpacing(16)
        self.cardLayout.setObjectName("cardLayout")
        self.lblTitulo = QtWidgets.QLabel(self.frameCard)
        self.lblTitulo.setObjectName("lblTitulo")
        self.cardLayout.addWidget(self.lblTitulo)
        self.lblSubtitulo = QtWidgets.QLabel(self.frameCard)
        self.lblSubtitulo.setWordWrap(True)
        self.lblSubtitulo.setObjectName("lblSubtitulo")
        self.cardLayout.addWidget(self.lblSubtitulo)
        self.gridResumo = QtWidgets.QGridLayout()
        self.gridResumo.setHorizontalSpacing(16)
        self.gridResumo.setVerticalSpacing(8)
        self.gridResumo.setObjectName("gridResumo")
        self.lblContaLabel = QtWidgets.QLabel(self.frameCard)
        self.lblContaLabel.setObjectName("lblContaLabel")
        self.lblContaLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblContaLabel, 0, 0, 1, 1)
        self.lblContaValor = QtWidgets.QLabel(self.frameCard)
        self.lblContaValor.setObjectName("lblContaValor")
        self.lblContaValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblContaValor, 1, 0, 1, 1)
        self.lblClienteLabel = QtWidgets.QLabel(self.frameCard)
        self.lblClienteLabel.setObjectName("lblClienteLabel")
        self.lblClienteLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblClienteLabel, 0, 1, 1, 1)
        self.lblClienteValor = QtWidgets.QLabel(self.frameCard)
        self.lblClienteValor.setObjectName("lblClienteValor")
        self.lblClienteValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblClienteValor, 1, 1, 1, 1)
        self.lblVencimentoLabel = QtWidgets.QLabel(self.frameCard)
        self.lblVencimentoLabel.setObjectName("lblVencimentoLabel")
        self.lblVencimentoLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblVencimentoLabel, 0, 2, 1, 1)
        self.lblVencimentoValor = QtWidgets.QLabel(self.frameCard)
        self.lblVencimentoValor.setObjectName("lblVencimentoValor")
        self.lblVencimentoValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblVencimentoValor, 1, 2, 1, 1)
        self.lblTotalLabel = QtWidgets.QLabel(self.frameCard)
        self.lblTotalLabel.setObjectName("lblTotalLabel")
        self.lblTotalLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblTotalLabel, 2, 0, 1, 1)
        self.lblTotalValor = QtWidgets.QLabel(self.frameCard)
        self.lblTotalValor.setObjectName("lblTotalValor")
        self.lblTotalValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblTotalValor, 3, 0, 1, 1)
        self.lblRecebidoLabel = QtWidgets.QLabel(self.frameCard)
        self.lblRecebidoLabel.setObjectName("lblRecebidoLabel")
        self.lblRecebidoLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblRecebidoLabel, 2, 1, 1, 1)
        self.lblRecebidoValor = QtWidgets.QLabel(self.frameCard)
        self.lblRecebidoValor.setObjectName("lblRecebidoValor")
        self.lblRecebidoValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblRecebidoValor, 3, 1, 1, 1)
        self.lblAbertoLabel = QtWidgets.QLabel(self.frameCard)
        self.lblAbertoLabel.setObjectName("lblAbertoLabel")
        self.lblAbertoLabel.setProperty("class", "infoLabel")
        self.gridResumo.addWidget(self.lblAbertoLabel, 2, 2, 1, 1)
        self.lblAbertoValor = QtWidgets.QLabel(self.frameCard)
        self.lblAbertoValor.setObjectName("lblAbertoValor")
        self.lblAbertoValor.setProperty("class", "infoValue")
        self.gridResumo.addWidget(self.lblAbertoValor, 3, 2, 1, 1)
        self.cardLayout.addLayout(self.gridResumo)
        self.formGrid = QtWidgets.QGridLayout()
        self.formGrid.setHorizontalSpacing(12)
        self.formGrid.setVerticalSpacing(12)
        self.formGrid.setObjectName("formGrid")
        self.lblForma = QtWidgets.QLabel(self.frameCard)
        self.lblForma.setObjectName("lblForma")
        self.formGrid.addWidget(self.lblForma, 0, 0, 1, 1)
        self.cmbFormaPagamento = QtWidgets.QComboBox(self.frameCard)
        self.cmbFormaPagamento.setObjectName("cmbFormaPagamento")
        self.formGrid.addWidget(self.cmbFormaPagamento, 1, 0, 1, 1)
        self.lblValor = QtWidgets.QLabel(self.frameCard)
        self.lblValor.setObjectName("lblValor")
        self.formGrid.addWidget(self.lblValor, 0, 1, 1, 1)
        self.lineEditValor = QtWidgets.QLineEdit(self.frameCard)
        self.lineEditValor.setObjectName("lineEditValor")
        self.formGrid.addWidget(self.lineEditValor, 1, 1, 1, 1)
        self.lblDataRecebimento = QtWidgets.QLabel(self.frameCard)
        self.lblDataRecebimento.setObjectName("lblDataRecebimento")
        self.formGrid.addWidget(self.lblDataRecebimento, 0, 2, 1, 1)
        self.dateRecebimento = QtWidgets.QDateEdit(self.frameCard)
        self.dateRecebimento.setCalendarPopup(True)
        self.dateRecebimento.setObjectName("dateRecebimento")
        self.formGrid.addWidget(self.dateRecebimento, 1, 2, 1, 1)
        self.lblObservacao = QtWidgets.QLabel(self.frameCard)
        self.lblObservacao.setObjectName("lblObservacao")
        self.formGrid.addWidget(self.lblObservacao, 2, 0, 1, 3)
        self.textObservacao = QtWidgets.QPlainTextEdit(self.frameCard)
        self.textObservacao.setMinimumHeight(120)
        self.textObservacao.setObjectName("textObservacao")
        self.formGrid.addWidget(self.textObservacao, 3, 0, 1, 3)
        self.cardLayout.addLayout(self.formGrid)
        self.botoesLayout = QtWidgets.QHBoxLayout()
        self.botoesLayout.setSpacing(10)
        self.botoesLayout.setObjectName("botoesLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesLayout.addItem(spacerItem)
        self.btnCancelar = QtWidgets.QPushButton(self.frameCard)
        self.btnCancelar.setObjectName("btnCancelar")
        self.botoesLayout.addWidget(self.btnCancelar)
        self.btnConfirmar = QtWidgets.QPushButton(self.frameCard)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.botoesLayout.addWidget(self.btnConfirmar)
        self.cardLayout.addLayout(self.botoesLayout)
        self.verticalLayout.addWidget(self.frameCard)

        self.retranslateUi(ReceberPendenciaDialog)
        QtCore.QMetaObject.connectSlotsByName(ReceberPendenciaDialog)

    def retranslateUi(self, ReceberPendenciaDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceberPendenciaDialog.setWindowTitle(_translate("ReceberPendenciaDialog", "CSPdv - Receber Pendência"))
        self.lblTitulo.setText(_translate("ReceberPendenciaDialog", "Receber Pendência"))
        self.lblSubtitulo.setText(_translate("ReceberPendenciaDialog", "Registre o recebimento parcial ou total da conta em aberto sem sair do módulo financeiro."))
        self.lblContaLabel.setText(_translate("ReceberPendenciaDialog", "CONTA"))
        self.lblContaValor.setText(_translate("ReceberPendenciaDialog", "#0"))
        self.lblClienteLabel.setText(_translate("ReceberPendenciaDialog", "CLIENTE"))
        self.lblClienteValor.setText(_translate("ReceberPendenciaDialog", "Consumidor Final"))
        self.lblVencimentoLabel.setText(_translate("ReceberPendenciaDialog", "VENCIMENTO"))
        self.lblVencimentoValor.setText(_translate("ReceberPendenciaDialog", "--/--/----"))
        self.lblTotalLabel.setText(_translate("ReceberPendenciaDialog", "VALOR TOTAL"))
        self.lblTotalValor.setText(_translate("ReceberPendenciaDialog", "R$ 0,00"))
        self.lblRecebidoLabel.setText(_translate("ReceberPendenciaDialog", "JÁ RECEBIDO"))
        self.lblRecebidoValor.setText(_translate("ReceberPendenciaDialog", "R$ 0,00"))
        self.lblAbertoLabel.setText(_translate("ReceberPendenciaDialog", "SALDO EM ABERTO"))
        self.lblAbertoValor.setText(_translate("ReceberPendenciaDialog", "R$ 0,00"))
        self.lblForma.setText(_translate("ReceberPendenciaDialog", "Forma de pagamento *"))
        self.lblValor.setText(_translate("ReceberPendenciaDialog", "Valor recebido *"))
        self.lblDataRecebimento.setText(_translate("ReceberPendenciaDialog", "Data do recebimento"))
        self.lblObservacao.setText(_translate("ReceberPendenciaDialog", "Observação"))
        self.btnCancelar.setText(_translate("ReceberPendenciaDialog", "Cancelar"))
        self.btnConfirmar.setText(_translate("ReceberPendenciaDialog", "Registrar Recebimento"))
