# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selecao_modo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SelecaoModo(object):
    def setupUi(self, SelecaoModo):
        SelecaoModo.setObjectName("SelecaoModo")
        SelecaoModo.resize(1279, 820)
        SelecaoModo.setStyleSheet("\n"
"QWidget {\n"
" font-family: \'Segoe UI\', Arial;\n"
" background-color: #0c2238;\n"
" color: white;\n"
"}\n"
"QLabel {\n"
" background-color: transparent;\n"
"}\n"
"QFrame#frameHero {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #13385c, stop:1 #0b1f33);\n"
" border-bottom: 1px solid #21486b;\n"
"}\n"
"QLabel#lblTitulo {\n"
" font-size: 28px;\n"
" font-weight: bold;\n"
" color: white;\n"
"}\n"
"QLabel#lblSubtitulo, QLabel#lblVersao {\n"
" background-color: transparent;\n"
" font-size: 12px;\n"
" color: #a8c3da;\n"
"}\n"
"QFrame#frameAtalhos {\n"
" background-color: rgba(255,255,255,0.04);\n"
" border: 1px solid #234d72;\n"
" border-radius: 10px;\n"
"}\n"
"QLabel#lblAtalhosTitulo {\n"
" background-color: transparent;\n"
" color: #d8ebfb;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" text-transform: uppercase;\n"
"}\n"
"QLabel#lblAtalhosTexto {\n"
" background-color: transparent;\n"
" color: #b6cbdf;\n"
" font-size: 11px;\n"
"}\n"
"QFrame[card=\"true\"] {\n"
" background-color: #112c47;\n"
" border: 1px solid #234d72;\n"
" border-radius: 18px;\n"
"}\n"
"QLabel[moduleBadge=\"true\"] {\n"
" background-color: rgba(255,255,255,24);\n"
" color: #d8ebfb;\n"
" border: 1px solid rgba(255,255,255,35);\n"
" border-radius: 11px;\n"
" padding: 4px 10px;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
"}\n"
"QLabel[moduleTitle=\"true\"] {\n"
" background-color: transparent;\n"
" font-size: 22px;\n"
" font-weight: bold;\n"
" color: white;\n"
"}\n"
"QLabel[moduleDesc=\"true\"] {\n"
" background-color: transparent;\n"
" font-size: 12px;\n"
" color: #a8c3da;\n"
"}\n"
"QPushButton[moduleCard=\"true\"] {\n"
" background-color: #163758;\n"
" color: white;\n"
" border: 1px solid #2b5e87;\n"
" border-radius: 10px;\n"
" padding: 10px 14px;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" text-align: center;\n"
"}\n"
"QPushButton[moduleCard=\"true\"]:hover {\n"
" background-color: #1d466c;\n"
" border-color: #3d78a8;\n"
"}\n"
"QPushButton[moduleCard=\"true\"]:pressed {\n"
" background-color: #10314e;\n"
"}\n"
"QPushButton#btnSairSessao {\n"
" background-color: #c53030;\n"
" color: white;\n"
" border: none;\n"
" border-radius: 6px;\n"
" padding: 8px 16px;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
"}\n"
"QPushButton#btnSairSessao:hover {\n"
" background-color: #df4242;\n"
"}\n"
"QFrame#frameFooter {\n"
" background-color: #09192a;\n"
" border-top: 1px solid #163753;\n"
"}\n"
"QLabel#lblOperadorNome {\n"
" background-color: transparent;\n"
" font-weight: bold;\n"
" color: #70e28b;\n"
" font-size: 12px;\n"
"}\n"
"   ")
        self.mainVLayout = QtWidgets.QVBoxLayout(SelecaoModo)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHero = QtWidgets.QFrame(SelecaoModo)
        self.frameHero.setMinimumSize(QtCore.QSize(0, 180))
        self.frameHero.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frameHero.setObjectName("frameHero")
        self.heroVLayout = QtWidgets.QVBoxLayout(self.frameHero)
        self.heroVLayout.setContentsMargins(28, 24, 28, 20)
        self.heroVLayout.setObjectName("heroVLayout")
        self.heroTopLayout = QtWidgets.QHBoxLayout()
        self.heroTopLayout.setObjectName("heroTopLayout")
        self.lblTitulo = QtWidgets.QLabel(self.frameHero)
        self.lblTitulo.setObjectName("lblTitulo")
        self.heroTopLayout.addWidget(self.lblTitulo)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.heroTopLayout.addItem(spacerItem)
        self.btnSairSessao = QtWidgets.QPushButton(self.frameHero)
        self.btnSairSessao.setMinimumSize(QtCore.QSize(110, 38))
        self.btnSairSessao.setObjectName("btnSairSessao")
        self.heroTopLayout.addWidget(self.btnSairSessao)
        self.heroVLayout.addLayout(self.heroTopLayout)
        self.lblSubtitulo = QtWidgets.QLabel(self.frameHero)
        self.lblSubtitulo.setObjectName("lblSubtitulo")
        self.heroVLayout.addWidget(self.lblSubtitulo)
        self.frameAtalhos = QtWidgets.QFrame(self.frameHero)
        self.frameAtalhos.setMinimumSize(QtCore.QSize(0, 34))
        self.frameAtalhos.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frameAtalhos.setObjectName("frameAtalhos")
        self.frameAtalhosLayout = QtWidgets.QHBoxLayout(self.frameAtalhos)
        self.frameAtalhosLayout.setContentsMargins(14, 6, 14, 6)
        self.frameAtalhosLayout.setSpacing(10)
        self.frameAtalhosLayout.setObjectName("frameAtalhosLayout")
        self.lblAtalhosTitulo = QtWidgets.QLabel(self.frameAtalhos)
        self.lblAtalhosTitulo.setObjectName("lblAtalhosTitulo")
        self.frameAtalhosLayout.addWidget(self.lblAtalhosTitulo)
        spacerItemAtalhos = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.frameAtalhosLayout.addItem(spacerItemAtalhos)
        self.lblAtalhosTexto = QtWidgets.QLabel(self.frameAtalhos)
        self.lblAtalhosTexto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.lblAtalhosTexto.setObjectName("lblAtalhosTexto")
        self.frameAtalhosLayout.addWidget(self.lblAtalhosTexto)
        self.heroVLayout.addWidget(self.frameAtalhos)
        self.mainVLayout.addWidget(self.frameHero)
        self.layoutContent = QtWidgets.QGridLayout()
        self.layoutContent.setContentsMargins(26, 24, 26, 24)
        self.layoutContent.setSpacing(18)
        self.layoutContent.setObjectName("layoutContent")
        self.cardFrenteCaixa = QtWidgets.QFrame(SelecaoModo)
        self.cardFrenteCaixa.setObjectName("cardFrenteCaixa")
        self.cardFrenteCaixaLayout = QtWidgets.QVBoxLayout(self.cardFrenteCaixa)
        self.cardFrenteCaixaLayout.setContentsMargins(18, 18, 18, 18)
        self.cardFrenteCaixaLayout.setSpacing(12)
        self.cardFrenteCaixaLayout.setObjectName("cardFrenteCaixaLayout")
        self.lblBadgePdv = QtWidgets.QLabel(self.cardFrenteCaixa)
        self.lblBadgePdv.setObjectName("lblBadgePdv")
        self.cardFrenteCaixaLayout.addWidget(self.lblBadgePdv)
        self.lblTitlePdv = QtWidgets.QLabel(self.cardFrenteCaixa)
        self.lblTitlePdv.setObjectName("lblTitlePdv")
        self.cardFrenteCaixaLayout.addWidget(self.lblTitlePdv)
        self.lblFrenteCaixa = QtWidgets.QLabel(self.cardFrenteCaixa)
        self.lblFrenteCaixa.setWordWrap(True)
        self.lblFrenteCaixa.setObjectName("lblFrenteCaixa")
        self.cardFrenteCaixaLayout.addWidget(self.lblFrenteCaixa)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardFrenteCaixaLayout.addItem(spacerItem1)
        self.btnFrenteCaixa = QtWidgets.QPushButton(self.cardFrenteCaixa)
        self.btnFrenteCaixa.setObjectName("btnFrenteCaixa")
        self.cardFrenteCaixaLayout.addWidget(self.btnFrenteCaixa)
        self.layoutContent.addWidget(self.cardFrenteCaixa, 0, 0, 1, 1)
        self.cardAdmin = QtWidgets.QFrame(SelecaoModo)
        self.cardAdmin.setObjectName("cardAdmin")
        self.cardAdminLayout = QtWidgets.QVBoxLayout(self.cardAdmin)
        self.cardAdminLayout.setContentsMargins(18, 18, 18, 18)
        self.cardAdminLayout.setSpacing(12)
        self.cardAdminLayout.setObjectName("cardAdminLayout")
        self.lblBadgeAdmin = QtWidgets.QLabel(self.cardAdmin)
        self.lblBadgeAdmin.setObjectName("lblBadgeAdmin")
        self.cardAdminLayout.addWidget(self.lblBadgeAdmin)
        self.lblTitleAdmin = QtWidgets.QLabel(self.cardAdmin)
        self.lblTitleAdmin.setObjectName("lblTitleAdmin")
        self.cardAdminLayout.addWidget(self.lblTitleAdmin)
        self.lblPainelAdmin = QtWidgets.QLabel(self.cardAdmin)
        self.lblPainelAdmin.setWordWrap(True)
        self.lblPainelAdmin.setObjectName("lblPainelAdmin")
        self.cardAdminLayout.addWidget(self.lblPainelAdmin)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardAdminLayout.addItem(spacerItem2)
        self.btnPainelAdmin = QtWidgets.QPushButton(self.cardAdmin)
        self.btnPainelAdmin.setObjectName("btnPainelAdmin")
        self.cardAdminLayout.addWidget(self.btnPainelAdmin)
        self.layoutContent.addWidget(self.cardAdmin, 0, 1, 1, 1)
        self.cardEstoque = QtWidgets.QFrame(SelecaoModo)
        self.cardEstoque.setObjectName("cardEstoque")
        self.cardEstoqueLayout = QtWidgets.QVBoxLayout(self.cardEstoque)
        self.cardEstoqueLayout.setContentsMargins(18, 18, 18, 18)
        self.cardEstoqueLayout.setSpacing(12)
        self.cardEstoqueLayout.setObjectName("cardEstoqueLayout")
        self.lblBadgeEstoque = QtWidgets.QLabel(self.cardEstoque)
        self.lblBadgeEstoque.setObjectName("lblBadgeEstoque")
        self.cardEstoqueLayout.addWidget(self.lblBadgeEstoque)
        self.lblTitleEstoque = QtWidgets.QLabel(self.cardEstoque)
        self.lblTitleEstoque.setObjectName("lblTitleEstoque")
        self.cardEstoqueLayout.addWidget(self.lblTitleEstoque)
        self.lblEstoque = QtWidgets.QLabel(self.cardEstoque)
        self.lblEstoque.setWordWrap(True)
        self.lblEstoque.setObjectName("lblEstoque")
        self.cardEstoqueLayout.addWidget(self.lblEstoque)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardEstoqueLayout.addItem(spacerItem3)
        self.btnEstoque = QtWidgets.QPushButton(self.cardEstoque)
        self.btnEstoque.setObjectName("btnEstoque")
        self.cardEstoqueLayout.addWidget(self.btnEstoque)
        self.layoutContent.addWidget(self.cardEstoque, 0, 2, 1, 1)
        self.cardFinanceiro = QtWidgets.QFrame(SelecaoModo)
        self.cardFinanceiro.setObjectName("cardFinanceiro")
        self.cardFinanceiroLayout = QtWidgets.QVBoxLayout(self.cardFinanceiro)
        self.cardFinanceiroLayout.setContentsMargins(18, 18, 18, 18)
        self.cardFinanceiroLayout.setSpacing(12)
        self.cardFinanceiroLayout.setObjectName("cardFinanceiroLayout")
        self.lblBadgeFinanceiro = QtWidgets.QLabel(self.cardFinanceiro)
        self.lblBadgeFinanceiro.setObjectName("lblBadgeFinanceiro")
        self.cardFinanceiroLayout.addWidget(self.lblBadgeFinanceiro)
        self.lblTitleFinanceiro = QtWidgets.QLabel(self.cardFinanceiro)
        self.lblTitleFinanceiro.setObjectName("lblTitleFinanceiro")
        self.cardFinanceiroLayout.addWidget(self.lblTitleFinanceiro)
        self.lblFinanceiro = QtWidgets.QLabel(self.cardFinanceiro)
        self.lblFinanceiro.setWordWrap(True)
        self.lblFinanceiro.setObjectName("lblFinanceiro")
        self.cardFinanceiroLayout.addWidget(self.lblFinanceiro)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardFinanceiroLayout.addItem(spacerItem4)
        self.btnFinanceiro = QtWidgets.QPushButton(self.cardFinanceiro)
        self.btnFinanceiro.setObjectName("btnFinanceiro")
        self.cardFinanceiroLayout.addWidget(self.btnFinanceiro)
        self.layoutContent.addWidget(self.cardFinanceiro, 1, 0, 1, 1)
        self.cardRelatorios = QtWidgets.QFrame(SelecaoModo)
        self.cardRelatorios.setObjectName("cardRelatorios")
        self.cardRelatoriosLayout = QtWidgets.QVBoxLayout(self.cardRelatorios)
        self.cardRelatoriosLayout.setContentsMargins(18, 18, 18, 18)
        self.cardRelatoriosLayout.setSpacing(12)
        self.cardRelatoriosLayout.setObjectName("cardRelatoriosLayout")
        self.lblBadgeRelatorios = QtWidgets.QLabel(self.cardRelatorios)
        self.lblBadgeRelatorios.setObjectName("lblBadgeRelatorios")
        self.cardRelatoriosLayout.addWidget(self.lblBadgeRelatorios)
        self.lblTitleRelatorios = QtWidgets.QLabel(self.cardRelatorios)
        self.lblTitleRelatorios.setObjectName("lblTitleRelatorios")
        self.cardRelatoriosLayout.addWidget(self.lblTitleRelatorios)
        self.lblRelatorios = QtWidgets.QLabel(self.cardRelatorios)
        self.lblRelatorios.setWordWrap(True)
        self.lblRelatorios.setObjectName("lblRelatorios")
        self.cardRelatoriosLayout.addWidget(self.lblRelatorios)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardRelatoriosLayout.addItem(spacerItem5)
        self.btnRelatorios = QtWidgets.QPushButton(self.cardRelatorios)
        self.btnRelatorios.setObjectName("btnRelatorios")
        self.cardRelatoriosLayout.addWidget(self.btnRelatorios)
        self.layoutContent.addWidget(self.cardRelatorios, 1, 1, 1, 1)
        self.cardResumo = QtWidgets.QFrame(SelecaoModo)
        self.cardResumo.setObjectName("cardResumo")
        self.cardResumoLayout = QtWidgets.QVBoxLayout(self.cardResumo)
        self.cardResumoLayout.setContentsMargins(24, 22, 24, 22)
        self.cardResumoLayout.setSpacing(14)
        self.cardResumoLayout.setObjectName("cardResumoLayout")
        self.lblResumoBadge = QtWidgets.QLabel(self.cardResumo)
        self.lblResumoBadge.setObjectName("lblResumoBadge")
        self.cardResumoLayout.addWidget(self.lblResumoBadge)
        self.lblResumoTitle = QtWidgets.QLabel(self.cardResumo)
        self.lblResumoTitle.setObjectName("lblResumoTitle")
        self.cardResumoLayout.addWidget(self.lblResumoTitle)
        self.lblResumoText3 = QtWidgets.QLabel(self.cardResumo)
        self.lblResumoText3.setWordWrap(True)
        self.lblResumoText3.setObjectName("lblResumoText3")
        self.cardResumoLayout.addWidget(self.lblResumoText3)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardResumoLayout.addItem(spacerItem6)
        self.btnResumoRelatorios = QtWidgets.QPushButton(self.cardResumo)
        self.btnResumoRelatorios.setObjectName("btnResumoRelatorios")
        self.cardResumoLayout.addWidget(self.btnResumoRelatorios)
        self.layoutContent.addWidget(self.cardResumo, 1, 2, 1, 1)
        self.mainVLayout.addLayout(self.layoutContent)
        self.frameFooter = QtWidgets.QFrame(SelecaoModo)
        self.frameFooter.setMinimumSize(QtCore.QSize(0, 54))
        self.frameFooter.setMaximumSize(QtCore.QSize(16777215, 54))
        self.frameFooter.setObjectName("frameFooter")
        self.footerLayout = QtWidgets.QHBoxLayout(self.frameFooter)
        self.footerLayout.setContentsMargins(18, 8, 18, 8)
        self.footerLayout.setSpacing(10)
        self.footerLayout.setObjectName("footerLayout")
        self.lblOperadorNome = QtWidgets.QLabel(self.frameFooter)
        self.lblOperadorNome.setObjectName("lblOperadorNome")
        self.footerLayout.addWidget(self.lblOperadorNome)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footerLayout.addItem(spacerItem6)
        self.lblVersao = QtWidgets.QLabel(self.frameFooter)
        self.lblVersao.setObjectName("lblVersao")
        self.footerLayout.addWidget(self.lblVersao)
        self.mainVLayout.addWidget(self.frameFooter)

        self.retranslateUi(SelecaoModo)
        QtCore.QMetaObject.connectSlotsByName(SelecaoModo)

    def retranslateUi(self, SelecaoModo):
        _translate = QtCore.QCoreApplication.translate
        SelecaoModo.setWindowTitle(_translate("SelecaoModo", "CSPdv - Seleção de Áreas"))
        self.lblTitulo.setText(_translate("SelecaoModo", "CSPdv • Centro de Operações"))
        self.btnSairSessao.setText(_translate("SelecaoModo", "SAIR (ESC)"))
        self.lblSubtitulo.setText(_translate("SelecaoModo", "Selecione o módulo desejado."))
        self.cardFrenteCaixa.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblBadgePdv.setText(_translate("SelecaoModo", "F1 • OPERAÇÃO"))
        self.lblBadgePdv.setProperty("moduleBadge", _translate("SelecaoModo", "true"))
        self.lblTitlePdv.setText(_translate("SelecaoModo", "Frente de Caixa"))
        self.lblTitlePdv.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblFrenteCaixa.setText(_translate("SelecaoModo", "Vendas, caixa e atendimento em operação contínua."))
        self.lblFrenteCaixa.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.btnFrenteCaixa.setToolTip(_translate("SelecaoModo", "[F1] Frente de caixa"))
        self.btnFrenteCaixa.setText(_translate("SelecaoModo", "Acessar Frente de Caixa"))
        self.btnFrenteCaixa.setProperty("moduleCard", _translate("SelecaoModo", "true"))
        self.cardAdmin.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblBadgeAdmin.setText(_translate("SelecaoModo", "F2 • ADMINISTRAÇÃO"))
        self.lblBadgeAdmin.setProperty("moduleBadge", _translate("SelecaoModo", "true"))
        self.lblTitleAdmin.setText(_translate("SelecaoModo", "Painel Admin"))
        self.lblTitleAdmin.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblPainelAdmin.setText(_translate("SelecaoModo", "Usuários, perfis, permissões, cargos e cadastros mestres."))
        self.lblPainelAdmin.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.btnPainelAdmin.setToolTip(_translate("SelecaoModo", "[F2] Painel administrativo"))
        self.btnPainelAdmin.setText(_translate("SelecaoModo", "Acessar Painel Admin"))
        self.btnPainelAdmin.setProperty("moduleCard", _translate("SelecaoModo", "true"))
        self.cardEstoque.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblBadgeEstoque.setText(_translate("SelecaoModo", "F3 • ESTOQUE"))
        self.lblBadgeEstoque.setProperty("moduleBadge", _translate("SelecaoModo", "true"))
        self.lblTitleEstoque.setText(_translate("SelecaoModo", "Estoque"))
        self.lblTitleEstoque.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblEstoque.setText(_translate("SelecaoModo", "Produtos, lotes, validade, ajustes e movimentações."))
        self.lblEstoque.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.btnEstoque.setToolTip(_translate("SelecaoModo", "[F3] Estoque"))
        self.btnEstoque.setText(_translate("SelecaoModo", "Acessar Estoque"))
        self.btnEstoque.setProperty("moduleCard", _translate("SelecaoModo", "true"))
        self.cardFinanceiro.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblBadgeFinanceiro.setText(_translate("SelecaoModo", "F4 • FINANCEIRO"))
        self.lblBadgeFinanceiro.setProperty("moduleBadge", _translate("SelecaoModo", "true"))
        self.lblTitleFinanceiro.setText(_translate("SelecaoModo", "Financeiro"))
        self.lblTitleFinanceiro.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblFinanceiro.setText(_translate("SelecaoModo", "Caixa, pagamentos, parcelas, reembolsos e posição diária."))
        self.lblFinanceiro.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.btnFinanceiro.setToolTip(_translate("SelecaoModo", "[F4] Financeiro"))
        self.btnFinanceiro.setText(_translate("SelecaoModo", "Acessar Financeiro"))
        self.btnFinanceiro.setProperty("moduleCard", _translate("SelecaoModo", "true"))
        self.cardRelatorios.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblBadgeRelatorios.setText(_translate("SelecaoModo", "F5 • PROMOÇÕES"))
        self.lblBadgeRelatorios.setProperty("moduleBadge", _translate("SelecaoModo", "true"))
        self.lblTitleRelatorios.setText(_translate("SelecaoModo", "Promoções"))
        self.lblTitleRelatorios.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblRelatorios.setText(_translate("SelecaoModo", "Campanhas, ofertas e ações promocionais para apoiar as vendas."))
        self.lblRelatorios.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.btnRelatorios.setToolTip(_translate("SelecaoModo", "[F5] Promoções"))
        self.btnRelatorios.setText(_translate("SelecaoModo", "Acessar Promoções"))
        self.btnRelatorios.setProperty("moduleCard", _translate("SelecaoModo", "true"))
        self.cardResumo.setProperty("card", _translate("SelecaoModo", "true"))
        self.lblResumoTitle.setText(_translate("SelecaoModo", "Atalhos"))
        self.lblResumoTitle.setProperty("moduleTitle", _translate("SelecaoModo", "true"))
        self.lblResumoText3.setText(_translate("SelecaoModo", "F1 - Frente de Caixa\nF2 - Administração\nF3 - Estoque\nF4 - Financeiro\nF5 - Promoções"))
        self.lblResumoText3.setProperty("moduleDesc", _translate("SelecaoModo", "true"))
        self.lblResumoText3.setWordWrap(True)
        self.lblResumoText3.setText(_translate("SelecaoModo", "<html><head/><body><div style=\"line-height:1.9;\"><table cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"54\"><span style=\"font-weight:700; color:#9fd0ff;\">F1</span></td><td>Frente de Caixa</td></tr><tr><td width=\"54\"><span style=\"font-weight:700; color:#9fd0ff;\">F2</span></td><td>Administração</td></tr><tr><td width=\"54\"><span style=\"font-weight:700; color:#9fd0ff;\">F3</span></td><td>Estoque</td></tr><tr><td width=\"54\"><span style=\"font-weight:700; color:#9fd0ff;\">F4</span></td><td>Financeiro</td></tr><tr><td width=\"54\"><span style=\"font-weight:700; color:#9fd0ff;\">F5</span></td><td>Promoções</td></tr></table></div></body></html>"))
        self.lblResumoText3.setText(_translate("SelecaoModo", "<html><head/><body><div style=\"line-height:1.8;\"><table cellspacing=\"0\" cellpadding=\"3\"><tr><td><span style=\"display:inline-block; min-width:32px; padding:2px 8px; border-radius:10px; background:#2a4f75; color:#d8ecff; font-weight:700; text-align:center;\">F1</span></td><td style=\"padding-left:10px;\">Frente de Caixa</td></tr><tr><td><span style=\"display:inline-block; min-width:32px; padding:2px 8px; border-radius:10px; background:#2a4f75; color:#d8ecff; font-weight:700; text-align:center;\">F2</span></td><td style=\"padding-left:10px;\">Administração</td></tr><tr><td><span style=\"display:inline-block; min-width:32px; padding:2px 8px; border-radius:10px; background:#2a4f75; color:#d8ecff; font-weight:700; text-align:center;\">F3</span></td><td style=\"padding-left:10px;\">Estoque</td></tr><tr><td><span style=\"display:inline-block; min-width:32px; padding:2px 8px; border-radius:10px; background:#2a4f75; color:#d8ecff; font-weight:700; text-align:center;\">F4</span></td><td style=\"padding-left:10px;\">Financeiro</td></tr><tr><td><span style=\"display:inline-block; min-width:32px; padding:2px 8px; border-radius:10px; background:#2a4f75; color:#d8ecff; font-weight:700; text-align:center;\">F5</span></td><td style=\"padding-left:10px;\">Promoções</td></tr></table></div></body></html>"))
        self.lblOperadorNome.setText(_translate("SelecaoModo", "OPERADOR: ---"))
        self.lblVersao.setText(_translate("SelecaoModo", "CSPdv v1.0.0"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelecaoModo = QtWidgets.QWidget()
    ui = Ui_SelecaoModo()
    ui.setupUi(SelecaoModo)
    SelecaoModo.show()
    sys.exit(app.exec_())
