# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selecao_modo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelecaoModo(object):
    def setupUi(self, SelecaoModo):
        SelecaoModo.setObjectName("SelecaoModo")
        SelecaoModo.resize(1200, 800)
        SelecaoModo.setStyleSheet("\n"
"    QWidget {\n"
"        font-family: \'Segoe UI\', Arial;\n"
"        background-color: #0f2a4a;\n"
"        color: white;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #1a3a5a;\n"
"        border: 2px solid #2a4a6a;\n"
"        border-radius: 15px;\n"
"        color: white;\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        min-height: 120px;\n"
"        min-width: 200px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #2a4a6a;\n"
"        border-color: #3a6aaa;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #0a1a2a;\n"
"    }\n"
"    QLabel#lblTitulo {\n"
"        font-size: 24px;\n"
"        font-weight: bold;\n"
"        color: #ffffff;\n"
"    }\n"
"    QLabel {\n"
"        font-size: 14px;\n"
"        color: #a0aec0;\n"
"    }\n"
"   ")
        self.mainVLayout = QtWidgets.QVBoxLayout(SelecaoModo)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(SelecaoModo)
        self.frameHeader.setMinimumSize(QtCore.QSize(0, 80))
        self.frameHeader.setStyleSheet("background-color: #0a1f35; border-bottom: 1px solid #1a3a5a;")
        self.frameHeader.setObjectName("frameHeader")
        self.headerLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerLayout.setObjectName("headerLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.lblTitulo = QtWidgets.QLabel(self.frameHeader)
        self.lblTitulo.setObjectName("lblTitulo")
        self.headerLayout.addWidget(self.lblTitulo)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem1)
        self.btnSairSessao = QtWidgets.QPushButton(self.frameHeader)
        self.btnSairSessao.setMinimumSize(QtCore.QSize(104, 43))
        self.btnSairSessao.setStyleSheet("background-color: #c53030; min-height: 40px; min-width: 100px; font-size: 12px;")
        self.btnSairSessao.setObjectName("btnSairSessao")
        self.headerLayout.addWidget(self.btnSairSessao)
        self.mainVLayout.addWidget(self.frameHeader)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem2)
        self.layoutContent = QtWidgets.QGridLayout()
        self.layoutContent.setContentsMargins(50, -1, 50, -1)
        self.layoutContent.setSpacing(40)
        self.layoutContent.setObjectName("layoutContent")
        self.vboxPDV = QtWidgets.QVBoxLayout()
        self.vboxPDV.setObjectName("vboxPDV")
        self.btnFrenteCaixa = QtWidgets.QPushButton(SelecaoModo)
        self.btnFrenteCaixa.setObjectName("btnFrenteCaixa")
        self.vboxPDV.addWidget(self.btnFrenteCaixa)
        self.lblFrenteCaixa = QtWidgets.QLabel(SelecaoModo)
        self.lblFrenteCaixa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFrenteCaixa.setObjectName("lblFrenteCaixa")
        self.vboxPDV.addWidget(self.lblFrenteCaixa)
        self.layoutContent.addLayout(self.vboxPDV, 0, 0, 1, 1)
        self.vboxEstoque = QtWidgets.QVBoxLayout()
        self.vboxEstoque.setObjectName("vboxEstoque")
        self.btnEstoque = QtWidgets.QPushButton(SelecaoModo)
        self.btnEstoque.setObjectName("btnEstoque")
        self.vboxEstoque.addWidget(self.btnEstoque)
        self.lblEstoque = QtWidgets.QLabel(SelecaoModo)
        self.lblEstoque.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEstoque.setObjectName("lblEstoque")
        self.vboxEstoque.addWidget(self.lblEstoque)
        self.layoutContent.addLayout(self.vboxEstoque, 0, 1, 1, 1)
        self.vboxFinanceiro = QtWidgets.QVBoxLayout()
        self.vboxFinanceiro.setObjectName("vboxFinanceiro")
        self.btnFinanceiro = QtWidgets.QPushButton(SelecaoModo)
        self.btnFinanceiro.setObjectName("btnFinanceiro")
        self.vboxFinanceiro.addWidget(self.btnFinanceiro)
        self.lblFinanceiro = QtWidgets.QLabel(SelecaoModo)
        self.lblFinanceiro.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFinanceiro.setObjectName("lblFinanceiro")
        self.vboxFinanceiro.addWidget(self.lblFinanceiro)
        self.layoutContent.addLayout(self.vboxFinanceiro, 0, 2, 1, 1)
        self.vboxRelatorios = QtWidgets.QVBoxLayout()
        self.vboxRelatorios.setObjectName("vboxRelatorios")
        self.btnRelatorios = QtWidgets.QPushButton(SelecaoModo)
        self.btnRelatorios.setObjectName("btnRelatorios")
        self.vboxRelatorios.addWidget(self.btnRelatorios)
        self.lblRelatorios = QtWidgets.QLabel(SelecaoModo)
        self.lblRelatorios.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRelatorios.setObjectName("lblRelatorios")
        self.vboxRelatorios.addWidget(self.lblRelatorios)
        self.layoutContent.addLayout(self.vboxRelatorios, 1, 0, 1, 1)
        self.vboxAdmin = QtWidgets.QVBoxLayout()
        self.vboxAdmin.setObjectName("vboxAdmin")
        self.btnPainelAdmin = QtWidgets.QPushButton(SelecaoModo)
        self.btnPainelAdmin.setObjectName("btnPainelAdmin")
        self.vboxAdmin.addWidget(self.btnPainelAdmin)
        self.lblPainelAdmin = QtWidgets.QLabel(SelecaoModo)
        self.lblPainelAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPainelAdmin.setObjectName("lblPainelAdmin")
        self.vboxAdmin.addWidget(self.lblPainelAdmin)
        self.layoutContent.addLayout(self.vboxAdmin, 1, 1, 1, 1)
        self.mainVLayout.addLayout(self.layoutContent)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainVLayout.addItem(spacerItem3)
        self.frameFooter = QtWidgets.QFrame(SelecaoModo)
        self.frameFooter.setMinimumSize(QtCore.QSize(0, 50))
        self.frameFooter.setObjectName("frameFooter")
        self.footerLayout = QtWidgets.QHBoxLayout(self.frameFooter)
        self.footerLayout.setObjectName("footerLayout")
        self.lblOperadorNome = QtWidgets.QLabel(self.frameFooter)
        self.lblOperadorNome.setStyleSheet("font-weight: bold; color: #40c840;")
        self.lblOperadorNome.setObjectName("lblOperadorNome")
        self.footerLayout.addWidget(self.lblOperadorNome)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footerLayout.addItem(spacerItem4)
        self.lblVersao = QtWidgets.QLabel(self.frameFooter)
        self.lblVersao.setObjectName("lblVersao")
        self.footerLayout.addWidget(self.lblVersao)
        self.mainVLayout.addWidget(self.frameFooter)

        self.retranslateUi(SelecaoModo)
        QtCore.QMetaObject.connectSlotsByName(SelecaoModo)

    def retranslateUi(self, SelecaoModo):
        _translate = QtCore.QCoreApplication.translate
        SelecaoModo.setWindowTitle(_translate("SelecaoModo", "CSPdv - Seleção de Modo"))
        self.lblTitulo.setText(_translate("SelecaoModo", "CLAUDINHA STORE - SELEÇÃO DE MÓDULO"))
        self.btnSairSessao.setText(_translate("SelecaoModo", "SAIR (ESC)"))
        self.btnFrenteCaixa.setToolTip(_translate("SelecaoModo", "[F1] Acesso ao PDV"))
        self.btnFrenteCaixa.setText(_translate("SelecaoModo", "FRENTE DE CAIXA"))
        self.lblFrenteCaixa.setText(_translate("SelecaoModo", "Vendas e Operações (F1)"))
        self.btnEstoque.setToolTip(_translate("SelecaoModo", "[F3] Gestão de Produtos"))
        self.btnEstoque.setText(_translate("SelecaoModo", "ESTOQUE"))
        self.lblEstoque.setText(_translate("SelecaoModo", "Produtos e Compras (F3)"))
        self.btnFinanceiro.setToolTip(_translate("SelecaoModo", "[F4] Fluxo de Caixa"))
        self.btnFinanceiro.setText(_translate("SelecaoModo", "FINANCEIRO"))
        self.lblFinanceiro.setText(_translate("SelecaoModo", "Contas e Fluxo (F4)"))
        self.btnRelatorios.setToolTip(_translate("SelecaoModo", "[F5] Indicadores de Venda"))
        self.btnRelatorios.setText(_translate("SelecaoModo", "RELATÓRIOS"))
        self.lblRelatorios.setText(_translate("SelecaoModo", "Desempenho e BI (F5)"))
        self.btnPainelAdmin.setToolTip(_translate("SelecaoModo", "[F2] Configurações do Sistema"))
        self.btnPainelAdmin.setText(_translate("SelecaoModo", "PAINEL ADMIN"))
        self.lblPainelAdmin.setText(_translate("SelecaoModo", "Configurações (F2)"))
        self.lblOperadorNome.setText(_translate("SelecaoModo", "OPERADOR: ---"))
        self.lblVersao.setText(_translate("SelecaoModo", "CSPdv v1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelecaoModo = QtWidgets.QWidget()
    ui = Ui_SelecaoModo()
    ui.setupUi(SelecaoModo)
    SelecaoModo.show()
    sys.exit(app.exec_())
