# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelecaoModo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelecaoModo(object):
    def setupUi(self, SelecaoModo):
        SelecaoModo.setObjectName("SelecaoModo")
        SelecaoModo.resize(1376, 744)
        SelecaoModo.setStyleSheet("\n"
"    QWidget {\n"
"     font-family: Arial;\n"
"     background-color: #0f2a4a;\n"
"    }\n"
"   ")
        self.mainVLayout = QtWidgets.QVBoxLayout(SelecaoModo)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(SelecaoModo)
        self.frameHeader.setMinimumHeight(72)
        self.frameHeader.setMaximumHeight(72)
        self.frameHeader.setStyleSheet("\n"
"       QFrame#frameHeader {\n"
"        background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"         stop:0 #1a5fa0, stop:1 #0f2a4a);\n"
"        border-bottom: 2px solid #3585c8;\n"
"       }\n"
"      ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(40, 10, 40, 10)
        self.headerHLayout.setSpacing(12)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setStyleSheet("\n"
"          color: white;\n"
"          font-size: 32px;\n"
"          font-weight: bold;\n"
"          letter-spacing: 1px;\n"
"         ")
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.frameOperadorInfo = QtWidgets.QFrame(self.frameHeader)
        self.frameOperadorInfo.setStyleSheet("\n"
"          QFrame#frameOperadorInfo {\n"
"           background-color: rgba(255,255,255,12);\n"
"           border: 1px solid rgba(255,255,255,25);\n"
"           border-radius: 6px;\n"
"          }\n"
"         ")
        self.frameOperadorInfo.setObjectName("frameOperadorInfo")
        self.operadorHL = QtWidgets.QHBoxLayout(self.frameOperadorInfo)
        self.operadorHL.setContentsMargins(14, 6, 14, 6)
        self.operadorHL.setSpacing(10)
        self.operadorHL.setObjectName("operadorHL")
        self.lblOperadorIcone = QtWidgets.QLabel(self.frameOperadorInfo)
        self.lblOperadorIcone.setStyleSheet("font-size:20px;")
        self.lblOperadorIcone.setObjectName("lblOperadorIcone")
        self.operadorHL.addWidget(self.lblOperadorIcone)
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setSpacing(1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblOperadorLabel = QtWidgets.QLabel(self.frameOperadorInfo)
        self.lblOperadorLabel.setStyleSheet("font-size:10px;color:#8ab0d0;")
        self.lblOperadorLabel.setObjectName("lblOperadorLabel")
        self.vboxlayout.addWidget(self.lblOperadorLabel)
        self.lblOperadorNome = QtWidgets.QLabel(self.frameOperadorInfo)
        self.lblOperadorNome.setStyleSheet("font-size:13px;font-weight:bold;color:white;")
        self.lblOperadorNome.setObjectName("lblOperadorNome")
        self.vboxlayout.addWidget(self.lblOperadorNome)
        self.operadorHL.addLayout(self.vboxlayout)
        self.headerHLayout.addWidget(self.frameOperadorInfo)
        self.btnSairSessao = QtWidgets.QPushButton(self.frameHeader)
        self.btnSairSessao.setMinimumSize(QtCore.QSize(90, 36))
        self.btnSairSessao.setStyleSheet("\n"
"          QPushButton {\n"
"           background-color: rgba(200,40,40,180);\n"
"           color: white;\n"
"           font-size: 12px;\n"
"           font-weight: bold;\n"
"           border: none;\n"
"           border-radius: 5px;\n"
"           padding: 5px 14px;\n"
"          }\n"
"          QPushButton:hover  { background-color: rgba(220,50,50,220); }\n"
"          QPushButton:pressed{ background-color: rgba(160,20,20,220); }\n"
"         ")
        self.btnSairSessao.setObjectName("btnSairSessao")
        self.headerHLayout.addWidget(self.btnSairSessao)
        self.mainVLayout.addWidget(self.frameHeader)
        self.widgetCentral = QtWidgets.QWidget(SelecaoModo)
        self.widgetCentral.setStyleSheet("QWidget#widgetCentral { background-color: transparent; }")
        self.widgetCentral.setObjectName("widgetCentral")
        self.centralVLayout = QtWidgets.QVBoxLayout(self.widgetCentral)
        self.centralVLayout.setContentsMargins(0, 0, 0, 0)
        self.centralVLayout.setSpacing(0)
        self.centralVLayout.setObjectName("centralVLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.centralVLayout.addItem(spacerItem1)
        self.titlesVLayout = QtWidgets.QVBoxLayout()
        self.titlesVLayout.setSpacing(6)
        self.titlesVLayout.setObjectName("titlesVLayout")
        self.lblTituloSelecao = QtWidgets.QLabel(self.widgetCentral)
        self.lblTituloSelecao.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloSelecao.setStyleSheet("\n"
"            color: white;\n"
"            font-size: 26px;\n"
"            font-weight: bold;\n"
"            letter-spacing: 1px;\n"
"           ")
        self.lblTituloSelecao.setObjectName("lblTituloSelecao")
        self.titlesVLayout.addWidget(self.lblTituloSelecao)
        self.lblSubtituloSelecao = QtWidgets.QLabel(self.widgetCentral)
        self.lblSubtituloSelecao.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtituloSelecao.setStyleSheet("color: #6a9fcc; font-size: 14px;")
        self.lblSubtituloSelecao.setObjectName("lblSubtituloSelecao")
        self.titlesVLayout.addWidget(self.lblSubtituloSelecao)
        self.centralVLayout.addLayout(self.titlesVLayout)
        spacerItem2 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.centralVLayout.addItem(spacerItem2)
        self.cardsHLayout = QtWidgets.QHBoxLayout()
        self.cardsHLayout.setContentsMargins(120, -1, 120, -1)
        self.cardsHLayout.setSpacing(40)
        self.cardsHLayout.setObjectName("cardsHLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cardsHLayout.addItem(spacerItem3)
        self.btnFrenteCaixa = QtWidgets.QPushButton(self.widgetCentral)
        self.btnFrenteCaixa.setText("")
        self.btnFrenteCaixa.setMinimumSize(QtCore.QSize(340, 320))
        self.btnFrenteCaixa.setMaximumSize(QtCore.QSize(400, 340))
        self.btnFrenteCaixa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFrenteCaixa.setStyleSheet("\n"
"            QPushButton {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #1a6020, stop:1 #0d3810);\n"
"             border: 2px solid #2a8a30;\n"
"             border-radius: 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #1e7025, stop:1 #104215);\n"
"             border: 2px solid #40bb48;\n"
"            }\n"
"            QPushButton:pressed {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #0d3810, stop:1 #061c08);\n"
"             border: 2px solid #2a8a30;\n"
"            }\n"
"           ")
        self.btnFrenteCaixa.setObjectName("btnFrenteCaixa")
        self.cardsHLayout.addWidget(self.btnFrenteCaixa)
        self.btnPainelAdmin = QtWidgets.QPushButton(self.widgetCentral)
        self.btnPainelAdmin.setText("")
        self.btnPainelAdmin.setMinimumSize(QtCore.QSize(340, 320))
        self.btnPainelAdmin.setMaximumSize(QtCore.QSize(400, 340))
        self.btnPainelAdmin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPainelAdmin.setStyleSheet("\n"
"            QPushButton {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #1a3a6a, stop:1 #0d1e38);\n"
"             border: 2px solid #2a5fa0;\n"
"             border-radius: 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #1e4478, stop:1 #102244);\n"
"             border: 2px solid #3585c8;\n"
"            }\n"
"            QPushButton:pressed {\n"
"             background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"              stop:0 #0d1e38, stop:1 #060e1c);\n"
"             border: 2px solid #2a5fa0;\n"
"            }\n"
"           ")
        self.btnPainelAdmin.setObjectName("btnPainelAdmin")
        self.cardsHLayout.addWidget(self.btnPainelAdmin)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cardsHLayout.addItem(spacerItem4)
        self.centralVLayout.addLayout(self.cardsHLayout)
        self.cardsContentHLayout = QtWidgets.QHBoxLayout()
        self.cardsContentHLayout.setContentsMargins(120, -1, 120, -1)
        self.cardsContentHLayout.setSpacing(40)
        self.cardsContentHLayout.setObjectName("cardsContentHLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cardsContentHLayout.addItem(spacerItem5)
        self.frameCardCaixa = QtWidgets.QFrame(self.widgetCentral)
        self.frameCardCaixa.setMinimumSize(QtCore.QSize(340, 320))
        self.frameCardCaixa.setMaximumSize(QtCore.QSize(400, 340))
        self.frameCardCaixa.setStyleSheet("\n"
"            QFrame#frameCardCaixa {\n"
"             background: transparent;\n"
"             border: none;\n"
"            }\n"
"           ")
        self.frameCardCaixa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frameCardCaixa.setObjectName("frameCardCaixa")
        self.cardCaixaVLayout = QtWidgets.QVBoxLayout(self.frameCardCaixa)
        self.cardCaixaVLayout.setContentsMargins(30, 36, 30, 36)
        self.cardCaixaVLayout.setSpacing(14)
        self.cardCaixaVLayout.setObjectName("cardCaixaVLayout")
        self.lblIconeCaixa = QtWidgets.QLabel(self.frameCardCaixa)
        self.lblIconeCaixa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconeCaixa.setStyleSheet("font-size:64px;")
        self.lblIconeCaixa.setObjectName("lblIconeCaixa")
        self.cardCaixaVLayout.addWidget(self.lblIconeCaixa)
        self.lblTituloCaixa = QtWidgets.QLabel(self.frameCardCaixa)
        self.lblTituloCaixa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloCaixa.setStyleSheet("\n"
"               color: #60e060;\n"
"               font-size: 22px;\n"
"               font-weight: bold;\n"
"              ")
        self.lblTituloCaixa.setObjectName("lblTituloCaixa")
        self.cardCaixaVLayout.addWidget(self.lblTituloCaixa)
        self.lblDescCaixa = QtWidgets.QLabel(self.frameCardCaixa)
        self.lblDescCaixa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDescCaixa.setWordWrap(True)
        self.lblDescCaixa.setStyleSheet("color: #88c888; font-size: 13px; line-height: 1.5;")
        self.lblDescCaixa.setObjectName("lblDescCaixa")
        self.cardCaixaVLayout.addWidget(self.lblDescCaixa)
        spacerItem6 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardCaixaVLayout.addItem(spacerItem6)
        self.frameTeclaCaixa = QtWidgets.QFrame(self.frameCardCaixa)
        self.frameTeclaCaixa.setStyleSheet("\n"
"               QFrame#frameTeclaCaixa {\n"
"                background-color: rgba(40,140,40,60);\n"
"                border: 1px solid rgba(60,180,60,80);\n"
"                border-radius: 6px;\n"
"               }\n"
"              ")
        self.frameTeclaCaixa.setObjectName("frameTeclaCaixa")
        self.teclaHL = QtWidgets.QHBoxLayout(self.frameTeclaCaixa)
        self.teclaHL.setContentsMargins(10, 6, 10, 6)
        self.teclaHL.setObjectName("teclaHL")
        spacerItem7 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.teclaHL.addItem(spacerItem7)
        self.lblAtalhoCaixa = QtWidgets.QLabel(self.frameTeclaCaixa)
        self.lblAtalhoCaixa.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAtalhoCaixa.setStyleSheet("color:#60c860;font-size:11px;")
        self.lblAtalhoCaixa.setObjectName("lblAtalhoCaixa")
        self.teclaHL.addWidget(self.lblAtalhoCaixa)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.teclaHL.addItem(spacerItem8)
        self.cardCaixaVLayout.addWidget(self.frameTeclaCaixa)
        self.cardsContentHLayout.addWidget(self.frameCardCaixa)
        self.frameCardAdmin = QtWidgets.QFrame(self.widgetCentral)
        self.frameCardAdmin.setMinimumSize(QtCore.QSize(340, 320))
        self.frameCardAdmin.setMaximumSize(QtCore.QSize(400, 340))
        self.frameCardAdmin.setStyleSheet("\n"
"            QFrame#frameCardAdmin {\n"
"             background: transparent;\n"
"             border: none;\n"
"            }\n"
"           ")
        self.frameCardAdmin.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frameCardAdmin.setObjectName("frameCardAdmin")
        self.cardAdminVLayout = QtWidgets.QVBoxLayout(self.frameCardAdmin)
        self.cardAdminVLayout.setContentsMargins(30, 36, 30, 36)
        self.cardAdminVLayout.setSpacing(14)
        self.cardAdminVLayout.setObjectName("cardAdminVLayout")
        self.lblIconeAdmin = QtWidgets.QLabel(self.frameCardAdmin)
        self.lblIconeAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconeAdmin.setStyleSheet("font-size:64px;color:#4a90d4;")
        self.lblIconeAdmin.setObjectName("lblIconeAdmin")
        self.cardAdminVLayout.addWidget(self.lblIconeAdmin)
        self.lblTituloAdmin = QtWidgets.QLabel(self.frameCardAdmin)
        self.lblTituloAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTituloAdmin.setStyleSheet("\n"
"               color: #60a8e0;\n"
"               font-size: 22px;\n"
"               font-weight: bold;\n"
"              ")
        self.lblTituloAdmin.setObjectName("lblTituloAdmin")
        self.cardAdminVLayout.addWidget(self.lblTituloAdmin)
        self.lblDescAdmin = QtWidgets.QLabel(self.frameCardAdmin)
        self.lblDescAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDescAdmin.setWordWrap(True)
        self.lblDescAdmin.setStyleSheet("color: #6090b8; font-size: 13px; line-height: 1.5;")
        self.lblDescAdmin.setObjectName("lblDescAdmin")
        self.cardAdminVLayout.addWidget(self.lblDescAdmin)
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cardAdminVLayout.addItem(spacerItem9)
        self.frameTeclaAdmin = QtWidgets.QFrame(self.frameCardAdmin)
        self.frameTeclaAdmin.setStyleSheet("\n"
"               QFrame#frameTeclaAdmin {\n"
"                background-color: rgba(40,80,160,60);\n"
"                border: 1px solid rgba(60,110,200,80);\n"
"                border-radius: 6px;\n"
"               }\n"
"              ")
        self.frameTeclaAdmin.setObjectName("frameTeclaAdmin")
        self.teclaAdminHL = QtWidgets.QHBoxLayout(self.frameTeclaAdmin)
        self.teclaAdminHL.setContentsMargins(10, 6, 10, 6)
        self.teclaAdminHL.setObjectName("teclaAdminHL")
        spacerItem10 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.teclaAdminHL.addItem(spacerItem10)
        self.lblAtalhoAdmin = QtWidgets.QLabel(self.frameTeclaAdmin)
        self.lblAtalhoAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAtalhoAdmin.setStyleSheet("color:#6090b8;font-size:11px;")
        self.lblAtalhoAdmin.setObjectName("lblAtalhoAdmin")
        self.teclaAdminHL.addWidget(self.lblAtalhoAdmin)
        spacerItem11 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.teclaAdminHL.addItem(spacerItem11)
        self.cardAdminVLayout.addWidget(self.frameTeclaAdmin)
        self.cardsContentHLayout.addWidget(self.frameCardAdmin)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cardsContentHLayout.addItem(spacerItem12)
        self.centralVLayout.addLayout(self.cardsContentHLayout)
        spacerItem13 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.centralVLayout.addItem(spacerItem13)
        self.mainVLayout.addWidget(self.widgetCentral)
        self.frameStatusBar = QtWidgets.QFrame(SelecaoModo)
        self.frameStatusBar.setMinimumHeight(36)
        self.frameStatusBar.setMaximumHeight(36)
        self.frameStatusBar.setStyleSheet("\n"
"       QFrame#frameStatusBar {\n"
"        background-color: #081828;\n"
"        border-top: 1px solid #1a3a5a;\n"
"       }\n"
"      ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusHLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusHLayout.setContentsMargins(20, 0, 20, 0)
        self.statusHLayout.setSpacing(20)
        self.statusHLayout.setObjectName("statusHLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setStyleSheet("color:#40c840;font-size:11px;font-weight:bold;")
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusHLayout.addWidget(self.lblStatusSistema)
        self.frameSepStatus = QtWidgets.QFrame(self.frameStatusBar)
        self.frameSepStatus.setMinimumWidth(1)
        self.frameSepStatus.setMaximumWidth(1)
        self.frameSepStatus.setStyleSheet("background-color:#2a3a4a;")
        self.frameSepStatus.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepStatus.setObjectName("frameSepStatus")
        self.statusHLayout.addWidget(self.frameSepStatus)
        self.lblDataHora = QtWidgets.QLabel(self.frameStatusBar)
        self.lblDataHora.setStyleSheet("color:#4a6a8a;font-size:11px;")
        self.lblDataHora.setObjectName("lblDataHora")
        self.statusHLayout.addWidget(self.lblDataHora)
        spacerItem14 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem14)
        self.lblVersao = QtWidgets.QLabel(self.frameStatusBar)
        self.lblVersao.setStyleSheet("color:#2a4a6a;font-size:11px;")
        self.lblVersao.setObjectName("lblVersao")
        self.statusHLayout.addWidget(self.lblVersao)
        self.mainVLayout.addWidget(self.frameStatusBar)

        self.retranslateUi(SelecaoModo)
        QtCore.QMetaObject.connectSlotsByName(SelecaoModo)

    def retranslateUi(self, SelecaoModo):
        _translate = QtCore.QCoreApplication.translate
        SelecaoModo.setWindowTitle(_translate("SelecaoModo", "CSPdv - Selecionar Modo"))
        self.lblLogo.setText(_translate("SelecaoModo", "CSPdv"))
        self.lblOperadorIcone.setText(_translate("SelecaoModo", "👤"))
        self.lblOperadorLabel.setText(_translate("SelecaoModo", "Operador logado"))
        self.lblOperadorNome.setText(_translate("SelecaoModo", "ADMIN"))
        self.btnSairSessao.setText(_translate("SelecaoModo", "✕  Sair"))
        self.lblTituloSelecao.setText(_translate("SelecaoModo", "Como deseja continuar?"))
        self.lblSubtituloSelecao.setText(_translate("SelecaoModo", "Selecione o modo de operação para esta sessão"))
        self.lblIconeCaixa.setText(_translate("SelecaoModo", "💸"))
        self.lblTituloCaixa.setText(_translate("SelecaoModo", "Frente de Caixa"))
        self.lblDescCaixa.setText(_translate("SelecaoModo", "Acesso direto ao PDV para\n"
"realizar vendas, pré-vendas\n"
"e pagamentos"))
        self.lblAtalhoCaixa.setText(_translate("SelecaoModo", "Pressione   F1   para abrir"))
        self.lblIconeAdmin.setText(_translate("SelecaoModo", "⚙"))
        self.lblTituloAdmin.setText(_translate("SelecaoModo", "Painel Administrativo"))
        self.lblDescAdmin.setText(_translate("SelecaoModo", "Acesso ao painel de gestão\n"
"para gerenciar produtos, clientes,\n"
"usuários e relatórios"))
        self.lblAtalhoAdmin.setText(_translate("SelecaoModo", "Pressione   F2   para abrir"))
        self.lblStatusSistema.setText(_translate("SelecaoModo", "●  Sistema Online"))
        self.lblDataHora.setText(_translate("SelecaoModo", "--/--/----  --:--:--"))
        self.lblVersao.setText(_translate("SelecaoModo", "CSPdv  v1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelecaoModo = QtWidgets.QWidget()
    ui = Ui_SelecaoModo()
    ui.setupUi(SelecaoModo)
    SelecaoModo.show()
    sys.exit(app.exec_())
