# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaDeLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaDeLogin(object):
    def setupUi(self, TelaDeLogin):
        TelaDeLogin.setObjectName("TelaDeLogin")
        TelaDeLogin.resize(460, 460)
        TelaDeLogin.setModal(True)
        TelaDeLogin.setStyleSheet("\n"
"    QDialog {\n"
"     background-color: #0f2030;\n"
"     font-family: Arial;\n"
"    }\n"
"   ")
        self.mainVLayout = QtWidgets.QVBoxLayout(TelaDeLogin)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameTop = QtWidgets.QFrame(TelaDeLogin)
        self.frameTop.setMinimumHeight(130)
        self.frameTop.setMaximumHeight(130)
        self.frameTop.setStyleSheet("\n"
"       QFrame#frameTop {\n"
"        background: qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"         stop:0 #1a3a5a, stop:1 #0a1828);\n"
"        border-bottom: 2px solid #3585c8;\n"
"       }\n"
"      ")
        self.frameTop.setObjectName("frameTop")
        self.topVLayout = QtWidgets.QVBoxLayout(self.frameTop)
        self.topVLayout.setContentsMargins(0, 24, 0, 18)
        self.topVLayout.setSpacing(4)
        self.topVLayout.setObjectName("topVLayout")
        self.labelLogo = QtWidgets.QLabel(self.frameTop)
        self.labelLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogo.setStyleSheet("color:white;font-size:40px;font-weight:bold;letter-spacing:2px;")
        self.labelLogo.setObjectName("labelLogo")
        self.topVLayout.addWidget(self.labelLogo)
        self.labelSubtitulo = QtWidgets.QLabel(self.frameTop)
        self.labelSubtitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitulo.setStyleSheet("color:#3585c8;font-size:11px;letter-spacing:1px;")
        self.labelSubtitulo.setObjectName("labelSubtitulo")
        self.topVLayout.addWidget(self.labelSubtitulo)
        self.labelVersao = QtWidgets.QLabel(self.frameTop)
        self.labelVersao.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVersao.setStyleSheet("color:#1a3a5a;font-size:10px;")
        self.labelVersao.setObjectName("labelVersao")
        self.topVLayout.addWidget(self.labelVersao)
        self.mainVLayout.addWidget(self.frameTop)
        self.frameForm = QtWidgets.QFrame(TelaDeLogin)
        self.frameForm.setStyleSheet("QFrame#frameForm { background-color: #0f2030; }")
        self.frameForm.setObjectName("frameForm")
        self.formVLayout = QtWidgets.QVBoxLayout(self.frameForm)
        self.formVLayout.setContentsMargins(44, 28, 44, 10)
        self.formVLayout.setSpacing(12)
        self.formVLayout.setObjectName("formVLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setSpacing(5)
        self.vboxlayout.setObjectName("vboxlayout")
        self.labelLogin = QtWidgets.QLabel(self.frameForm)
        self.labelLogin.setStyleSheet("font-size:11px;font-weight:bold;color:#3a6a8a;letter-spacing:1px;")
        self.labelLogin.setObjectName("labelLogin")
        self.vboxlayout.addWidget(self.labelLogin)
        self.lineEditLogin = QtWidgets.QLineEdit(self.frameForm)
        self.lineEditLogin.setMinimumHeight(42)
        self.lineEditLogin.setStyleSheet("\n"
"            QLineEdit{background-color:#0d2030;border:2px solid #1a4060;border-radius:6px;font-size:14px;color:#c0dff4;padding:4px 12px;selection-background-color:#3585c8;selection-color:white;}\n"
"            QLineEdit:focus{border:2px solid #3585c8;background-color:#0f2840;}\n"
"            QLineEdit:hover:!focus{border:2px solid #2a5a80;}\n"
"           ")
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.vboxlayout.addWidget(self.lineEditLogin)
        self.formVLayout.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setSpacing(5)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.labelSenha = QtWidgets.QLabel(self.frameForm)
        self.labelSenha.setStyleSheet("font-size:11px;font-weight:bold;color:#3a6a8a;letter-spacing:1px;")
        self.labelSenha.setObjectName("labelSenha")
        self.vboxlayout1.addWidget(self.labelSenha)
        self.lineEditSenha = QtWidgets.QLineEdit(self.frameForm)
        self.lineEditSenha.setMinimumHeight(42)
        self.lineEditSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditSenha.setStyleSheet("\n"
"            QLineEdit{background-color:#0d2030;border:2px solid #1a4060;border-radius:6px;font-size:14px;color:#c0dff4;padding:4px 12px;selection-background-color:#3585c8;selection-color:white;}\n"
"            QLineEdit:focus{border:2px solid #3585c8;background-color:#0f2840;}\n"
"            QLineEdit:hover:!focus{border:2px solid #2a5a80;}\n"
"           ")
        self.lineEditSenha.setObjectName("lineEditSenha")
        self.vboxlayout1.addWidget(self.lineEditSenha)
        self.formVLayout.addLayout(self.vboxlayout1)
        self.labelErro = QtWidgets.QLabel(self.frameForm)
        self.labelErro.setVisible(False)
        self.labelErro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelErro.setStyleSheet("\n"
"          QLabel {\n"
"           background-color: rgba(180,30,30,40);\n"
"           border: 1px solid rgba(180,30,30,80);\n"
"           border-radius: 4px;\n"
"           font-size: 12px;\n"
"           font-weight: bold;\n"
"           color: #ff8080;\n"
"           padding: 6px 10px;\n"
"          }\n"
"         ")
        self.labelErro.setObjectName("labelErro")
        self.formVLayout.addWidget(self.labelErro)
        self.btnLogar = QtWidgets.QPushButton(self.frameForm)
        self.btnLogar.setDefault(True)
        self.btnLogar.setMinimumHeight(48)
        self.btnLogar.setStyleSheet("\n"
"          QPushButton{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #2a7ad8,stop:1 #1a5ab8);color:white;font-size:15px;font-weight:bold;border:none;border-radius:7px;padding:8px;}\n"
"          QPushButton:hover{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #3a88e8,stop:1 #2a68c8);}\n"
"          QPushButton:pressed{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #1a5098,stop:1 #0e3880);}\n"
"         ")
        self.btnLogar.setObjectName("btnLogar")
        self.formVLayout.addWidget(self.btnLogar)
        self.btnCancelar = QtWidgets.QPushButton(self.frameForm)
        self.btnCancelar.setMinimumHeight(34)
        self.btnCancelar.setStyleSheet("\n"
"          QPushButton{background-color:transparent;color:#2a5a7a;font-size:12px;border:1px solid #1a3a5a;border-radius:5px;padding:4px;}\n"
"          QPushButton:hover{background-color:rgba(255,255,255,6);color:#4a8ab0;border-color:#2a5a80;}\n"
"          QPushButton:pressed{background-color:rgba(255,255,255,10);}\n"
"         ")
        self.btnCancelar.setObjectName("btnCancelar")
        self.formVLayout.addWidget(self.btnCancelar)
        self.mainVLayout.addWidget(self.frameForm)
        self.frameRodape = QtWidgets.QFrame(TelaDeLogin)
        self.frameRodape.setMinimumHeight(52)
        self.frameRodape.setMaximumHeight(52)
        self.frameRodape.setStyleSheet("\n"
"      QFrame#frameRodape {\n"
"       background-color: #081828;\n"
"       border-top: 1px solid #1a3a5a;\n"
"      }\n"
"     ")
        self.frameRodape.setObjectName("frameRodape")
        self.rodapeVLayout = QtWidgets.QVBoxLayout(self.frameRodape)
        self.rodapeVLayout.setContentsMargins(20, 8, 20, 8)
        self.rodapeVLayout.setSpacing(4)
        self.rodapeVLayout.setObjectName("rodapeVLayout")
        self.labelCarregando = QtWidgets.QLabel(self.frameRodape)
        self.labelCarregando.setStyleSheet("color:#2a4a6a;font-size:10px;")
        self.labelCarregando.setObjectName("labelCarregando")
        self.rodapeVLayout.addWidget(self.labelCarregando)
        self.progressBarCarregando = QtWidgets.QProgressBar(self.frameRodape)
        self.progressBarCarregando.setMinimumHeight(6)
        self.progressBarCarregando.setMaximumHeight(6)
        self.progressBarCarregando.setProperty("value", 0)
        self.progressBarCarregando.setTextVisible(False)
        self.progressBarCarregando.setStyleSheet("\n"
"         QProgressBar{border:none;border-radius:3px;background-color:#0d2030;}\n"
"         QProgressBar::chunk{background:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #1a5fa0,stop:1 #3585c8);border-radius:3px;}\n"
"        ")
        self.progressBarCarregando.setObjectName("progressBarCarregando")
        self.rodapeVLayout.addWidget(self.progressBarCarregando)
        self.mainVLayout.addWidget(self.frameRodape)

        self.retranslateUi(TelaDeLogin)
        self.btnCancelar.clicked.connect(TelaDeLogin.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TelaDeLogin)

    def retranslateUi(self, TelaDeLogin):
        _translate = QtCore.QCoreApplication.translate
        TelaDeLogin.setWindowTitle(_translate("TelaDeLogin", "CSPdv - Login"))
        self.labelLogo.setText(_translate("TelaDeLogin", "CSPdv"))
        self.labelSubtitulo.setText(_translate("TelaDeLogin", "Sistema de Ponto de Venda"))
        self.labelVersao.setText(_translate("TelaDeLogin", "v1.0.0"))
        self.labelLogin.setText(_translate("TelaDeLogin", "Usuário"))
        self.lineEditLogin.setPlaceholderText(_translate("TelaDeLogin", "Nome de usuário"))
        self.labelSenha.setText(_translate("TelaDeLogin", "Senha"))
        self.lineEditSenha.setPlaceholderText(_translate("TelaDeLogin", "Senha"))
        self.labelErro.setText(_translate("TelaDeLogin", "●  Usuário ou senha incorretos."))
        self.btnLogar.setText(_translate("TelaDeLogin", "Entrar"))
        self.btnLogar.setShortcut(_translate("TelaDeLogin", "Return"))
        self.btnCancelar.setText(_translate("TelaDeLogin", "Cancelar"))
        self.btnCancelar.setShortcut(_translate("TelaDeLogin", "Escape"))
        self.labelCarregando.setText(_translate("TelaDeLogin", "Pronto."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaDeLogin = QtWidgets.QDialog()
    ui = Ui_TelaDeLogin()
    ui.setupUi(TelaDeLogin)
    TelaDeLogin.show()
    sys.exit(app.exec_())
