# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro_produto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroProduto(object):
    def setupUi(self, CadastroProduto):
        CadastroProduto.setObjectName("CadastroProduto")
        CadastroProduto.resize(1376, 860)
        CadastroProduto.setStyleSheet("QWidget { font-family: Arial; }")
        self.mainVLayout = QtWidgets.QVBoxLayout(CadastroProduto)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(CadastroProduto)
        self.frameHeader.setStyleSheet("\n"
"       QFrame#frameHeader {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"         stop:0 #3585c8, stop:1 #1a5fa0);\n"
"       }\n"
"      ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(14, 8, 14, 8)
        self.headerHLayout.setSpacing(12)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setStyleSheet("color: white; font-size: 28px; font-weight: bold;")
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblBadge = QtWidgets.QLabel(self.frameHeader)
        self.lblBadge.setStyleSheet("\n"
"          QLabel {\n"
"           background-color: rgba(255,255,255,30);\n"
"           color: #ffe080;\n"
"           font-size: 12px;\n"
"           font-weight: bold;\n"
"           border: 1px solid rgba(255,255,255,60);\n"
"           border-radius: 4px;\n"
"           padding: 3px 10px;\n"
"          }\n"
"         ")
        self.lblBadge.setObjectName("lblBadge")
        self.headerHLayout.addWidget(self.lblBadge)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.btnVoltar = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltar.setMinimumSize(QtCore.QSize(90, 32))
        self.btnVoltar.setStyleSheet("\n"
"          QPushButton {\n"
"           background-color: rgba(255,255,255,25);\n"
"           color: white;\n"
"           font-size: 11px;\n"
"           font-weight: bold;\n"
"           border: 1px solid rgba(255,255,255,60);\n"
"           border-radius: 4px;\n"
"           padding: 4px 12px;\n"
"          }\n"
"          QPushButton:hover  { background-color: rgba(255,255,255,40); }\n"
"          QPushButton:pressed{ background-color: rgba(255,255,255,15); }\n"
"         ")
        self.btnVoltar.setObjectName("btnVoltar")
        self.headerHLayout.addWidget(self.btnVoltar)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameTabBar = QtWidgets.QFrame(CadastroProduto)
        self.frameTabBar.setStyleSheet("QFrame#frameTabBar { background-color: #9dbfda; }")
        self.frameTabBar.setObjectName("frameTabBar")
        self.tabHLayout = QtWidgets.QHBoxLayout(self.frameTabBar)
        self.tabHLayout.setContentsMargins(10, 3, 0, 0)
        self.tabHLayout.setObjectName("tabHLayout")
        self.lblTabCadProduto = QtWidgets.QLabel(self.frameTabBar)
        self.lblTabCadProduto.setStyleSheet("\n"
"          QLabel {\n"
"           background-color: #c4d8e8;\n"
"           border: 1px solid #8aaabb;\n"
"           border-bottom: none;\n"
"           padding: 1px 14px;\n"
"           font-size: 12px;\n"
"          }\n"
"         ")
        self.lblTabCadProduto.setObjectName("lblTabCadProduto")
        self.tabHLayout.addWidget(self.lblTabCadProduto)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tabHLayout.addItem(spacerItem1)
        self.mainVLayout.addWidget(self.frameTabBar)
        self.conteudoHLayout = QtWidgets.QHBoxLayout()
        self.conteudoHLayout.setContentsMargins(14, 12, 14, 12)
        self.conteudoHLayout.setSpacing(12)
        self.conteudoHLayout.setObjectName("conteudoHLayout")
        self.frameFormulario = QtWidgets.QFrame(CadastroProduto)
        self.frameFormulario.setStyleSheet("\n"
"          QFrame#frameFormulario {\n"
"           background-color: #ffffff;\n"
"           border: 1px solid #a8c4d8;\n"
"           border-radius: 6px;\n"
"          }\n"
"         ")
        self.frameFormulario.setObjectName("frameFormulario")
        self.formularioVLayout = QtWidgets.QVBoxLayout(self.frameFormulario)
        self.formularioVLayout.setContentsMargins(0, 0, 0, 0)
        self.formularioVLayout.setSpacing(0)
        self.formularioVLayout.setObjectName("formularioVLayout")
        self.lblFormTitle = QtWidgets.QLabel(self.frameFormulario)
        self.lblFormTitle.setStyleSheet("\n"
"             QLabel {\n"
"              background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"               stop:0 #3585c8, stop:1 #1a5fa0);\n"
"              color: white;\n"
"              font-size: 13px;\n"
"              font-weight: bold;\n"
"              padding: 6px 14px;\n"
"              border-top-left-radius: 6px;\n"
"              border-top-right-radius: 6px;\n"
"             }\n"
"            ")
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formularioVLayout.addWidget(self.lblFormTitle)
        self.frameCampos = QtWidgets.QFrame(self.frameFormulario)
        self.frameCampos.setStyleSheet("QFrame#frameCampos { background-color: #ffffff; }")
        self.frameCampos.setObjectName("frameCampos")
        self.camposVLayout = QtWidgets.QVBoxLayout(self.frameCampos)
        self.camposVLayout.setContentsMargins(16, 14, 16, 14)
        self.camposVLayout.setSpacing(10)
        self.camposVLayout.setObjectName("camposVLayout")
        self.row1HLayout = QtWidgets.QHBoxLayout()
        self.row1HLayout.setSpacing(12)
        self.row1HLayout.setObjectName("row1HLayout")
        self.colCodigoVLayout = QtWidgets.QVBoxLayout()
        self.colCodigoVLayout.setSpacing(3)
        self.colCodigoVLayout.setObjectName("colCodigoVLayout")
        self.lblCodigo = QtWidgets.QLabel(self.frameCampos)
        self.lblCodigo.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblCodigo.setObjectName("lblCodigo")
        self.colCodigoVLayout.addWidget(self.lblCodigo)
        self.lineEditCodigo = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCodigo.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #f0f6fc;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; background-color: #ffffff; }\n"
"                   ")
        self.lineEditCodigo.setReadOnly(True)
        self.lineEditCodigo.setObjectName("lineEditCodigo")
        self.colCodigoVLayout.addWidget(self.lineEditCodigo)
        self.row1HLayout.addLayout(self.colCodigoVLayout)
        self.colCodigoBarrasVLayout = QtWidgets.QVBoxLayout()
        self.colCodigoBarrasVLayout.setSpacing(3)
        self.colCodigoBarrasVLayout.setObjectName("colCodigoBarrasVLayout")
        self.lblCodigoBarras = QtWidgets.QLabel(self.frameCampos)
        self.lblCodigoBarras.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblCodigoBarras.setObjectName("lblCodigoBarras")
        self.colCodigoBarrasVLayout.addWidget(self.lblCodigoBarras)
        self.lineEditCodigoBarras = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCodigoBarras.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditCodigoBarras.setObjectName("lineEditCodigoBarras")
        self.colCodigoBarrasVLayout.addWidget(self.lineEditCodigoBarras)
        self.row1HLayout.addLayout(self.colCodigoBarrasVLayout)
        self.camposVLayout.addLayout(self.row1HLayout)
        self.colDescVLayout = QtWidgets.QVBoxLayout()
        self.colDescVLayout.setSpacing(3)
        self.colDescVLayout.setObjectName("colDescVLayout")
        self.lblDescricao = QtWidgets.QLabel(self.frameCampos)
        self.lblDescricao.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblDescricao.setObjectName("lblDescricao")
        self.colDescVLayout.addWidget(self.lblDescricao)
        self.lineEditDescricao = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditDescricao.setStyleSheet("\n"
"                  QLineEdit {\n"
"                   background-color: #ffffff;\n"
"                   border: 2px solid #a8c4d8;\n"
"                   border-radius: 4px;\n"
"                   font-size: 13px;\n"
"                   color: #1a3a5c;\n"
"                   padding: 3px 8px;\n"
"                  }\n"
"                  QLineEdit:focus { border-color: #3585c8; }\n"
"                 ")
        self.lineEditDescricao.setObjectName("lineEditDescricao")
        self.colDescVLayout.addWidget(self.lineEditDescricao)
        self.camposVLayout.addLayout(self.colDescVLayout)
        self.row2HLayout = QtWidgets.QHBoxLayout()
        self.row2HLayout.setSpacing(12)
        self.row2HLayout.setObjectName("row2HLayout")
        self.colCategoriaVLayout = QtWidgets.QVBoxLayout()
        self.colCategoriaVLayout.setSpacing(3)
        self.colCategoriaVLayout.setObjectName("colCategoriaVLayout")
        self.lblCategoria = QtWidgets.QLabel(self.frameCampos)
        self.lblCategoria.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblCategoria.setObjectName("lblCategoria")
        self.colCategoriaVLayout.addWidget(self.lblCategoria)
        self.comboCategoria = QtWidgets.QComboBox(self.frameCampos)
        self.comboCategoria.setStyleSheet("\n"
"                    QComboBox {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QComboBox:focus { border-color: #3585c8; }\n"
"                    QComboBox::drop-down {\n"
"                     border: none;\n"
"                     width: 24px;\n"
"                    }\n"
"                    QComboBox QAbstractItemView {\n"
"                     background-color: #ffffff;\n"
"                     border: 1px solid #a8c4d8;\n"
"                     selection-background-color: #3585c8;\n"
"                     selection-color: white;\n"
"                     font-size: 13px;\n"
"                    }\n"
"                   ")
        self.comboCategoria.setObjectName("comboCategoria")
        self.comboCategoria.addItem("")
        self.colCategoriaVLayout.addWidget(self.comboCategoria)
        self.row2HLayout.addLayout(self.colCategoriaVLayout)
        self.colUnidadeVLayout = QtWidgets.QVBoxLayout()
        self.colUnidadeVLayout.setSpacing(3)
        self.colUnidadeVLayout.setObjectName("colUnidadeVLayout")
        self.lblUnidade = QtWidgets.QLabel(self.frameCampos)
        self.lblUnidade.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblUnidade.setObjectName("lblUnidade")
        self.colUnidadeVLayout.addWidget(self.lblUnidade)
        self.comboMarca = QtWidgets.QComboBox(self.frameCampos)
        self.comboMarca.setStyleSheet("\n"
"                    QComboBox {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QComboBox:focus { border-color: #3585c8; }\n"
"                    QComboBox::drop-down { border: none; width: 24px; }\n"
"                    QComboBox QAbstractItemView {\n"
"                     background-color: #ffffff;\n"
"                     border: 1px solid #a8c4d8;\n"
"                     selection-background-color: #3585c8;\n"
"                     selection-color: white;\n"
"                     font-size: 13px;\n"
"                    }\n"
"                   ")
        self.comboMarca.setObjectName("comboMarca")
        self.comboMarca.addItem("")
        self.colUnidadeVLayout.addWidget(self.comboMarca)
        self.row2HLayout.addLayout(self.colUnidadeVLayout)
        self.camposVLayout.addLayout(self.row2HLayout)
        self.colFornVLayout = QtWidgets.QVBoxLayout()
        self.colFornVLayout.setSpacing(3)
        self.colFornVLayout.setObjectName("colFornVLayout")
        self.lblD = QtWidgets.QLabel(self.frameCampos)
        self.lblD.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblD.setObjectName("lblD")
        self.colFornVLayout.addWidget(self.lblD)
        self.comboBox = QtWidgets.QComboBox(self.frameCampos)
        self.comboBox.setStyleSheet("\n"
"                    QComboBox {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QComboBox:focus { border-color: #3585c8; }\n"
"                    QComboBox::drop-down {\n"
"                     border: none;\n"
"                     width: 24px;\n"
"                    }\n"
"                    QComboBox QAbstractItemView {\n"
"                     background-color: #ffffff;\n"
"                     border: 1px solid #a8c4d8;\n"
"                     selection-background-color: #3585c8;\n"
"                     selection-color: white;\n"
"                     font-size: 13px;\n"
"                    }\n"
"                   ")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.colFornVLayout.addWidget(self.comboBox)
        self.camposVLayout.addLayout(self.colFornVLayout)
        self.rowFiscalHLayout = QtWidgets.QHBoxLayout()
        self.rowFiscalHLayout.setSpacing(12)
        self.rowFiscalHLayout.setObjectName("rowFiscalHLayout")
        self.colNcmVLayout = QtWidgets.QVBoxLayout()
        self.colNcmVLayout.setSpacing(3)
        self.colNcmVLayout.setObjectName("colNcmVLayout")
        self.lblNcm = QtWidgets.QLabel(self.frameCampos)
        self.lblNcm.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblNcm.setObjectName("lblNcm")
        self.colNcmVLayout.addWidget(self.lblNcm)
        self.lineEditNcm = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditNcm.setMaxLength(8)
        self.lineEditNcm.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditNcm.setObjectName("lineEditNcm")
        self.colNcmVLayout.addWidget(self.lineEditNcm)
        self.rowFiscalHLayout.addLayout(self.colNcmVLayout)
        self.colCestVLayout = QtWidgets.QVBoxLayout()
        self.colCestVLayout.setSpacing(3)
        self.colCestVLayout.setObjectName("colCestVLayout")
        self.lblCest = QtWidgets.QLabel(self.frameCampos)
        self.lblCest.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblCest.setObjectName("lblCest")
        self.colCestVLayout.addWidget(self.lblCest)
        self.lineEditCest = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCest.setMaxLength(7)
        self.lineEditCest.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditCest.setObjectName("lineEditCest")
        self.colCestVLayout.addWidget(self.lineEditCest)
        self.rowFiscalHLayout.addLayout(self.colCestVLayout)
        self.colUnidadeComercialVLayout = QtWidgets.QVBoxLayout()
        self.colUnidadeComercialVLayout.setSpacing(3)
        self.colUnidadeComercialVLayout.setObjectName("colUnidadeComercialVLayout")
        self.lblUnidadeComercial = QtWidgets.QLabel(self.frameCampos)
        self.lblUnidadeComercial.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblUnidadeComercial.setObjectName("lblUnidadeComercial")
        self.colUnidadeComercialVLayout.addWidget(self.lblUnidadeComercial)
        self.comboUnidade = QtWidgets.QComboBox(self.frameCampos)
        self.comboUnidade.setStyleSheet("\n"
"                    QComboBox {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QComboBox:focus { border-color: #3585c8; }\n"
"                    QComboBox::drop-down { border: none; width: 24px; }\n"
"                    QComboBox QAbstractItemView {\n"
"                     background-color: #ffffff;\n"
"                     border: 1px solid #a8c4d8;\n"
"                     selection-background-color: #3585c8;\n"
"                     selection-color: white;\n"
"                     font-size: 13px;\n"
"                    }\n"
"                   ")
        self.comboUnidade.setObjectName("comboUnidade")
        self.comboUnidade.addItem("")
        self.colUnidadeComercialVLayout.addWidget(self.comboUnidade)
        self.rowFiscalHLayout.addLayout(self.colUnidadeComercialVLayout)
        self.colUnidadeTribVLayout = QtWidgets.QVBoxLayout()
        self.colUnidadeTribVLayout.setSpacing(3)
        self.colUnidadeTribVLayout.setObjectName("colUnidadeTribVLayout")
        self.lblUnidadeTributavel = QtWidgets.QLabel(self.frameCampos)
        self.lblUnidadeTributavel.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblUnidadeTributavel.setObjectName("lblUnidadeTributavel")
        self.colUnidadeTribVLayout.addWidget(self.lblUnidadeTributavel)
        self.comboUnidadeTributavel = QtWidgets.QComboBox(self.frameCampos)
        self.comboUnidadeTributavel.setStyleSheet("\n"
"                    QComboBox {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QComboBox:focus { border-color: #3585c8; }\n"
"                    QComboBox::drop-down { border: none; width: 24px; }\n"
"                    QComboBox QAbstractItemView {\n"
"                     background-color: #ffffff;\n"
"                     border: 1px solid #a8c4d8;\n"
"                     selection-background-color: #3585c8;\n"
"                     selection-color: white;\n"
"                     font-size: 13px;\n"
"                    }\n"
"                   ")
        self.comboUnidadeTributavel.setObjectName("comboUnidadeTributavel")
        self.comboUnidadeTributavel.addItem("")
        self.colUnidadeTribVLayout.addWidget(self.comboUnidadeTributavel)
        self.rowFiscalHLayout.addLayout(self.colUnidadeTribVLayout)
        self.camposVLayout.addLayout(self.rowFiscalHLayout)
        self.row3HLayout = QtWidgets.QHBoxLayout()
        self.row3HLayout.setSpacing(12)
        self.row3HLayout.setObjectName("row3HLayout")
        self.colPrecoCustoVLayout = QtWidgets.QVBoxLayout()
        self.colPrecoCustoVLayout.setSpacing(3)
        self.colPrecoCustoVLayout.setObjectName("colPrecoCustoVLayout")
        self.lblPrecoCusto = QtWidgets.QLabel(self.frameCampos)
        self.lblPrecoCusto.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblPrecoCusto.setObjectName("lblPrecoCusto")
        self.colPrecoCustoVLayout.addWidget(self.lblPrecoCusto)
        self.lineEditPrecoCusto = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditPrecoCusto.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditPrecoCusto.setObjectName("lineEditPrecoCusto")
        self.colPrecoCustoVLayout.addWidget(self.lineEditPrecoCusto)
        self.row3HLayout.addLayout(self.colPrecoCustoVLayout)
        self.colPrecoVendaVLayout = QtWidgets.QVBoxLayout()
        self.colPrecoVendaVLayout.setSpacing(3)
        self.colPrecoVendaVLayout.setObjectName("colPrecoVendaVLayout")
        self.lblPrecoVenda = QtWidgets.QLabel(self.frameCampos)
        self.lblPrecoVenda.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblPrecoVenda.setObjectName("lblPrecoVenda")
        self.colPrecoVendaVLayout.addWidget(self.lblPrecoVenda)
        self.lineEditPrecoVenda = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditPrecoVenda.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     font-weight: bold;\n"
"                     color: #1a5fa0;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditPrecoVenda.setObjectName("lineEditPrecoVenda")
        self.colPrecoVendaVLayout.addWidget(self.lineEditPrecoVenda)
        self.row3HLayout.addLayout(self.colPrecoVendaVLayout)
        self.colMargemVLayout = QtWidgets.QVBoxLayout()
        self.colMargemVLayout.setSpacing(3)
        self.colMargemVLayout.setObjectName("colMargemVLayout")
        self.lblMargem = QtWidgets.QLabel(self.frameCampos)
        self.lblMargem.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblMargem.setObjectName("lblMargem")
        self.colMargemVLayout.addWidget(self.lblMargem)
        self.lineEditMargem = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditMargem.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #f0f6fc;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; background-color: #ffffff; }\n"
"                   ")
        self.lineEditMargem.setReadOnly(True)
        self.lineEditMargem.setObjectName("lineEditMargem")
        self.colMargemVLayout.addWidget(self.lineEditMargem)
        self.row3HLayout.addLayout(self.colMargemVLayout)
        self.camposVLayout.addLayout(self.row3HLayout)
        self.rowEstoqueHLayout = QtWidgets.QHBoxLayout()
        self.rowEstoqueHLayout.setSpacing(12)
        self.rowEstoqueHLayout.setObjectName("rowEstoqueHLayout")
        self.colEstoqueVLayout = QtWidgets.QVBoxLayout()
        self.colEstoqueVLayout.setSpacing(3)
        self.colEstoqueVLayout.setObjectName("colEstoqueVLayout")
        self.lblQuantidadeEstoque = QtWidgets.QLabel(self.frameCampos)
        self.lblQuantidadeEstoque.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblQuantidadeEstoque.setObjectName("lblQuantidadeEstoque")
        self.colEstoqueVLayout.addWidget(self.lblQuantidadeEstoque)
        self.lineEditQuantidadeEstoque = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditQuantidadeEstoque.setStyleSheet("\n"
"                    QLineEdit {\n"
"                     background-color: #ffffff;\n"
"                     border: 2px solid #a8c4d8;\n"
"                     border-radius: 4px;\n"
"                     font-size: 13px;\n"
"                     color: #1a3a5c;\n"
"                     padding: 3px 8px;\n"
"                    }\n"
"                    QLineEdit:focus { border-color: #3585c8; }\n"
"                   ")
        self.lineEditQuantidadeEstoque.setObjectName("lineEditQuantidadeEstoque")
        self.colEstoqueVLayout.addWidget(self.lineEditQuantidadeEstoque)
        self.rowEstoqueHLayout.addLayout(self.colEstoqueVLayout)
        self.colStatusVLayout = QtWidgets.QVBoxLayout()
        self.colStatusVLayout.setSpacing(3)
        self.colStatusVLayout.setObjectName("colStatusVLayout")
        self.lblStatusProduto = QtWidgets.QLabel(self.frameCampos)
        self.lblStatusProduto.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblStatusProduto.setObjectName("lblStatusProduto")
        self.colStatusVLayout.addWidget(self.lblStatusProduto)
        self.checkBoxAtivo = QtWidgets.QCheckBox(self.frameCampos)
        self.checkBoxAtivo.setStyleSheet("\n"
"                    QCheckBox {\n"
"                     font-size: 13px;\n"
"                     font-weight: bold;\n"
"                     color: #1a3a5c;\n"
"                     padding: 6px 2px;\n"
"                    }\n"
"                   ")
        self.checkBoxAtivo.setChecked(True)
        self.checkBoxAtivo.setObjectName("checkBoxAtivo")
        self.colStatusVLayout.addWidget(self.checkBoxAtivo)
        self.rowEstoqueHLayout.addLayout(self.colStatusVLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rowEstoqueHLayout.addItem(spacerItem2)
        self.camposVLayout.addLayout(self.rowEstoqueHLayout)
        self.colImagemVLayout = QtWidgets.QVBoxLayout()
        self.colImagemVLayout.setSpacing(6)
        self.colImagemVLayout.setObjectName("colImagemVLayout")
        self.lblImagemProduto = QtWidgets.QLabel(self.frameCampos)
        self.lblImagemProduto.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblImagemProduto.setObjectName("lblImagemProduto")
        self.colImagemVLayout.addWidget(self.lblImagemProduto)
        self.lblPreviewImagem = QtWidgets.QLabel(self.frameCampos)
        self.lblPreviewImagem.setMinimumSize(QtCore.QSize(0, 170))
        self.lblPreviewImagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPreviewImagem.setStyleSheet("\n"
"                  QLabel {\n"
"                   background-color: #f7fbff;\n"
"                   border: 2px dashed #a8c4d8;\n"
"                   border-radius: 4px;\n"
"                   font-size: 12px;\n"
"                   color: #5e7a94;\n"
"                   padding: 10px;\n"
"                  }\n"
"                 ")
        self.lblPreviewImagem.setObjectName("lblPreviewImagem")
        self.colImagemVLayout.addWidget(self.lblPreviewImagem)
        self.rowImagemHLayout = QtWidgets.QHBoxLayout()
        self.rowImagemHLayout.setSpacing(8)
        self.rowImagemHLayout.setObjectName("rowImagemHLayout")
        self.lineEditImagemProduto = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditImagemProduto.setReadOnly(True)
        self.lineEditImagemProduto.setStyleSheet("\n"
"                  QLineEdit {\n"
"                   background-color: #f0f6fc;\n"
"                   border: 2px solid #a8c4d8;\n"
"                   border-radius: 4px;\n"
"                   font-size: 12px;\n"
"                   color: #1a3a5c;\n"
"                   padding: 3px 8px;\n"
"                  }\n"
"                 ")
        self.lineEditImagemProduto.setObjectName("lineEditImagemProduto")
        self.rowImagemHLayout.addWidget(self.lineEditImagemProduto)
        self.btnSelecionarImagem = QtWidgets.QPushButton(self.frameCampos)
        self.btnSelecionarImagem.setMinimumSize(QtCore.QSize(150, 34))
        self.btnSelecionarImagem.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background-color: #e8f1f9;\n"
"                   color: #1a5fa0;\n"
"                   font-size: 12px;\n"
"                   font-weight: bold;\n"
"                   border: 1px solid #a8c4d8;\n"
"                   border-radius: 5px;\n"
"                   padding: 5px 12px;\n"
"                  }\n"
"                  QPushButton:hover  { background-color: #d9ebfa; }\n"
"                  QPushButton:pressed{ background-color: #c8def1; }\n"
"                 ")
        self.btnSelecionarImagem.setObjectName("btnSelecionarImagem")
        self.rowImagemHLayout.addWidget(self.btnSelecionarImagem)
        self.btnRemoverImagem = QtWidgets.QPushButton(self.frameCampos)
        self.btnRemoverImagem.setMinimumSize(QtCore.QSize(110, 34))
        self.btnRemoverImagem.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background-color: #f0f0f0;\n"
"                   color: #555555;\n"
"                   font-size: 12px;\n"
"                   font-weight: bold;\n"
"                   border: 1px solid #bbbbbb;\n"
"                   border-radius: 5px;\n"
"                   padding: 5px 12px;\n"
"                  }\n"
"                  QPushButton:hover  { background-color: #e0e0e0; }\n"
"                  QPushButton:pressed{ background-color: #cccccc; }\n"
"                 ")
        self.btnRemoverImagem.setObjectName("btnRemoverImagem")
        self.rowImagemHLayout.addWidget(self.btnRemoverImagem)
        self.colImagemVLayout.addLayout(self.rowImagemHLayout)
        self.camposVLayout.addLayout(self.colImagemVLayout)
        self.botoesHLayout = QtWidgets.QHBoxLayout()
        self.botoesHLayout.setSpacing(10)
        self.botoesHLayout.setObjectName("botoesHLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesHLayout.addItem(spacerItem3)
        self.btnLimpar = QtWidgets.QPushButton(self.frameCampos)
        self.btnLimpar.setMinimumSize(QtCore.QSize(110, 38))
        self.btnLimpar.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background-color: #f0f0f0;\n"
"                   color: #555555;\n"
"                   font-size: 12px;\n"
"                   font-weight: bold;\n"
"                   border: 1px solid #bbbbbb;\n"
"                   border-radius: 5px;\n"
"                   padding: 5px 14px;\n"
"                  }\n"
"                  QPushButton:hover  { background-color: #e0e0e0; }\n"
"                  QPushButton:pressed{ background-color: #cccccc; }\n"
"                 ")
        self.btnLimpar.setObjectName("btnLimpar")
        self.botoesHLayout.addWidget(self.btnLimpar)
        self.btnSalvar = QtWidgets.QPushButton(self.frameCampos)
        self.btnSalvar.setMinimumSize(QtCore.QSize(120, 38))
        self.btnSalvar.setStyleSheet("\n"
"                  QPushButton {\n"
"                   background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                    stop:0 #3585c8, stop:1 #1a5fa0);\n"
"                   color: white;\n"
"                   font-size: 12px;\n"
"                   font-weight: bold;\n"
"                   border: none;\n"
"                   border-radius: 5px;\n"
"                   padding: 5px 14px;\n"
"                  }\n"
"                  QPushButton:hover  { background: #2a74b8; }\n"
"                  QPushButton:pressed{ background: #1a5fa0; }\n"
"                 ")
        self.btnSalvar.setObjectName("btnSalvar")
        self.botoesHLayout.addWidget(self.btnSalvar)
        self.camposVLayout.addLayout(self.botoesHLayout)
        self.formularioVLayout.addWidget(self.frameCampos)
        self.conteudoHLayout.addWidget(self.frameFormulario)
        self.conteudoHLayout.setStretch(0, 2)
        self.mainVLayout.addLayout(self.conteudoHLayout)
        self.frameStatusBar = QtWidgets.QFrame(CadastroProduto)
        self.frameStatusBar.setStyleSheet("\n"
"       QFrame#frameStatusBar {\n"
"        background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"         stop:0 #3585c8, stop:1 #1a5fa0);\n"
"       }\n"
"      ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusHLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusHLayout.setContentsMargins(12, 0, 12, 0)
        self.statusHLayout.setObjectName("statusHLayout")
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setStyleSheet("color: white; font-size: 11px; font-weight: bold;")
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusHLayout.addWidget(self.lblStatusBar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem4)
        self.mainVLayout.addWidget(self.frameStatusBar)

        self.retranslateUi(CadastroProduto)
        QtCore.QMetaObject.connectSlotsByName(CadastroProduto)

    def retranslateUi(self, CadastroProduto):
        _translate = QtCore.QCoreApplication.translate
        CadastroProduto.setWindowTitle(_translate("CadastroProduto", "GR$Pdv - Cadastro de Produto"))
        self.lblLogo.setText(_translate("CadastroProduto", "GR$Pdv"))
        self.lblBadge.setText(_translate("CadastroProduto", "📦  CADASTRO DE PRODUTO"))
        self.btnVoltar.setText(_translate("CadastroProduto", "◀  Voltar"))
        self.lblTabCadProduto.setText(_translate("CadastroProduto", "Cadastro de Produto"))
        self.lblFormTitle.setText(_translate("CadastroProduto", "Dados do Produto"))
        self.lblCodigo.setText(_translate("CadastroProduto", "Código"))
        self.lineEditCodigo.setPlaceholderText(_translate("CadastroProduto", "Auto-gerado"))
        self.lblCodigoBarras.setText(_translate("CadastroProduto", "Codigo de Barras *"))
        self.lineEditCodigoBarras.setPlaceholderText(_translate("CadastroProduto", "Codigo de barras"))
        self.lblDescricao.setText(_translate("CadastroProduto", "Descrição do Produto *"))
        self.lineEditDescricao.setPlaceholderText(_translate("CadastroProduto", "Nome completo do produto"))
        self.lblCategoria.setText(_translate("CadastroProduto", "Categoria *"))
        self.comboCategoria.setItemText(0, _translate("CadastroProduto", "Selecione a categoria"))
        self.lblUnidade.setText(_translate("CadastroProduto", "Marca *"))
        self.comboMarca.setItemText(0, _translate("CadastroProduto", "Selecione a marca"))
        self.lblD.setText(_translate("CadastroProduto", "Fornecedor *"))
        self.comboBox.setItemText(0, _translate("CadastroProduto", "Selecione o fornecedor"))
        self.lblNcm.setText(_translate("CadastroProduto", "NCM"))
        self.lineEditNcm.setPlaceholderText(_translate("CadastroProduto", "00000000"))
        self.lblCest.setText(_translate("CadastroProduto", "CEST"))
        self.lineEditCest.setPlaceholderText(_translate("CadastroProduto", "0000000"))
        self.lblUnidadeComercial.setText(_translate("CadastroProduto", "Unidade Comercial"))
        self.comboUnidade.setItemText(0, _translate("CadastroProduto", "Selecione a unidade"))
        self.lblUnidadeTributavel.setText(_translate("CadastroProduto", "Unidade Tributavel"))
        self.comboUnidadeTributavel.setItemText(0, _translate("CadastroProduto", "Selecione a unidade tributavel"))
        self.lblPrecoCusto.setText(_translate("CadastroProduto", "Preço de Custo (R$)"))
        self.lineEditPrecoCusto.setPlaceholderText(_translate("CadastroProduto", "0,00"))
        self.lblPrecoVenda.setText(_translate("CadastroProduto", "Preço de Venda (R$) *"))
        self.lineEditPrecoVenda.setPlaceholderText(_translate("CadastroProduto", "0,00"))
        self.lblMargem.setText(_translate("CadastroProduto", "Margem (%)"))
        self.lineEditMargem.setPlaceholderText(_translate("CadastroProduto", "0,00"))
        self.lblQuantidadeEstoque.setText(_translate("CadastroProduto", "Estoque Inicial"))
        self.lineEditQuantidadeEstoque.setPlaceholderText(_translate("CadastroProduto", "0"))
        self.lblStatusProduto.setText(_translate("CadastroProduto", "Status *"))
        self.checkBoxAtivo.setText(_translate("CadastroProduto", "Produto ativo"))
        self.lblImagemProduto.setText(_translate("CadastroProduto", "Imagem do Produto"))
        self.lblPreviewImagem.setText(_translate("CadastroProduto", "Nenhuma imagem selecionada"))
        self.lineEditImagemProduto.setPlaceholderText(_translate("CadastroProduto", "Nenhum arquivo selecionado"))
        self.btnSelecionarImagem.setText(_translate("CadastroProduto", "Selecionar Imagem"))
        self.btnRemoverImagem.setText(_translate("CadastroProduto", "Remover"))
        self.btnLimpar.setText(_translate("CadastroProduto", "🗑  Limpar"))
        self.btnSalvar.setText(_translate("CadastroProduto", "💾  Salvar"))
        self.btnSalvar.setShortcut(_translate("CadastroProduto", "Return"))
        self.lblStatusBar.setText(_translate("CadastroProduto", "GRPDV - Operador: ADMIN  |  Cadastro de Produto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CadastroProduto = QtWidgets.QWidget()
    ui = Ui_CadastroProduto()
    ui.setupUi(CadastroProduto)
    CadastroProduto.show()
    sys.exit(app.exec_())
