from PyQt5 import QtCore, QtWidgets

class Ui_CadastroCliente(object):
    def setupUi(self, CadastroCliente):
        CadastroCliente.setObjectName("CadastroCliente")
        CadastroCliente.resize(1376, 900)
        CadastroCliente.setStyleSheet("QWidget { font-family: Arial; }")
        self.mainVLayout = QtWidgets.QVBoxLayout(CadastroCliente)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(CadastroCliente)
        self.frameHeader.setStyleSheet("QFrame#frameHeader { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); }")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(14, 8, 14, 8)
        self.headerHLayout.setSpacing(12)
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setStyleSheet("color: white; font-size: 28px; font-weight: bold;")
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblBadge = QtWidgets.QLabel(self.frameHeader)
        self.lblBadge.setStyleSheet("QLabel { background-color: rgba(255,255,255,30); color: #ffe080; font-size: 12px; font-weight: bold; border: 1px solid rgba(255,255,255,60); border-radius: 4px; padding: 3px 10px; }")
        self.lblBadge.setObjectName("lblBadge")
        self.headerHLayout.addWidget(self.lblBadge)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.btnVoltar = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltar.setMinimumSize(QtCore.QSize(90, 32))
        self.btnVoltar.setStyleSheet("QPushButton { background-color: rgba(255,255,255,25); color: white; font-size: 11px; font-weight: bold; border: 1px solid rgba(255,255,255,60); border-radius: 4px; padding: 4px 12px; } QPushButton:hover { background-color: rgba(255,255,255,40); } QPushButton:pressed { background-color: rgba(255,255,255,15); }")
        self.btnVoltar.setObjectName("btnVoltar")
        self.headerHLayout.addWidget(self.btnVoltar)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameTabBar = QtWidgets.QFrame(CadastroCliente)
        self.frameTabBar.setStyleSheet("QFrame#frameTabBar { background-color: #9dbfda; }")
        self.frameTabBar.setObjectName("frameTabBar")
        self.tabHLayout = QtWidgets.QHBoxLayout(self.frameTabBar)
        self.tabHLayout.setContentsMargins(10, 3, 0, 0)
        self.lblTabCadCliente = QtWidgets.QLabel(self.frameTabBar)
        self.lblTabCadCliente.setStyleSheet("QLabel { background-color: #c4d8e8; border: 1px solid #8aaabb; border-bottom: none; padding: 1px 14px; font-size: 12px; }")
        self.lblTabCadCliente.setObjectName("lblTabCadCliente")
        self.tabHLayout.addWidget(self.lblTabCadCliente)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tabHLayout.addItem(spacerItem1)
        self.mainVLayout.addWidget(self.frameTabBar)
        self.conteudoHLayout = QtWidgets.QHBoxLayout()
        self.conteudoHLayout.setContentsMargins(14, 12, 14, 12)
        self.conteudoHLayout.setSpacing(12)
        self.frameFormulario = QtWidgets.QFrame(CadastroCliente)
        self.frameFormulario.setStyleSheet("QFrame#frameFormulario { background-color: #ffffff; border: 1px solid #a8c4d8; border-radius: 6px; }")
        self.frameFormulario.setObjectName("frameFormulario")
        self.formularioVLayout = QtWidgets.QVBoxLayout(self.frameFormulario)
        self.formularioVLayout.setContentsMargins(0, 0, 0, 0)
        self.formularioVLayout.setSpacing(0)
        self.lblFormTitle = QtWidgets.QLabel(self.frameFormulario)
        self.lblFormTitle.setStyleSheet("QLabel { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); color: white; font-size: 13px; font-weight: bold; padding: 6px 14px; border-top-left-radius: 6px; border-top-right-radius: 6px; }")
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formularioVLayout.addWidget(self.lblFormTitle)
        self.frameCampos = QtWidgets.QFrame(self.frameFormulario)
        self.frameCampos.setStyleSheet("QFrame#frameCampos { background-color: #ffffff; }")
        self.frameCampos.setObjectName("frameCampos")
        self.camposVLayout = QtWidgets.QVBoxLayout(self.frameCampos)
        self.camposVLayout.setContentsMargins(16, 14, 16, 14)
        self.camposVLayout.setSpacing(10)

        self.row0HLayout = QtWidgets.QHBoxLayout()
        self.colCodigoVLayout = QtWidgets.QVBoxLayout()
        self.lblCodigo = QtWidgets.QLabel(self.frameCampos)
        self.lblCodigo.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblCodigo.setObjectName("lblCodigo")
        self.colCodigoVLayout.addWidget(self.lblCodigo)
        self.lineEditCodigo = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCodigo.setStyleSheet("QLineEdit{background-color:#f0f6fc;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;background-color:#ffffff;}")
        self.lineEditCodigo.setReadOnly(True)
        self.lineEditCodigo.setObjectName("lineEditCodigo")
        self.colCodigoVLayout.addWidget(self.lineEditCodigo)
        self.row0HLayout.addLayout(self.colCodigoVLayout)
        self.colStatusVLayout = QtWidgets.QVBoxLayout()
        self.lblStatus = QtWidgets.QLabel(self.frameCampos)
        self.lblStatus.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblStatus.setObjectName("lblStatus")
        self.colStatusVLayout.addWidget(self.lblStatus)
        self.checkBoxAtivo = QtWidgets.QCheckBox(self.frameCampos)
        self.checkBoxAtivo.setStyleSheet("QCheckBox{font-size:13px;color:#1a3a5c;spacing:6px;}QCheckBox::indicator{width:18px;height:18px;border:2px solid #a8c4d8;border-radius:3px;background:#ffffff;}QCheckBox::indicator:checked{background-color:#3585c8;border-color:#1a5fa0;}")
        self.checkBoxAtivo.setChecked(True)
        self.checkBoxAtivo.setObjectName("checkBoxAtivo")
        self.colStatusVLayout.addWidget(self.checkBoxAtivo)
        self.row0HLayout.addLayout(self.colStatusVLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row0HLayout.addItem(spacerItem2)
        self.camposVLayout.addLayout(self.row0HLayout)

        def add_line(layout, label_name, label_text, field):
            col = QtWidgets.QVBoxLayout()
            lbl = QtWidgets.QLabel(self.frameCampos)
            lbl.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
            lbl.setObjectName(label_name)
            lbl.setText(label_text)
            col.addWidget(lbl)
            col.addWidget(field)
            layout.addLayout(col)
            return lbl

        self.lineEditNome = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditNome.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditNome.setObjectName("lineEditNome")
        self.lblNome = QtWidgets.QLabel(self.frameCampos)
        self.lblNome.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblNome.setObjectName("lblNome")
        self.lblNome.setText("Nome *")
        self.camposVLayout.addWidget(self.lblNome)
        self.camposVLayout.addWidget(self.lineEditNome)

        self.row2HLayout = QtWidgets.QHBoxLayout()
        self.lineEditCpf = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCpf.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditCpf.setObjectName("lineEditCpf")
        self.lblCpf = add_line(self.row2HLayout, "lblCpf", "CPF", self.lineEditCpf)
        self.lineEditTelefone = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditTelefone.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditTelefone.setObjectName("lineEditTelefone")
        self.lblTelefone = add_line(self.row2HLayout, "lblTelefone", "Telefone", self.lineEditTelefone)
        self.lineEditEmail = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditEmail.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lblEmail = add_line(self.row2HLayout, "lblEmail", "E-mail", self.lineEditEmail)
        self.camposVLayout.addLayout(self.row2HLayout)

        self.row4HLayout = QtWidgets.QHBoxLayout()
        self.lineEditLogradouro = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditLogradouro.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditLogradouro.setObjectName("lineEditLogradouro")
        self.lblLogradouro = add_line(self.row4HLayout, "lblLogradouro", "Logradouro", self.lineEditLogradouro)
        self.lineEditNumero = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditNumero.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditNumero.setObjectName("lineEditNumero")
        self.lblNumero = add_line(self.row4HLayout, "lblNumero", "Numero", self.lineEditNumero)
        self.lineEditBairro = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditBairro.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditBairro.setObjectName("lineEditBairro")
        self.lblBairro = add_line(self.row4HLayout, "lblBairro", "Bairro", self.lineEditBairro)
        self.camposVLayout.addLayout(self.row4HLayout)

        self.row5HLayout = QtWidgets.QHBoxLayout()
        self.lineEditCep = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCep.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditCep.setObjectName("lineEditCep")
        self.lblCep = add_line(self.row5HLayout, "lblCep", "CEP", self.lineEditCep)
        self.lineEditCidade = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditCidade.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditCidade.setObjectName("lineEditCidade")
        self.lblCidade = add_line(self.row5HLayout, "lblCidade", "Cidade", self.lineEditCidade)
        self.lineEditEstado = QtWidgets.QLineEdit(self.frameCampos)
        self.lineEditEstado.setStyleSheet("QLineEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:13px;color:#1a3a5c;padding:3px 8px;}QLineEdit:focus{border-color:#3585c8;}")
        self.lineEditEstado.setObjectName("lineEditEstado")
        self.lblEstado = add_line(self.row5HLayout, "lblEstado", "Estado", self.lineEditEstado)
        self.camposVLayout.addLayout(self.row5HLayout)

        self.lblObservacao = QtWidgets.QLabel(self.frameCampos)
        self.lblObservacao.setStyleSheet("font-size:12px; font-weight:bold; color:#1a3a5c;")
        self.lblObservacao.setObjectName("lblObservacao")
        self.camposVLayout.addWidget(self.lblObservacao)
        self.plainTextObservacao = QtWidgets.QPlainTextEdit(self.frameCampos)
        self.plainTextObservacao.setStyleSheet("QPlainTextEdit{background-color:#ffffff;border:2px solid #a8c4d8;border-radius:4px;font-size:12px;color:#1a3a5c;padding:4px 8px;}QPlainTextEdit:focus{border-color:#3585c8;}")
        self.plainTextObservacao.setObjectName("plainTextObservacao")
        self.camposVLayout.addWidget(self.plainTextObservacao)

        self.botoesHLayout = QtWidgets.QHBoxLayout()
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.botoesHLayout.addItem(spacerItem3)
        self.btnLimpar = QtWidgets.QPushButton(self.frameCampos)
        self.btnLimpar.setMinimumSize(QtCore.QSize(110, 38))
        self.btnLimpar.setStyleSheet("QPushButton{background-color:#f0f0f0;color:#555555;font-size:12px;font-weight:bold;border:1px solid #bbbbbb;border-radius:5px;padding:5px 14px;}QPushButton:hover{background-color:#e0e0e0;}QPushButton:pressed{background-color:#cccccc;}")
        self.btnLimpar.setObjectName("btnLimpar")
        self.botoesHLayout.addWidget(self.btnLimpar)
        self.btnSalvar = QtWidgets.QPushButton(self.frameCampos)
        self.btnSalvar.setMinimumSize(QtCore.QSize(120, 38))
        self.btnSalvar.setStyleSheet("QPushButton{background:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 #3585c8,stop:1 #1a5fa0);color:white;font-size:12px;font-weight:bold;border:none;border-radius:5px;padding:5px 14px;}QPushButton:hover{background:#2a74b8;}QPushButton:pressed{background:#1a5fa0;}")
        self.btnSalvar.setObjectName("btnSalvar")
        self.botoesHLayout.addWidget(self.btnSalvar)
        self.camposVLayout.addLayout(self.botoesHLayout)
        self.formularioVLayout.addWidget(self.frameCampos)
        self.conteudoHLayout.addWidget(self.frameFormulario)
        self.mainVLayout.addLayout(self.conteudoHLayout)
        self.frameStatusBar = QtWidgets.QFrame(CadastroCliente)
        self.frameStatusBar.setStyleSheet("QFrame#frameStatusBar {background: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 #3585c8, stop:1 #1a5fa0);}")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusHLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusHLayout.setContentsMargins(12, 0, 12, 0)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setStyleSheet("color: white; font-size: 11px; font-weight: bold;")
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusHLayout.addWidget(self.lblStatusBar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem4)
        self.mainVLayout.addWidget(self.frameStatusBar)

        self.retranslateUi(CadastroCliente)
        QtCore.QMetaObject.connectSlotsByName(CadastroCliente)

    def retranslateUi(self, CadastroCliente):
        _translate = QtCore.QCoreApplication.translate
        CadastroCliente.setWindowTitle(_translate("CadastroCliente", "CSPdv - Cadastro de Cliente"))
        self.lblLogo.setText(_translate("CadastroCliente", "CSPdv"))
        self.lblBadge.setText(_translate("CadastroCliente", "CADASTRO DE CLIENTE"))
        self.btnVoltar.setText(_translate("CadastroCliente", "Voltar"))
        self.lblTabCadCliente.setText(_translate("CadastroCliente", "Cadastro de Cliente"))
        self.lblFormTitle.setText(_translate("CadastroCliente", "Dados do Cliente"))
        self.lblCodigo.setText(_translate("CadastroCliente", "Codigo"))
        self.lineEditCodigo.setPlaceholderText(_translate("CadastroCliente", "Auto-gerado"))
        self.lblStatus.setText(_translate("CadastroCliente", "Status"))
        self.checkBoxAtivo.setText(_translate("CadastroCliente", "Cliente ativo"))
        self.lineEditNome.setPlaceholderText(_translate("CadastroCliente", "Nome completo do cliente"))
        self.lineEditCpf.setPlaceholderText(_translate("CadastroCliente", "00000000000"))
        self.lineEditTelefone.setPlaceholderText(_translate("CadastroCliente", "Telefone"))
        self.lineEditEmail.setPlaceholderText(_translate("CadastroCliente", "E-mail"))
        self.lineEditLogradouro.setPlaceholderText(_translate("CadastroCliente", "Rua, avenida, etc."))
        self.lineEditNumero.setPlaceholderText(_translate("CadastroCliente", "Numero"))
        self.lineEditBairro.setPlaceholderText(_translate("CadastroCliente", "Bairro"))
        self.lineEditCep.setPlaceholderText(_translate("CadastroCliente", "00000000"))
        self.lineEditCidade.setPlaceholderText(_translate("CadastroCliente", "Cidade"))
        self.lineEditEstado.setPlaceholderText(_translate("CadastroCliente", "UF"))
        self.lblObservacao.setText(_translate("CadastroCliente", "Observacao"))
        self.plainTextObservacao.setPlaceholderText(_translate("CadastroCliente", "Informacoes adicionais sobre o cliente..."))
        self.btnLimpar.setText(_translate("CadastroCliente", "Limpar"))
        self.btnSalvar.setText(_translate("CadastroCliente", "Salvar"))
        self.lblStatusBar.setText(_translate("CadastroCliente", "CSPdv - Operador: ADMIN  |  Cadastro de Cliente"))
