# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PainelAdmin(object):
    def setupUi(self, PainelAdmin):
        PainelAdmin.setObjectName("PainelAdmin")
        PainelAdmin.resize(1388, 812)
        PainelAdmin.setStyleSheet("QWidget { font-family: Arial; }")
        self.centralWidget = QtWidgets.QWidget(PainelAdmin)
        self.centralWidget.setObjectName("centralWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(self.centralWidget)
        self.frameHeader.setStyleSheet("\n"
"QFrame#frameHeader {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #153552, stop:0.55 #1d4c74, stop:1 #2f75b0);\n"
"}\n"
"       ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(14, 8, 14, 8)
        self.headerHLayout.setSpacing(12)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setStyleSheet("color: white; font-size: 30px; font-weight: 800;")
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblBadgeAdmin = QtWidgets.QLabel(self.frameHeader)
        self.lblBadgeAdmin.setStyleSheet("\n"
"QLabel {\n"
" background-color: rgba(255,255,255,0.10);\n"
" color: #ffe59d;\n"
" font-size: 12px;\n"
" font-weight: 700;\n"
" border: 1px solid rgba(255,255,255,0.18);\n"
" border-radius: 8px;\n"
" padding: 8px 14px;\n"
"}\n"
"          ")
        self.lblBadgeAdmin.setObjectName("lblBadgeAdmin")
        self.headerHLayout.addWidget(self.lblBadgeAdmin)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.lblOperadorInfo = QtWidgets.QLabel(self.frameHeader)
        self.lblOperadorInfo.setStyleSheet("color: #dbeaf7; font-size: 12px; font-weight: 600;")
        self.lblOperadorInfo.setObjectName("lblOperadorInfo")
        self.headerHLayout.addWidget(self.lblOperadorInfo)
        self.lblDataHora = QtWidgets.QLabel(self.frameHeader)
        self.lblDataHora.setStyleSheet("\n"
"QLabel {\n"
" color: #dbeaf7;\n"
" font-size: 12px;\n"
" font-weight: 600;\n"
" background-color: transparent;\n"
" padding: 0px;\n"
"}\n"
"          ")
        self.lblDataHora.setObjectName("lblDataHora")
        self.headerHLayout.addWidget(self.lblDataHora)
        self.btnSair = QtWidgets.QPushButton(self.frameHeader)
        self.btnSair.setMinimumSize(QtCore.QSize(86, 42))
        self.btnSair.setStyleSheet("\n"
"QPushButton {\n"
" background-color: #d92b2b;\n"
" color: white;\n"
" font-size: 12px;\n"
" font-weight: 700;\n"
" border: none;\n"
" border-radius: 10px;\n"
" padding: 10px 24px;\n"
"}\n"
"QPushButton:hover  { background-color: #c11f1f; }\n"
"QPushButton:pressed{ background-color: #a81818; }\n"
"          ")
        self.btnSair.setObjectName("btnSair")
        self.headerHLayout.addWidget(self.btnSair)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameNavBar = QtWidgets.QFrame(self.centralWidget)
        self.frameNavBar.setMinimumSize(QtCore.QSize(0, 46))
        self.frameNavBar.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frameNavBar.setStyleSheet("\n"
"QFrame#frameNavBar { background-color: #1a5fa0; }\n"
"QPushButton {\n"
" background-color: transparent;\n"
" color: #c8dff4;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-bottom: 3px solid transparent;\n"
" min-height: 44px;\n"
" padding: 6px 18px;\n"
"}\n"
"QPushButton:hover {\n"
" color: white;\n"
" background-color: rgba(255,255,255,15);\n"
" border-bottom: 3px solid rgba(255,255,255,60);\n"
"}\n"
"QPushButton:checked {\n"
" color: white;\n"
" background-color: rgba(255,255,255,20);\n"
" border-bottom: 3px solid #ffe080;\n"
"}\n"
"       ")
        self.frameNavBar.setObjectName("frameNavBar")
        self.navHLayout = QtWidgets.QHBoxLayout(self.frameNavBar)
        self.navHLayout.setContentsMargins(8, 0, 0, 0)
        self.navHLayout.setSpacing(0)
        self.navHLayout.setObjectName("navHLayout")
        self.btnNavDashboard = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavDashboard.setCheckable(True)
        self.btnNavDashboard.setChecked(True)
        self.btnNavDashboard.setObjectName("btnNavDashboard")
        self.navHLayout.addWidget(self.btnNavDashboard)
        self.btnNavProdutos = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavProdutos.setCheckable(True)
        self.btnNavProdutos.setObjectName("btnNavProdutos")
        self.navHLayout.addWidget(self.btnNavProdutos)
        self.btnNavUsuarios = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavUsuarios.setCheckable(True)
        self.btnNavUsuarios.setObjectName("btnNavUsuarios")
        self.navHLayout.addWidget(self.btnNavUsuarios)
        self.btnNavVendas = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavVendas.setCheckable(True)
        self.btnNavVendas.setObjectName("btnNavVendas")
        self.navHLayout.addWidget(self.btnNavVendas)
        self.btnNavClientes = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavClientes.setCheckable(True)
        self.btnNavClientes.setObjectName("btnNavClientes")
        self.navHLayout.addWidget(self.btnNavClientes)
        self.btnNavLotes = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavLotes.setCheckable(True)
        self.btnNavLotes.setObjectName("btnNavLotes")
        self.navHLayout.addWidget(self.btnNavLotes)
        self.btnNavAuditoria = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavAuditoria.setCheckable(True)
        self.btnNavAuditoria.setObjectName("btnNavAuditoria")
        self.navHLayout.addWidget(self.btnNavAuditoria)
        self.btnNavConfiguracoes = QtWidgets.QPushButton(self.frameNavBar)
        self.btnNavConfiguracoes.setCheckable(True)
        self.btnNavConfiguracoes.setObjectName("btnNavConfiguracoes")
        self.navHLayout.addWidget(self.btnNavConfiguracoes)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.navHLayout.addItem(spacerItem1)
        self.mainVLayout.addWidget(self.frameNavBar)
        self.frameSubNavBar = QtWidgets.QFrame(self.centralWidget)
        self.frameSubNavBar.setMinimumSize(QtCore.QSize(0, 42))
        self.frameSubNavBar.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frameSubNavBar.setStyleSheet("\n"
"QFrame#frameSubNavBar { background-color: #ecf4fb; border-bottom: 1px solid #d4e1ec; }\n"
"QPushButton {\n"
" background-color: transparent;\n"
" color: #567f9f;\n"
" border: none;\n"
" padding: 6px 12px;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" text-align: left;\n"
"}\n"
"QPushButton:hover { color: #1a5fa0; background-color: rgba(53,133,200,18); }\n"
"       ")
        self.frameSubNavBar.setObjectName("frameSubNavBar")
        self.subNavLayout = QtWidgets.QHBoxLayout(self.frameSubNavBar)
        self.subNavLayout.setContentsMargins(12, 0, 12, 0)
        self.subNavLayout.setSpacing(6)
        self.subNavLayout.setObjectName("subNavLayout")
        self.btnNavProdutosCadastro = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavProdutosCadastro.setObjectName("btnNavProdutosCadastro")
        self.subNavLayout.addWidget(self.btnNavProdutosCadastro)
        self.btnNavMarcas = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavMarcas.setObjectName("btnNavMarcas")
        self.subNavLayout.addWidget(self.btnNavMarcas)
        self.btnNavFornecedores = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavFornecedores.setObjectName("btnNavFornecedores")
        self.subNavLayout.addWidget(self.btnNavFornecedores)
        self.btnNavCategorias = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavCategorias.setObjectName("btnNavCategorias")
        self.subNavLayout.addWidget(self.btnNavCategorias)
        self.btnNavClientesCadastro = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavClientesCadastro.setObjectName("btnNavClientesCadastro")
        self.subNavLayout.addWidget(self.btnNavClientesCadastro)
        self.btnNavPerfis = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavPerfis.setObjectName("btnNavPerfis")
        self.subNavLayout.addWidget(self.btnNavPerfis)
        self.btnNavPermissoes = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavPermissoes.setObjectName("btnNavPermissoes")
        self.subNavLayout.addWidget(self.btnNavPermissoes)
        self.btnNavCargos = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavCargos.setObjectName("btnNavCargos")
        self.subNavLayout.addWidget(self.btnNavCargos)
        self.btnNavFormasPagamento = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavFormasPagamento.setObjectName("btnNavFormasPagamento")
        self.subNavLayout.addWidget(self.btnNavFormasPagamento)
        self.btnNavCaixas = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavCaixas.setObjectName("btnNavCaixas")
        self.subNavLayout.addWidget(self.btnNavCaixas)
        self.btnNavFiscal = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavFiscal.setObjectName("btnNavFiscal")
        self.subNavLayout.addWidget(self.btnNavFiscal)
        self.btnNavUnidades = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavUnidades.setObjectName("btnNavUnidades")
        self.subNavLayout.addWidget(self.btnNavUnidades)
        self.btnNavPdvs = QtWidgets.QPushButton(self.frameSubNavBar)
        self.btnNavPdvs.setObjectName("btnNavPdvs")
        self.subNavLayout.addWidget(self.btnNavPdvs)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.subNavLayout.addItem(spacerItem2)
        self.mainVLayout.addWidget(self.frameSubNavBar)
        self.mainContentVLayout = QtWidgets.QVBoxLayout()
        self.mainContentVLayout.setContentsMargins(16, 14, 16, 14)
        self.mainContentVLayout.setSpacing(12)
        self.mainContentVLayout.setObjectName("mainContentVLayout")
        self.sectionTitleHLayout = QtWidgets.QHBoxLayout()
        self.sectionTitleHLayout.setObjectName("sectionTitleHLayout")
        self.lblSectionTitle = QtWidgets.QLabel(self.centralWidget)
        self.lblSectionTitle.setStyleSheet("font-size: 19px; font-weight: bold; color: #1a3a5c;")
        self.lblSectionTitle.setObjectName("lblSectionTitle")
        self.sectionTitleHLayout.addWidget(self.lblSectionTitle)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sectionTitleHLayout.addItem(spacerItem3)
        self.btnFrenteCaixa = QtWidgets.QPushButton(self.centralWidget)
        self.btnFrenteCaixa.setMinimumSize(QtCore.QSize(208, 38))
        self.btnFrenteCaixa.setStyleSheet("\n"
"QPushButton {\n"
" background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0);\n"
" color: white;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-radius: 5px;\n"
" padding: 6px 16px;\n"
"}\n"
"QPushButton:hover { background: #2a74b8; }\n"
"           ")
        self.btnFrenteCaixa.setObjectName("btnFrenteCaixa")
        self.sectionTitleHLayout.addWidget(self.btnFrenteCaixa)
        self.mainContentVLayout.addLayout(self.sectionTitleHLayout)
        self.cardsHLayout = QtWidgets.QHBoxLayout()
        self.cardsHLayout.setSpacing(12)
        self.cardsHLayout.setObjectName("cardsHLayout")
        self.cardVendasHoje = QtWidgets.QFrame(self.centralWidget)
        self.cardVendasHoje.setStyleSheet("QFrame#cardVendasHoje { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0); border-radius: 8px; }")
        self.cardVendasHoje.setObjectName("cardVendasHoje")
        self.cardVendasVLayout = QtWidgets.QVBoxLayout(self.cardVendasHoje)
        self.cardVendasVLayout.setContentsMargins(16, 14, 16, 14)
        self.cardVendasVLayout.setSpacing(4)
        self.cardVendasVLayout.setObjectName("cardVendasVLayout")
        self.lblCardVendasIcon = QtWidgets.QLabel(self.cardVendasHoje)
        self.lblCardVendasIcon.setStyleSheet("font-size: 22px; color: white;")
        self.lblCardVendasIcon.setObjectName("lblCardVendasIcon")
        self.cardVendasVLayout.addWidget(self.lblCardVendasIcon)
        self.lblVendasHojeValor = QtWidgets.QLabel(self.cardVendasHoje)
        self.lblVendasHojeValor.setStyleSheet("color: white; font-size: 32px; font-weight: bold;")
        self.lblVendasHojeValor.setObjectName("lblVendasHojeValor")
        self.cardVendasVLayout.addWidget(self.lblVendasHojeValor)
        self.lblVendasHojeTitulo = QtWidgets.QLabel(self.cardVendasHoje)
        self.lblVendasHojeTitulo.setStyleSheet("color: #d5e9fa; font-size: 12px;")
        self.lblVendasHojeTitulo.setObjectName("lblVendasHojeTitulo")
        self.cardVendasVLayout.addWidget(self.lblVendasHojeTitulo)
        self.cardsHLayout.addWidget(self.cardVendasHoje)
        self.cardFaturamento = QtWidgets.QFrame(self.centralWidget)
        self.cardFaturamento.setStyleSheet("QFrame#cardFaturamento { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #5cb85c, stop:1 #3f9443); border-radius: 8px; }")
        self.cardFaturamento.setObjectName("cardFaturamento")
        self.cardFatVLayout = QtWidgets.QVBoxLayout(self.cardFaturamento)
        self.cardFatVLayout.setContentsMargins(16, 14, 16, 14)
        self.cardFatVLayout.setSpacing(4)
        self.cardFatVLayout.setObjectName("cardFatVLayout")
        self.lblCardFatIcon = QtWidgets.QLabel(self.cardFaturamento)
        self.lblCardFatIcon.setStyleSheet("font-size: 22px; color: white;")
        self.lblCardFatIcon.setObjectName("lblCardFatIcon")
        self.cardFatVLayout.addWidget(self.lblCardFatIcon)
        self.lblFaturamentoValor = QtWidgets.QLabel(self.cardFaturamento)
        self.lblFaturamentoValor.setStyleSheet("color: white; font-size: 26px; font-weight: bold;")
        self.lblFaturamentoValor.setObjectName("lblFaturamentoValor")
        self.cardFatVLayout.addWidget(self.lblFaturamentoValor)
        self.lblFaturamentoTitulo = QtWidgets.QLabel(self.cardFaturamento)
        self.lblFaturamentoTitulo.setStyleSheet("color: #daf0da; font-size: 12px;")
        self.lblFaturamentoTitulo.setObjectName("lblFaturamentoTitulo")
        self.cardFatVLayout.addWidget(self.lblFaturamentoTitulo)
        self.cardsHLayout.addWidget(self.cardFaturamento)
        self.cardProdutos = QtWidgets.QFrame(self.centralWidget)
        self.cardProdutos.setStyleSheet("QFrame#cardProdutos { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0a030, stop:1 #c87912); border-radius: 8px; }")
        self.cardProdutos.setObjectName("cardProdutos")
        self.cardProdVLayout = QtWidgets.QVBoxLayout(self.cardProdutos)
        self.cardProdVLayout.setContentsMargins(16, 14, 16, 14)
        self.cardProdVLayout.setSpacing(4)
        self.cardProdVLayout.setObjectName("cardProdVLayout")
        self.lblCardProdIcon = QtWidgets.QLabel(self.cardProdutos)
        self.lblCardProdIcon.setStyleSheet("font-size: 22px; color: white;")
        self.lblCardProdIcon.setObjectName("lblCardProdIcon")
        self.cardProdVLayout.addWidget(self.lblCardProdIcon)
        self.lblProdutosValor = QtWidgets.QLabel(self.cardProdutos)
        self.lblProdutosValor.setStyleSheet("color: white; font-size: 32px; font-weight: bold;")
        self.lblProdutosValor.setObjectName("lblProdutosValor")
        self.cardProdVLayout.addWidget(self.lblProdutosValor)
        self.lblProdutosTitulo = QtWidgets.QLabel(self.cardProdutos)
        self.lblProdutosTitulo.setStyleSheet("color: #fff1d6; font-size: 12px;")
        self.lblProdutosTitulo.setObjectName("lblProdutosTitulo")
        self.cardProdVLayout.addWidget(self.lblProdutosTitulo)
        self.cardsHLayout.addWidget(self.cardProdutos)
        self.cardClientes = QtWidgets.QFrame(self.centralWidget)
        self.cardClientes.setStyleSheet("QFrame#cardClientes { background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #8f62c7, stop:1 #6b4299); border-radius: 8px; }")
        self.cardClientes.setObjectName("cardClientes")
        self.cardCliVLayout = QtWidgets.QVBoxLayout(self.cardClientes)
        self.cardCliVLayout.setContentsMargins(16, 14, 16, 14)
        self.cardCliVLayout.setSpacing(4)
        self.cardCliVLayout.setObjectName("cardCliVLayout")
        self.lblCardCliIcon = QtWidgets.QLabel(self.cardClientes)
        self.lblCardCliIcon.setStyleSheet("font-size: 22px; color: white;")
        self.lblCardCliIcon.setObjectName("lblCardCliIcon")
        self.cardCliVLayout.addWidget(self.lblCardCliIcon)
        self.lblClientesValor = QtWidgets.QLabel(self.cardClientes)
        self.lblClientesValor.setStyleSheet("color: white; font-size: 32px; font-weight: bold;")
        self.lblClientesValor.setObjectName("lblClientesValor")
        self.cardCliVLayout.addWidget(self.lblClientesValor)
        self.lblClientesTitulo = QtWidgets.QLabel(self.cardClientes)
        self.lblClientesTitulo.setStyleSheet("color: #e6d9f4; font-size: 12px;")
        self.lblClientesTitulo.setObjectName("lblClientesTitulo")
        self.cardCliVLayout.addWidget(self.lblClientesTitulo)
        self.cardsHLayout.addWidget(self.cardClientes)
        self.mainContentVLayout.addLayout(self.cardsHLayout)
        self.bottomHLayout = QtWidgets.QHBoxLayout()
        self.bottomHLayout.setSpacing(12)
        self.bottomHLayout.setObjectName("bottomHLayout")
        self.frameUltimasVendas = QtWidgets.QFrame(self.centralWidget)
        self.frameUltimasVendas.setStyleSheet("\n"
"QFrame#frameUltimasVendas, QFrame#frameAcessoSistema, QFrame#frameConfiguracaoEstrutural {\n"
" background-color: white;\n"
" border: 1px solid #a8c4d8;\n"
" border-radius: 6px;\n"
"}\n"
"QLabel[panelTitle=\"true\"] {\n"
" background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0);\n"
" color: white;\n"
" font-size: 13px;\n"
" font-weight: bold;\n"
" padding: 6px 12px;\n"
" border-top-left-radius: 6px;\n"
" border-top-right-radius: 6px;\n"
"}\n"
"QTableWidget {\n"
" background-color: #ffffff;\n"
" border: none;\n"
" font-size: 12px;\n"
" gridline-color: #dce8f0;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" padding: 4px 6px;\n"
" border: none;\n"
" border-right: 1px solid #dce8f0;\n"
" border-bottom: 2px solid #3585c8;\n"
"}\n"
"QPushButton[actionButton=\"true\"] {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" border: 1px solid #c0d8ec;\n"
" border-radius: 4px;\n"
" padding: 8px 10px;\n"
" text-align: left;\n"
"}\n"
"QPushButton[actionButton=\"true\"]:hover {\n"
" background-color: #dceaf4;\n"
" border-color: #3585c8;\n"
" color: #1a5fa0;\n"
"}\n"
"           ")
        self.frameUltimasVendas.setObjectName("frameUltimasVendas")
        self.dashboardPanelsLayout = QtWidgets.QHBoxLayout(self.frameUltimasVendas)
        self.dashboardPanelsLayout.setContentsMargins(0, 0, 0, 0)
        self.dashboardPanelsLayout.setSpacing(12)
        self.dashboardPanelsLayout.setObjectName("dashboardPanelsLayout")
        self.panelUltimasVendas = QtWidgets.QFrame(self.frameUltimasVendas)
        self.panelUltimasVendas.setObjectName("panelUltimasVendas")
        self.panelUltimasVendasLayout = QtWidgets.QVBoxLayout(self.panelUltimasVendas)
        self.panelUltimasVendasLayout.setContentsMargins(0, 0, 0, 0)
        self.panelUltimasVendasLayout.setSpacing(0)
        self.panelUltimasVendasLayout.setObjectName("panelUltimasVendasLayout")
        self.lblUltimasVendasTitle = QtWidgets.QLabel(self.panelUltimasVendas)
        self.lblUltimasVendasTitle.setObjectName("lblUltimasVendasTitle")
        self.panelUltimasVendasLayout.addWidget(self.lblUltimasVendasTitle)
        self.tableUltimasVendas = QtWidgets.QTableWidget(self.panelUltimasVendas)
        self.tableUltimasVendas.setRowCount(0)
        self.tableUltimasVendas.setColumnCount(5)
        self.tableUltimasVendas.setObjectName("tableUltimasVendas")
        item = QtWidgets.QTableWidgetItem()
        self.tableUltimasVendas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUltimasVendas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUltimasVendas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUltimasVendas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUltimasVendas.setHorizontalHeaderItem(4, item)
        self.tableUltimasVendas.horizontalHeader().setStretchLastSection(True)
        self.panelUltimasVendasLayout.addWidget(self.tableUltimasVendas)
        self.dashboardPanelsLayout.addWidget(self.panelUltimasVendas)
        self.frameAcessoSistema = QtWidgets.QFrame(self.frameUltimasVendas)
        self.frameAcessoSistema.setMinimumSize(QtCore.QSize(320, 0))
        self.frameAcessoSistema.setObjectName("frameAcessoSistema")
        self.frameAcessoSistemaLayout = QtWidgets.QVBoxLayout(self.frameAcessoSistema)
        self.frameAcessoSistemaLayout.setContentsMargins(0, 0, 0, 0)
        self.frameAcessoSistemaLayout.setSpacing(0)
        self.frameAcessoSistemaLayout.setObjectName("frameAcessoSistemaLayout")
        self.lblAcoesTitle = QtWidgets.QLabel(self.frameAcessoSistema)
        self.lblAcoesTitle.setObjectName("lblAcoesTitle")
        self.frameAcessoSistemaLayout.addWidget(self.lblAcoesTitle)
        self.frameAcoesBtns = QtWidgets.QFrame(self.frameAcessoSistema)
        self.frameAcoesBtns.setObjectName("frameAcoesBtns")
        self.acoesBtnsVLayout = QtWidgets.QVBoxLayout(self.frameAcoesBtns)
        self.acoesBtnsVLayout.setContentsMargins(10, 10, 10, 10)
        self.acoesBtnsVLayout.setSpacing(6)
        self.acoesBtnsVLayout.setObjectName("acoesBtnsVLayout")
        self.btnAcaoCadProduto = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadProduto.setObjectName("btnAcaoCadProduto")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadProduto)
        self.btnAcaoBackup = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoBackup.setObjectName("btnAcaoBackup")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoBackup)
        self.btnAcaoConfig = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoConfig.setObjectName("btnAcaoConfig")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoConfig)
        self.btnAcaoCadFornecedor = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadFornecedor.setObjectName("btnAcaoCadFornecedor")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadFornecedor)
        self.btnAcaoCadCliente = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadCliente.setObjectName("btnAcaoCadCliente")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadCliente)
        self.btnAcaoCadFuncionario = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadFuncionario.setObjectName("btnAcaoCadFuncionario")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadFuncionario)
        self.btnAcaoCadUsuario = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadUsuario.setObjectName("btnAcaoCadUsuario")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadUsuario)
        self.btnAcaoCadPerfil = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadPerfil.setObjectName("btnAcaoCadPerfil")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadPerfil)
        self.btnAcaoCadPermissao = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadPermissao.setObjectName("btnAcaoCadPermissao")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadPermissao)
        self.btnAcaoCadCargo = QtWidgets.QPushButton(self.frameAcoesBtns)
        self.btnAcaoCadCargo.setObjectName("btnAcaoCadCargo")
        self.acoesBtnsVLayout.addWidget(self.btnAcaoCadCargo)
        self.frameAcessoSistemaLayout.addWidget(self.frameAcoesBtns)
        self.dashboardPanelsLayout.addWidget(self.frameAcessoSistema)
        self.frameConfiguracaoEstrutural = QtWidgets.QFrame(self.frameUltimasVendas)
        self.frameConfiguracaoEstrutural.setMinimumSize(QtCore.QSize(320, 0))
        self.frameConfiguracaoEstrutural.setObjectName("frameConfiguracaoEstrutural")
        self.frameConfiguracaoEstruturalLayout = QtWidgets.QVBoxLayout(self.frameConfiguracaoEstrutural)
        self.frameConfiguracaoEstruturalLayout.setContentsMargins(0, 0, 0, 0)
        self.frameConfiguracaoEstruturalLayout.setSpacing(0)
        self.frameConfiguracaoEstruturalLayout.setObjectName("frameConfiguracaoEstruturalLayout")
        self.lblConfigEstruturalTitle = QtWidgets.QLabel(self.frameConfiguracaoEstrutural)
        self.lblConfigEstruturalTitle.setMinimumSize(QtCore.QSize(0, 52))
        self.lblConfigEstruturalTitle.setMaximumSize(QtCore.QSize(16777215, 52))
        self.lblConfigEstruturalTitle.setStyleSheet("\n"
"QLabel {\n"
" background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0);\n"
" color: white;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" padding: 4px 12px;\n"
" border-top-left-radius: 6px;\n"
" border-top-right-radius: 6px;\n"
"}\n"
"        ")
        self.lblConfigEstruturalTitle.setObjectName("lblConfigEstruturalTitle")
        self.frameConfiguracaoEstruturalLayout.addWidget(self.lblConfigEstruturalTitle)
        self.frameEstruturalBody = QtWidgets.QFrame(self.frameConfiguracaoEstrutural)
        self.frameEstruturalBody.setObjectName("frameEstruturalBody")
        self.frameEstruturalBodyLayout = QtWidgets.QVBoxLayout(self.frameEstruturalBody)
        self.frameEstruturalBodyLayout.setContentsMargins(14, 14, 14, 14)
        self.frameEstruturalBodyLayout.setSpacing(10)
        self.frameEstruturalBodyLayout.setObjectName("frameEstruturalBodyLayout")
        self.lblResumoUsuarios = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoUsuarios.setStyleSheet("font-size: 12px; color: #486a86;")
        self.lblResumoUsuarios.setWordWrap(True)
        self.lblResumoUsuarios.setObjectName("lblResumoUsuarios")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoUsuarios)
        self.lblResumoPerfis = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoPerfis.setStyleSheet("font-size: 12px; color: #486a86;")
        self.lblResumoPerfis.setWordWrap(True)
        self.lblResumoPerfis.setObjectName("lblResumoPerfis")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoPerfis)
        self.lblResumoPdvs = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoPdvs.setStyleSheet("font-size: 12px; color: #486a86;")
        self.lblResumoPdvs.setWordWrap(True)
        self.lblResumoPdvs.setObjectName("lblResumoPdvs")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoPdvs)
        self.lblResumoCaixas = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoCaixas.setStyleSheet("font-size: 12px; color: #486a86;")
        self.lblResumoCaixas.setWordWrap(True)
        self.lblResumoCaixas.setObjectName("lblResumoCaixas")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoCaixas)
        self.lblResumoFormasPagamento = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoFormasPagamento.setStyleSheet("font-size: 12px; color: #486a86;")
        self.lblResumoFormasPagamento.setWordWrap(True)
        self.lblResumoFormasPagamento.setObjectName("lblResumoFormasPagamento")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoFormasPagamento)
        self.lineResumoAlertas = QtWidgets.QFrame(self.frameEstruturalBody)
        self.lineResumoAlertas.setMinimumSize(QtCore.QSize(0, 1))
        self.lineResumoAlertas.setMaximumSize(QtCore.QSize(16777215, 1))
        self.lineResumoAlertas.setStyleSheet("background-color:#d8e5f0;border:none;")
        self.lineResumoAlertas.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineResumoAlertas.setObjectName("lineResumoAlertas")
        self.frameEstruturalBodyLayout.addWidget(self.lineResumoAlertas)
        self.lblResumoAlertasTitulo = QtWidgets.QLabel(self.frameEstruturalBody)
        self.lblResumoAlertasTitulo.setStyleSheet("font-size: 12px; font-weight: bold; color: #1a3a5c; padding-top: 2px;")
        self.lblResumoAlertasTitulo.setObjectName("lblResumoAlertasTitulo")
        self.frameEstruturalBodyLayout.addWidget(self.lblResumoAlertasTitulo)
        self.btnResumoAlerta1 = QtWidgets.QPushButton(self.frameEstruturalBody)
        self.btnResumoAlerta1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResumoAlerta1.setStyleSheet("QPushButton { font-size: 12px; color: #7a2e0b; text-align: left; border: none; background: transparent; padding: 0px; } QPushButton:hover { text-decoration: underline; }")
        self.btnResumoAlerta1.setFlat(True)
        self.btnResumoAlerta1.setObjectName("btnResumoAlerta1")
        self.frameEstruturalBodyLayout.addWidget(self.btnResumoAlerta1)
        self.btnResumoAlerta2 = QtWidgets.QPushButton(self.frameEstruturalBody)
        self.btnResumoAlerta2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResumoAlerta2.setStyleSheet("QPushButton { font-size: 12px; color: #7a2e0b; text-align: left; border: none; background: transparent; padding: 0px; } QPushButton:hover { text-decoration: underline; }")
        self.btnResumoAlerta2.setFlat(True)
        self.btnResumoAlerta2.setObjectName("btnResumoAlerta2")
        self.frameEstruturalBodyLayout.addWidget(self.btnResumoAlerta2)
        self.btnResumoAlerta3 = QtWidgets.QPushButton(self.frameEstruturalBody)
        self.btnResumoAlerta3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResumoAlerta3.setStyleSheet("QPushButton { font-size: 12px; color: #7a2e0b; text-align: left; border: none; background: transparent; padding: 0px; } QPushButton:hover { text-decoration: underline; }")
        self.btnResumoAlerta3.setFlat(True)
        self.btnResumoAlerta3.setObjectName("btnResumoAlerta3")
        self.frameEstruturalBodyLayout.addWidget(self.btnResumoAlerta3)
        self.btnResumoAlerta4 = QtWidgets.QPushButton(self.frameEstruturalBody)
        self.btnResumoAlerta4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnResumoAlerta4.setStyleSheet("QPushButton { font-size: 12px; color: #7a2e0b; text-align: left; border: none; background: transparent; padding: 0px; } QPushButton:hover { text-decoration: underline; }")
        self.btnResumoAlerta4.setFlat(True)
        self.btnResumoAlerta4.setObjectName("btnResumoAlerta4")
        self.frameEstruturalBodyLayout.addWidget(self.btnResumoAlerta4)
        self.frameConfiguracaoEstruturalLayout.addWidget(self.frameEstruturalBody)
        self.dashboardPanelsLayout.addWidget(self.frameConfiguracaoEstrutural)
        self.bottomHLayout.addWidget(self.frameUltimasVendas)
        self.mainContentVLayout.addLayout(self.bottomHLayout)
        self.mainVLayout.addLayout(self.mainContentVLayout)
        self.frameStatusBar = QtWidgets.QFrame(self.centralWidget)
        self.frameStatusBar.setStyleSheet("\n"
"QFrame#frameStatusBar {\n"
" background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #153552, stop:1 #2f75b0);\n"
"}\n"
"       ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusHLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusHLayout.setContentsMargins(12, 0, 12, 0)
        self.statusHLayout.setObjectName("statusHLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setStyleSheet("color: #8ff09a; font-size: 11px; font-weight: 700;")
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusHLayout.addWidget(self.lblStatusSistema)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem4)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setStyleSheet("color: white; font-size: 11px; font-weight: 600;")
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusHLayout.addWidget(self.lblStatusBar)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem5)
        self.lblStatusVersao = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusVersao.setStyleSheet("color: #dbeaf7; font-size: 11px;")
        self.lblStatusVersao.setObjectName("lblStatusVersao")
        self.statusHLayout.addWidget(self.lblStatusVersao)
        self.mainVLayout.addWidget(self.frameStatusBar)
        PainelAdmin.setCentralWidget(self.centralWidget)

        self.retranslateUi(PainelAdmin)
        QtCore.QMetaObject.connectSlotsByName(PainelAdmin)

    def retranslateUi(self, PainelAdmin):
        _translate = QtCore.QCoreApplication.translate
        PainelAdmin.setWindowTitle(_translate("PainelAdmin", "CSPdv - Painel Administrativo"))
        self.lblLogo.setText(_translate("PainelAdmin", "CSPdv"))
        self.lblBadgeAdmin.setText(_translate("PainelAdmin", "ADMINISTRAÇÃO CENTRAL"))
        self.lblOperadorInfo.setText(_translate("PainelAdmin", "Operador: ADMIN"))
        self.lblDataHora.setText(_translate("PainelAdmin", "--/--/---- --:--:--"))
        self.btnSair.setText(_translate("PainelAdmin", "Sair"))
        self.btnNavDashboard.setText(_translate("PainelAdmin", "Dashboard"))
        self.btnNavProdutos.setText(_translate("PainelAdmin", "Cadastros"))
        self.btnNavUsuarios.setText(_translate("PainelAdmin", "Acesso"))
        self.btnNavVendas.setText(_translate("PainelAdmin", "Financeiro"))
        self.btnNavClientes.setText(_translate("PainelAdmin", "Relacionamento"))
        self.btnNavLotes.setText(_translate("PainelAdmin", "Operação e Fiscal"))
        self.btnNavProdutosCadastro.setText(_translate("PainelAdmin", "(F1) Produtos"))
        self.btnNavMarcas.setText(_translate("PainelAdmin", "(F2) Marcas"))
        self.btnNavFornecedores.setText(_translate("PainelAdmin", "(F3) Fornecedores"))
        self.btnNavCategorias.setText(_translate("PainelAdmin", "(F4) Categorias"))
        self.btnNavClientesCadastro.setText(_translate("PainelAdmin", "(F5) Clientes"))
        self.btnNavPerfis.setText(_translate("PainelAdmin", "Perfis"))
        self.btnNavPermissoes.setText(_translate("PainelAdmin", "Permissões"))
        self.btnNavCargos.setText(_translate("PainelAdmin", "Cargos"))
        self.btnNavFormasPagamento.setText(_translate("PainelAdmin", "Formas de Pagamento"))
        self.btnNavCaixas.setText(_translate("PainelAdmin", "Caixas"))
        self.btnNavFiscal.setText(_translate("PainelAdmin", "Parâmetros Fiscais"))
        self.btnNavUnidades.setText(_translate("PainelAdmin", "Unidades"))
        self.btnNavPdvs.setText(_translate("PainelAdmin", "PDVs"))
        self.btnNavConfiguracoes.setText(_translate("PainelAdmin", "Configurações"))
        self.lblSectionTitle.setText(_translate("PainelAdmin", "Dashboard Administrativo"))
        self.btnFrenteCaixa.setText(_translate("PainelAdmin", "Abrir Frente de Caixa"))
        self.lblCardVendasIcon.setText(_translate("PainelAdmin", "V"))
        self.lblVendasHojeValor.setText(_translate("PainelAdmin", "0"))
        self.lblVendasHojeTitulo.setText(_translate("PainelAdmin", "Vendas processadas hoje"))
        self.lblCardFatIcon.setText(_translate("PainelAdmin", "R$"))
        self.lblFaturamentoValor.setText(_translate("PainelAdmin", "R$ 0,00"))
        self.lblFaturamentoTitulo.setText(_translate("PainelAdmin", "Faturamento do dia"))
        self.lblCardProdIcon.setText(_translate("PainelAdmin", "📦"))
        self.lblProdutosValor.setText(_translate("PainelAdmin", "0"))
        self.lblProdutosTitulo.setText(_translate("PainelAdmin", "Produtos ativos"))
        self.lblCardCliIcon.setText(_translate("PainelAdmin", "👥"))
        self.lblClientesValor.setText(_translate("PainelAdmin", "0"))
        self.lblClientesTitulo.setText(_translate("PainelAdmin", "Clientes ativos"))
        self.lblUltimasVendasTitle.setText(_translate("PainelAdmin", "Últimas Vendas"))
        self.lblUltimasVendasTitle.setProperty("panelTitle", _translate("PainelAdmin", "true"))
        item = self.tableUltimasVendas.horizontalHeaderItem(0)
        item.setText(_translate("PainelAdmin", "N. Venda"))
        item = self.tableUltimasVendas.horizontalHeaderItem(1)
        item.setText(_translate("PainelAdmin", "Data / Hora"))
        item = self.tableUltimasVendas.horizontalHeaderItem(2)
        item.setText(_translate("PainelAdmin", "Operador"))
        item = self.tableUltimasVendas.horizontalHeaderItem(3)
        item.setText(_translate("PainelAdmin", "Forma Pgto."))
        item = self.tableUltimasVendas.horizontalHeaderItem(4)
        item.setText(_translate("PainelAdmin", "Total (R$)"))
        self.lblAcoesTitle.setText(_translate("PainelAdmin", "Ações Rápidas"))
        self.lblAcoesTitle.setProperty("panelTitle", _translate("PainelAdmin", "true"))
        self.btnAcaoCadProduto.setText(_translate("PainelAdmin", "📦   Cadastrar Produto"))
        self.btnAcaoCadProduto.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadCliente.setText(_translate("PainelAdmin", "👤   Cadastrar Cliente"))
        self.btnAcaoCadCliente.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadUsuario.setText(_translate("PainelAdmin", "🔑   Cadastrar Usuário"))
        self.btnAcaoCadUsuario.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadFornecedor.setText(_translate("PainelAdmin", "🚚   Cadastrar Fornecedor"))
        self.btnAcaoCadFornecedor.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadFuncionario.setText(_translate("PainelAdmin", "🧑   Cadastrar Funcionário"))
        self.btnAcaoCadFuncionario.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadPerfil.setText(_translate("PainelAdmin", "🛡   Cadastrar Perfil"))
        self.btnAcaoCadPerfil.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadPermissao.setText(_translate("PainelAdmin", "✅   Gerenciar Permissões"))
        self.btnAcaoCadPermissao.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoCadCargo.setText(_translate("PainelAdmin", "🧾   Gerenciar Cargos"))
        self.btnAcaoCadCargo.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoBackup.setText(_translate("PainelAdmin", "🏷   Cadastrar Marca"))
        self.btnAcaoBackup.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.btnAcaoConfig.setText(_translate("PainelAdmin", "🗂   Cadastrar Categoria"))
        self.btnAcaoConfig.setProperty("actionButton", _translate("PainelAdmin", "true"))
        self.lblConfigEstruturalTitle.setText(_translate("PainelAdmin", "Status da Estrutura"))
        self.lblConfigEstruturalTitle.setProperty("panelTitle", _translate("PainelAdmin", "true"))
        self.lblResumoUsuarios.setText(_translate("PainelAdmin", "Usuários ativos: 0"))
        self.lblResumoPerfis.setText(_translate("PainelAdmin", "Perfis ativos: 0"))
        self.lblResumoPdvs.setText(_translate("PainelAdmin", "PDVs ativos: 0"))
        self.lblResumoCaixas.setText(_translate("PainelAdmin", "Caixas abertos: 0"))
        self.lblResumoFormasPagamento.setText(_translate("PainelAdmin", "Formas de pagamento: 0"))
        self.lblResumoAlertasTitulo.setText(_translate("PainelAdmin", "Alertas"))
        self.btnResumoAlerta1.setText(_translate("PainelAdmin", "Nenhum alerta estrutural no momento."))
        self.btnResumoAlerta2.setText(_translate("PainelAdmin", ""))
        self.btnResumoAlerta3.setText(_translate("PainelAdmin", ""))
        self.btnResumoAlerta4.setText(_translate("PainelAdmin", ""))
        self.lblStatusSistema.setText(_translate("PainelAdmin", "● Sistema Online"))
        self.lblStatusBar.setText(_translate("PainelAdmin", "CSPdv - Operador: ADMIN  |  Painel Administrativo"))
        self.lblStatusVersao.setText(_translate("PainelAdmin", "v1.0.0"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PainelAdmin = QtWidgets.QMainWindow()
    ui = Ui_PainelAdmin()
    ui.setupUi(PainelAdmin)
    PainelAdmin.show()
    sys.exit(app.exec_())
