# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'painel_estoque.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PainelEstoque(object):
    def setupUi(self, PainelEstoque):
        PainelEstoque.setObjectName("PainelEstoque")
        PainelEstoque.resize(1366, 768)
        self.centralWidget = QtWidgets.QWidget(PainelEstoque)
        self.centralWidget.setObjectName("centralWidget")
        self.mainVLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainVLayout.setContentsMargins(0, 0, 0, 0)
        self.mainVLayout.setSpacing(0)
        self.mainVLayout.setObjectName("mainVLayout")
        self.frameHeader = QtWidgets.QFrame(self.centralWidget)
        self.frameHeader.setStyleSheet("\n"
"QFrame#frameHeader {\n"
" background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0);\n"
"}\n"
"QLabel#lblLogo {\n"
" color: white;\n"
" font-size: 28px;\n"
" font-weight: bold;\n"
"}\n"
"QLabel#lblModulo {\n"
" color: #ffe39a;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
" background-color: rgba(255,255,255,30);\n"
" border: 1px solid rgba(255,255,255,60);\n"
" border-radius: 4px;\n"
" padding: 3px 10px;\n"
"}\n"
"QLabel#lblOperadorInfo, QLabel#lblDataHora {\n"
" color: #d9ebfb;\n"
" font-size: 11px;\n"
"}\n"
"QPushButton#btnVoltarSelecao {\n"
" background-color: #cc2222;\n"
" color: white;\n"
" border: none;\n"
" border-radius: 4px;\n"
" padding: 6px 12px;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
"}\n"
"QPushButton#btnVoltarSelecao:hover {\n"
" background-color: #e03030;\n"
"}\n"
"       ")
        self.frameHeader.setObjectName("frameHeader")
        self.headerHLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.headerHLayout.setContentsMargins(14, 8, 14, 8)
        self.headerHLayout.setObjectName("headerHLayout")
        self.lblLogo = QtWidgets.QLabel(self.frameHeader)
        self.lblLogo.setObjectName("lblLogo")
        self.headerHLayout.addWidget(self.lblLogo)
        self.frameSepHeader = QtWidgets.QFrame(self.frameHeader)
        self.frameSepHeader.setStyleSheet("background-color: rgba(255,255,255,80);")
        self.frameSepHeader.setFrameShape(QtWidgets.QFrame.VLine)
        self.frameSepHeader.setObjectName("frameSepHeader")
        self.headerHLayout.addWidget(self.frameSepHeader)
        self.lblModulo = QtWidgets.QLabel(self.frameHeader)
        self.lblModulo.setObjectName("lblModulo")
        self.headerHLayout.addWidget(self.lblModulo)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerHLayout.addItem(spacerItem)
        self.lblOperadorInfo = QtWidgets.QLabel(self.frameHeader)
        self.lblOperadorInfo.setObjectName("lblOperadorInfo")
        self.headerHLayout.addWidget(self.lblOperadorInfo)
        self.lblDataHora = QtWidgets.QLabel(self.frameHeader)
        self.lblDataHora.setObjectName("lblDataHora")
        self.headerHLayout.addWidget(self.lblDataHora)
        self.btnVoltarSelecao = QtWidgets.QPushButton(self.frameHeader)
        self.btnVoltarSelecao.setMinimumSize(QtCore.QSize(96, 34))
        self.btnVoltarSelecao.setObjectName("btnVoltarSelecao")
        self.headerHLayout.addWidget(self.btnVoltarSelecao)
        self.mainVLayout.addWidget(self.frameHeader)
        self.frameToolbar = QtWidgets.QFrame(self.centralWidget)
        self.frameToolbar.setMinimumSize(QtCore.QSize(0, 56))
        self.frameToolbar.setStyleSheet("\n"
"QFrame#frameToolbar { background-color: #f0f6fc; border-bottom: 1px solid #c8d8e8; }\n"
"QLineEdit, QComboBox {\n"
" background-color: white;\n"
" border: 1px solid #b8cde0;\n"
" border-radius: 4px;\n"
" padding: 6px 8px;\n"
" font-size: 12px;\n"
"}\n"
"QPushButton {\n"
" background-color: #3585c8;\n"
" color: white;\n"
" border: none;\n"
" border-radius: 4px;\n"
" padding: 6px 12px;\n"
" font-size: 12px;\n"
" font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #2b74b4; }\n"
"QPushButton#btnAjusteEstoque { background-color: #f0a030; color: #1d2430; }\n"
"QPushButton#btnAjusteEstoque:hover { background-color: #d88b20; }\n"
"       ")
        self.frameToolbar.setObjectName("frameToolbar")
        self.toolbarHLayout = QtWidgets.QHBoxLayout(self.frameToolbar)
        self.toolbarHLayout.setContentsMargins(16, 10, 16, 10)
        self.toolbarHLayout.setObjectName("toolbarHLayout")
        self.txtBuscaProduto = QtWidgets.QLineEdit(self.frameToolbar)
        self.txtBuscaProduto.setObjectName("txtBuscaProduto")
        self.toolbarHLayout.addWidget(self.txtBuscaProduto)
        self.cmbCategoriaFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbCategoriaFiltro.setObjectName("cmbCategoriaFiltro")
        self.cmbCategoriaFiltro.addItem("")
        self.toolbarHLayout.addWidget(self.cmbCategoriaFiltro)
        self.cmbFornecedorFiltro = QtWidgets.QComboBox(self.frameToolbar)
        self.cmbFornecedorFiltro.setObjectName("cmbFornecedorFiltro")
        self.cmbFornecedorFiltro.addItem("")
        self.toolbarHLayout.addWidget(self.cmbFornecedorFiltro)
        self.btnFiltrar = QtWidgets.QPushButton(self.frameToolbar)
        self.btnFiltrar.setObjectName("btnFiltrar")
        self.toolbarHLayout.addWidget(self.btnFiltrar)
        self.btnNovoProduto = QtWidgets.QPushButton(self.frameToolbar)
        self.btnNovoProduto.setObjectName("btnNovoProduto")
        self.toolbarHLayout.addWidget(self.btnNovoProduto)
        self.btnNovoLote = QtWidgets.QPushButton(self.frameToolbar)
        self.btnNovoLote.setObjectName("btnNovoLote")
        self.toolbarHLayout.addWidget(self.btnNovoLote)
        self.btnAjusteEstoque = QtWidgets.QPushButton(self.frameToolbar)
        self.btnAjusteEstoque.setObjectName("btnAjusteEstoque")
        self.toolbarHLayout.addWidget(self.btnAjusteEstoque)
        self.mainVLayout.addWidget(self.frameToolbar)
        self.contentVLayout = QtWidgets.QVBoxLayout()
        self.contentVLayout.setContentsMargins(16, 14, 16, 14)
        self.contentVLayout.setSpacing(12)
        self.contentVLayout.setObjectName("contentVLayout")
        self.cardsHLayout = QtWidgets.QHBoxLayout()
        self.cardsHLayout.setSpacing(12)
        self.cardsHLayout.setObjectName("cardsHLayout")
        self.cardProdutosAtivos = QtWidgets.QFrame(self.centralWidget)
        self.cardProdutosAtivos.setStyleSheet("\n"
"QFrame#cardProdutosAtivos { background-color: #3585c8; border-radius: 8px; }\n"
"QLabel { color: white; }\n"
"QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; }\n"
"QLabel[role=\"title\"] { color: #d8ebfb; font-size: 12px; }\n"
"           ")
        self.cardProdutosAtivos.setObjectName("cardProdutosAtivos")
        self.cardProdutosAtivosLayout = QtWidgets.QVBoxLayout(self.cardProdutosAtivos)
        self.cardProdutosAtivosLayout.setContentsMargins(16, 14, 16, 14)
        self.cardProdutosAtivosLayout.setObjectName("cardProdutosAtivosLayout")
        self.lblProdutosAtivosValor = QtWidgets.QLabel(self.cardProdutosAtivos)
        self.lblProdutosAtivosValor.setObjectName("lblProdutosAtivosValor")
        self.cardProdutosAtivosLayout.addWidget(self.lblProdutosAtivosValor)
        self.lblProdutosAtivosTitulo = QtWidgets.QLabel(self.cardProdutosAtivos)
        self.lblProdutosAtivosTitulo.setObjectName("lblProdutosAtivosTitulo")
        self.cardProdutosAtivosLayout.addWidget(self.lblProdutosAtivosTitulo)
        self.cardsHLayout.addWidget(self.cardProdutosAtivos)
        self.cardLotesAtivos = QtWidgets.QFrame(self.centralWidget)
        self.cardLotesAtivos.setStyleSheet("\n"
"QFrame#cardLotesAtivos { background-color: #5cb85c; border-radius: 8px; }\n"
"QLabel { color: white; }\n"
"QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; }\n"
"QLabel[role=\"title\"] { color: #daf0da; font-size: 12px; }\n"
"           ")
        self.cardLotesAtivos.setObjectName("cardLotesAtivos")
        self.cardLotesAtivosLayout = QtWidgets.QVBoxLayout(self.cardLotesAtivos)
        self.cardLotesAtivosLayout.setContentsMargins(16, 14, 16, 14)
        self.cardLotesAtivosLayout.setObjectName("cardLotesAtivosLayout")
        self.lblLotesAtivosValor = QtWidgets.QLabel(self.cardLotesAtivos)
        self.lblLotesAtivosValor.setObjectName("lblLotesAtivosValor")
        self.cardLotesAtivosLayout.addWidget(self.lblLotesAtivosValor)
        self.lblLotesAtivosTitulo = QtWidgets.QLabel(self.cardLotesAtivos)
        self.lblLotesAtivosTitulo.setObjectName("lblLotesAtivosTitulo")
        self.cardLotesAtivosLayout.addWidget(self.lblLotesAtivosTitulo)
        self.cardsHLayout.addWidget(self.cardLotesAtivos)
        self.cardItensBaixoEstoque = QtWidgets.QFrame(self.centralWidget)
        self.cardItensBaixoEstoque.setStyleSheet("\n"
"QFrame#cardItensBaixoEstoque { background-color: #f0a030; border-radius: 8px; }\n"
"QLabel { color: #13202c; }\n"
"QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; }\n"
"QLabel[role=\"title\"] { color: #523b10; font-size: 12px; }\n"
"           ")
        self.cardItensBaixoEstoque.setObjectName("cardItensBaixoEstoque")
        self.cardItensBaixoEstoqueLayout = QtWidgets.QVBoxLayout(self.cardItensBaixoEstoque)
        self.cardItensBaixoEstoqueLayout.setContentsMargins(16, 14, 16, 14)
        self.cardItensBaixoEstoqueLayout.setObjectName("cardItensBaixoEstoqueLayout")
        self.lblItensBaixoEstoqueValor = QtWidgets.QLabel(self.cardItensBaixoEstoque)
        self.lblItensBaixoEstoqueValor.setObjectName("lblItensBaixoEstoqueValor")
        self.cardItensBaixoEstoqueLayout.addWidget(self.lblItensBaixoEstoqueValor)
        self.lblItensBaixoEstoqueTitulo = QtWidgets.QLabel(self.cardItensBaixoEstoque)
        self.lblItensBaixoEstoqueTitulo.setObjectName("lblItensBaixoEstoqueTitulo")
        self.cardItensBaixoEstoqueLayout.addWidget(self.lblItensBaixoEstoqueTitulo)
        self.cardsHLayout.addWidget(self.cardItensBaixoEstoque)
        self.cardMovimentacoesDia = QtWidgets.QFrame(self.centralWidget)
        self.cardMovimentacoesDia.setStyleSheet("\n"
"QFrame#cardMovimentacoesDia { background-color: #6c7ea0; border-radius: 8px; }\n"
"QLabel { color: white; }\n"
"QLabel[role=\"value\"] { font-size: 28px; font-weight: bold; }\n"
"QLabel[role=\"title\"] { color: #d7def0; font-size: 12px; }\n"
"           ")
        self.cardMovimentacoesDia.setObjectName("cardMovimentacoesDia")
        self.cardMovimentacoesDiaLayout = QtWidgets.QVBoxLayout(self.cardMovimentacoesDia)
        self.cardMovimentacoesDiaLayout.setContentsMargins(16, 14, 16, 14)
        self.cardMovimentacoesDiaLayout.setObjectName("cardMovimentacoesDiaLayout")
        self.lblMovimentacoesDiaValor = QtWidgets.QLabel(self.cardMovimentacoesDia)
        self.lblMovimentacoesDiaValor.setObjectName("lblMovimentacoesDiaValor")
        self.cardMovimentacoesDiaLayout.addWidget(self.lblMovimentacoesDiaValor)
        self.lblMovimentacoesDiaTitulo = QtWidgets.QLabel(self.cardMovimentacoesDia)
        self.lblMovimentacoesDiaTitulo.setObjectName("lblMovimentacoesDiaTitulo")
        self.cardMovimentacoesDiaLayout.addWidget(self.lblMovimentacoesDiaTitulo)
        self.cardsHLayout.addWidget(self.cardMovimentacoesDia)
        self.contentVLayout.addLayout(self.cardsHLayout)
        self.tablesHLayout = QtWidgets.QHBoxLayout()
        self.tablesHLayout.setSpacing(12)
        self.tablesHLayout.setObjectName("tablesHLayout")
        self.frameProdutos = QtWidgets.QFrame(self.centralWidget)
        self.frameProdutos.setStyleSheet("\n"
"QFrame#frameProdutos, QFrame#frameMovimentacoes {\n"
" background-color: #ffffff;\n"
" border: 1px solid #b8cde0;\n"
" border-radius: 6px;\n"
"}\n"
"QLabel[sectionTitle=\"true\"] {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 13px;\n"
" font-weight: bold;\n"
" padding: 8px 12px;\n"
" border-bottom: 1px solid #d8e3ee;\n"
"}\n"
"QTableWidget {\n"
" border: none;\n"
" background-color: white;\n"
" gridline-color: #dce8f0;\n"
" font-size: 12px;\n"
"}\n"
"QHeaderView::section {\n"
" background-color: #f0f6fc;\n"
" color: #1a3a5c;\n"
" font-size: 11px;\n"
" font-weight: bold;\n"
" border: none;\n"
" border-right: 1px solid #dce8f0;\n"
" border-bottom: 2px solid #3585c8;\n"
" padding: 5px 6px;\n"
"}\n"
"           ")
        self.frameProdutos.setObjectName("frameProdutos")
        self.frameProdutosLayout = QtWidgets.QVBoxLayout(self.frameProdutos)
        self.frameProdutosLayout.setContentsMargins(0, 0, 0, 0)
        self.frameProdutosLayout.setSpacing(0)
        self.frameProdutosLayout.setObjectName("frameProdutosLayout")
        self.lblProdutosSection = QtWidgets.QLabel(self.frameProdutos)
        self.lblProdutosSection.setObjectName("lblProdutosSection")
        self.frameProdutosLayout.addWidget(self.lblProdutosSection)
        self.tableProdutosEstoque = QtWidgets.QTableWidget(self.frameProdutos)
        self.tableProdutosEstoque.setRowCount(0)
        self.tableProdutosEstoque.setColumnCount(8)
        self.tableProdutosEstoque.setObjectName("tableProdutosEstoque")
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProdutosEstoque.setHorizontalHeaderItem(7, item)
        self.tableProdutosEstoque.horizontalHeader().setStretchLastSection(True)
        self.frameProdutosLayout.addWidget(self.tableProdutosEstoque)
        self.tablesHLayout.addWidget(self.frameProdutos)
        self.frameMovimentacoes = QtWidgets.QFrame(self.centralWidget)
        self.frameMovimentacoes.setMinimumSize(QtCore.QSize(420, 0))
        self.frameMovimentacoes.setObjectName("frameMovimentacoes")
        self.frameMovimentacoesLayout = QtWidgets.QVBoxLayout(self.frameMovimentacoes)
        self.frameMovimentacoesLayout.setContentsMargins(0, 0, 0, 0)
        self.frameMovimentacoesLayout.setSpacing(0)
        self.frameMovimentacoesLayout.setObjectName("frameMovimentacoesLayout")
        self.lblMovimentacoesSection = QtWidgets.QLabel(self.frameMovimentacoes)
        self.lblMovimentacoesSection.setObjectName("lblMovimentacoesSection")
        self.frameMovimentacoesLayout.addWidget(self.lblMovimentacoesSection)
        self.tableMovimentacoesEstoque = QtWidgets.QTableWidget(self.frameMovimentacoes)
        self.tableMovimentacoesEstoque.setRowCount(0)
        self.tableMovimentacoesEstoque.setColumnCount(5)
        self.tableMovimentacoesEstoque.setObjectName("tableMovimentacoesEstoque")
        item = QtWidgets.QTableWidgetItem()
        self.tableMovimentacoesEstoque.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMovimentacoesEstoque.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMovimentacoesEstoque.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMovimentacoesEstoque.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMovimentacoesEstoque.setHorizontalHeaderItem(4, item)
        self.tableMovimentacoesEstoque.horizontalHeader().setStretchLastSection(True)
        self.frameMovimentacoesLayout.addWidget(self.tableMovimentacoesEstoque)
        self.tablesHLayout.addWidget(self.frameMovimentacoes)
        self.contentVLayout.addLayout(self.tablesHLayout)
        self.mainVLayout.addLayout(self.contentVLayout)
        self.frameStatusBar = QtWidgets.QFrame(self.centralWidget)
        self.frameStatusBar.setStyleSheet("\n"
"QFrame#frameStatusBar {\n"
" background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3585c8, stop:1 #1a5fa0);\n"
"}\n"
"QLabel { color: white; font-size: 11px; }\n"
"QLabel#lblStatusSistema { color: #80ff80; font-weight: bold; }\n"
"       ")
        self.frameStatusBar.setObjectName("frameStatusBar")
        self.statusHLayout = QtWidgets.QHBoxLayout(self.frameStatusBar)
        self.statusHLayout.setContentsMargins(12, -1, 12, -1)
        self.statusHLayout.setObjectName("statusHLayout")
        self.lblStatusSistema = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusSistema.setObjectName("lblStatusSistema")
        self.statusHLayout.addWidget(self.lblStatusSistema)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusHLayout.addItem(spacerItem1)
        self.lblStatusBar = QtWidgets.QLabel(self.frameStatusBar)
        self.lblStatusBar.setObjectName("lblStatusBar")
        self.statusHLayout.addWidget(self.lblStatusBar)
        self.mainVLayout.addWidget(self.frameStatusBar)
        PainelEstoque.setCentralWidget(self.centralWidget)

        self.retranslateUi(PainelEstoque)
        QtCore.QMetaObject.connectSlotsByName(PainelEstoque)

    def retranslateUi(self, PainelEstoque):
        _translate = QtCore.QCoreApplication.translate
        PainelEstoque.setWindowTitle(_translate("PainelEstoque", "CSPdv - Estoque"))
        self.lblLogo.setText(_translate("PainelEstoque", "CSPdv"))
        self.lblModulo.setText(_translate("PainelEstoque", "ESTOQUE E MOVIMENTACOES"))
        self.lblOperadorInfo.setText(_translate("PainelEstoque", "Operador: ---"))
        self.lblDataHora.setText(_translate("PainelEstoque", "--/--/---- --:--:--"))
        self.btnVoltarSelecao.setText(_translate("PainelEstoque", "Voltar"))
        self.txtBuscaProduto.setPlaceholderText(_translate("PainelEstoque", "Buscar por produto, codigo de barras ou lote"))
        self.cmbCategoriaFiltro.setItemText(0, _translate("PainelEstoque", "Todas as categorias"))
        self.cmbFornecedorFiltro.setItemText(0, _translate("PainelEstoque", "Todos os fornecedores"))
        self.btnFiltrar.setText(_translate("PainelEstoque", "Filtrar"))
        self.btnNovoProduto.setText(_translate("PainelEstoque", "Novo Produto"))
        self.btnNovoLote.setText(_translate("PainelEstoque", "Novo Lote"))
        self.btnAjusteEstoque.setText(_translate("PainelEstoque", "Ajuste de Estoque"))
        self.lblProdutosAtivosValor.setProperty("role", _translate("PainelEstoque", "value"))
        self.lblProdutosAtivosValor.setText(_translate("PainelEstoque", "0"))
        self.lblProdutosAtivosTitulo.setProperty("role", _translate("PainelEstoque", "title"))
        self.lblProdutosAtivosTitulo.setText(_translate("PainelEstoque", "Produtos Ativos"))
        self.lblLotesAtivosValor.setProperty("role", _translate("PainelEstoque", "value"))
        self.lblLotesAtivosValor.setText(_translate("PainelEstoque", "0"))
        self.lblLotesAtivosTitulo.setProperty("role", _translate("PainelEstoque", "title"))
        self.lblLotesAtivosTitulo.setText(_translate("PainelEstoque", "Lotes Ativos"))
        self.lblItensBaixoEstoqueValor.setProperty("role", _translate("PainelEstoque", "value"))
        self.lblItensBaixoEstoqueValor.setText(_translate("PainelEstoque", "0"))
        self.lblItensBaixoEstoqueTitulo.setProperty("role", _translate("PainelEstoque", "title"))
        self.lblItensBaixoEstoqueTitulo.setText(_translate("PainelEstoque", "Produtos com Estoque Critico"))
        self.lblMovimentacoesDiaValor.setProperty("role", _translate("PainelEstoque", "value"))
        self.lblMovimentacoesDiaValor.setText(_translate("PainelEstoque", "0"))
        self.lblMovimentacoesDiaTitulo.setProperty("role", _translate("PainelEstoque", "title"))
        self.lblMovimentacoesDiaTitulo.setText(_translate("PainelEstoque", "Movimentacoes do Dia"))
        self.lblProdutosSection.setProperty("sectionTitle", _translate("PainelEstoque", "true"))
        self.lblProdutosSection.setText(_translate("PainelEstoque", "Produtos e Lotes"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(0)
        item.setText(_translate("PainelEstoque", "Cod."))
        item = self.tableProdutosEstoque.horizontalHeaderItem(1)
        item.setText(_translate("PainelEstoque", "Produto"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(2)
        item.setText(_translate("PainelEstoque", "Categoria"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(3)
        item.setText(_translate("PainelEstoque", "Marca"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(4)
        item.setText(_translate("PainelEstoque", "Lote"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(5)
        item.setText(_translate("PainelEstoque", "Validade"))
        item = self.tableProdutosEstoque.horizontalHeaderItem(6)
        item.setText(_translate("PainelEstoque", "Qtd."))
        item = self.tableProdutosEstoque.horizontalHeaderItem(7)
        item.setText(_translate("PainelEstoque", "Preco Venda"))
        self.lblMovimentacoesSection.setProperty("sectionTitle", _translate("PainelEstoque", "true"))
        self.lblMovimentacoesSection.setText(_translate("PainelEstoque", "Ultimas Movimentacoes de Estoque"))
        item = self.tableMovimentacoesEstoque.horizontalHeaderItem(0)
        item.setText(_translate("PainelEstoque", "Data/Hora"))
        item = self.tableMovimentacoesEstoque.horizontalHeaderItem(1)
        item.setText(_translate("PainelEstoque", "Produto"))
        item = self.tableMovimentacoesEstoque.horizontalHeaderItem(2)
        item.setText(_translate("PainelEstoque", "Tipo"))
        item = self.tableMovimentacoesEstoque.horizontalHeaderItem(3)
        item.setText(_translate("PainelEstoque", "Qtd."))
        item = self.tableMovimentacoesEstoque.horizontalHeaderItem(4)
        item.setText(_translate("PainelEstoque", "Usuario"))
        self.lblStatusSistema.setText(_translate("PainelEstoque", "Sistema online"))
        self.lblStatusBar.setText(_translate("PainelEstoque", "CSPdv - Modulo de Estoque"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PainelEstoque = QtWidgets.QMainWindow()
    ui = Ui_PainelEstoque()
    ui.setupUi(PainelEstoque)
    PainelEstoque.show()
    sys.exit(app.exec_())
